### ISSUE TITLE
jersey targets broken

### ISSUE THREAD

**Issue by fehguy** [swagger-api/swagger-codegen#2678] opened 2016-04-21 16:06 UTC
Something broke swagger-codegen for `jaxrs` targets in master, see https://github.com/swagger-api/swagger.io/issues/101

**Comment by wing328** [comment] 2016-04-21 16:12
@fehguy taking a look..

**Comment by wing328** [comment] 2016-04-21 16:16
Due to missing template:
```
[main] ERROR io.swagger.codegen.AbstractGenerator - can't load template JavaJaxRS/jersey1_18/model_doc.mustache
Exception in thread "main" java.lang.RuntimeException: Could not generate model 'Category'
	at io.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:328)
	at io.swagger.codegen.cmd.Generate.run(Generate.java:223)
	at io.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:36)
Caused by: java.lang.RuntimeException: can't load template JavaJaxRS/jersey1_18/model_doc.mustache
	at io.swagger.codegen.AbstractGenerator.readTemplate(AbstractGenerator.java:50)
	at io.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:314)
	... 2 more
```

**Comment by wing328** [comment] 2016-04-21 16:22
It's due to https://github.com/swagger-api/swagger-codegen/pull/2435 and AbstractJavaJAXRSServerCodegen.java extends JavaClientCodegen.

I've created a PR to rollback the change for the time being: https://github.com/swagger-api/swagger-codegen/pull/2679

**Comment by wing328** [comment] 2016-04-21 16:31
#2679 merged into master.

Pull the latest and running `mvn clean && ./bin/jaxrs-petstore-server.sh` does not throw any exception.

`mvn test` on samples/server/petstore/jaxrs is also successfully.

Sorry for the inconvenience caused by this.

**Closed by wing328** 2016-04-21 16:31 UTC
Labels: Server: Java
