### ISSUE TITLE
Exception caused by: java.util.regex.PatternSyntaxException: Illegal/unsupported escape sequence near index 3 v2\JavaSpring

### ISSUE THREAD

**Issue by thomas-worm-datev** [swagger-api/swagger-codegen#8273] opened 2018-06-05 08:33 UTC
##### Description

I tried to use swagger codegen maven plugin to generate the sources for an openapi 3.0 specification:

```
			<plugin>
				<groupId>io.swagger</groupId>
				<artifactId>swagger-codegen-maven-plugin</artifactId>
				<version>3.0.0-rc1</version>
				<executions>
					<execution>
						<goals>
							<goal>generate</goal>
						</goals>
						<configuration>
							<inputSpec>${project.basedir}/design/openapi.json</inputSpec>
							<language>spring</language>
							<configOptions>
								<java8>true</java8>
								<library>spring-boot</library>
							</configOptions>
						</configuration>
					</execution>
				</executions>
			</plugin>
```

But the generation of sources results in an exception:

```
[ERROR] 
java.lang.RuntimeException: Could not generate model 'user'
	at io.swagger.codegen.DefaultGenerator.generateModels(DefaultGenerator.java:409)
	at io.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:728)
	at io.swagger.codegen.plugin.CodeGenMojo.execute(CodeGenMojo.java:534)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:95)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
	at java.lang.reflect.Method.invoke(Method.java:507)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: java.util.regex.PatternSyntaxException: Illegal/unsupported escape sequence near index 3
v2\JavaSpring
   ^
	at java.util.regex.Pattern.error(Pattern.java:1966)
	at java.util.regex.Pattern.escape(Pattern.java:2482)
	at java.util.regex.Pattern.atom(Pattern.java:2209)
	at java.util.regex.Pattern.sequence(Pattern.java:2141)
	at java.util.regex.Pattern.expr(Pattern.java:2007)
	at java.util.regex.Pattern.compile(Pattern.java:1707)
	at java.util.regex.Pattern.<init>(Pattern.java:1362)
	at java.util.regex.Pattern.compile(Pattern.java:1039)
	at java.lang.String.replaceFirst(String.java:1939)
	at io.swagger.codegen.DefaultGenerator.getHandlebars(DefaultGenerator.java:1014)
	at io.swagger.codegen.DefaultGenerator.processTemplateToFile(DefaultGenerator.java:744)
	at io.swagger.codegen.DefaultGenerator.generateModels(DefaultGenerator.java:396)
	... 24 more
```

##### Swagger-codegen version

swagger-codegen-maven-plugin, 3.0.0-rc1

##### Swagger declaration file content or url

```json
{
  "openapi": "3.0.1",
  "info": {
    "title": "API.",
    "description": "The backend API.",
    "contact": {
      "name": "My Team",
      "url": "http://my/teamsite",
      "email": "My@Team.com"
    },
    "version": "1.0.0"
  },
  "servers": [
    {
      "url": "http://localhost:8080/api/v1",
      "description": "Local system"
    }
  ],
  "paths": {
    "/user": {
      "get": {
        "description": "Returns the current user.",
        "tags": [
          "User"
        ],
        "security": [
          {
            "basicAuthentication": []
          }
        ],
        "responses": {
          "200": {
            "description": "The user information",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/user"
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "user": {
        "description": "An user.",
        "type": "object",
        "required": [
          "userName"
        ],
        "properties": {
          "userName": {
            "description": "The name of the user.",
            "type": "string"
          },
          "displayName": {
            "description": "An alternative name of the user to display.",
            "type": "string"
          }
        }
      }
    },
    "securitySchemes": {
      "basicAuthentication": {
        "type": "http",
        "scheme": "basic"
      }
    }
  }
}
```

##### Command line used for generation

Used within maven.

##### Steps to reproduce

Create a spring boot maven project and add the plugin and swagger file to generate the source.

##### Related issues/PRs

Issue similar to #7509 . Seems not to be closed.

##### Suggest a fix/enhancement

Correct the regex.

**Comment by HugoMario** [comment] 2018-06-09 02:12
@thomas-worm-datev , this has been fixed for `3.0.0-SNAOSHOT`. So let's close this for now, but it can be reopened if you still get the error.

**Closed by HugoMario** 2018-06-09 02:12 UTC

**Comment by yeikel** [comment] 2018-07-17 18:01
I am using 3.0.0-rc1 and I am also getting the same error

**Comment by yeikel** [comment] 2018-07-17 18:14
Is there any release with this fix? @HugoMario

**Comment by cstechfoodie** [comment] 2018-08-17 15:28
I got the same error today for generating the model using 3.0.0-rc1.

**Comment by lperdigaoatTel** [comment] 2018-08-20 13:31
is there a workaround for this?

**Comment by lperdigaoTel** [comment] 2018-08-20 14:09
This might be a Windows problem since running it on Linux resolved the problem for me

**Comment by cstechfoodie** [comment] 2018-08-20 14:15
`servers:
  - url: 'http://localhost:8080/{basePath}'
    description: The server for User Preferences
    variables:
      basePath:
        default: v2`

try this with the new 3.0.0 Snapshot

**Comment by sepphuber** [comment] 2018-08-22 14:10
Hi,  

" Could not find artifact io.swagger:swagger-codegen-maven-plugin:jar:3.0.0-SNAPSHOT"

Does it mean one have to build it from source to use it.
Can I download it somewhere?

Thx

**Comment by lperdigaoTel** [comment] 2018-08-22 14:16
@sepphuber 

https://oss.sonatype.org/content/repositories/snapshots/io/swagger/swagger-codegen-cli/3.0.0-SNAPSHOT/

**Comment by sepphuber** [comment] 2018-08-22 14:36
Thx for the quick answer... it runs with:
<plugin>
		<groupId>io.swagger</groupId>
		<artifactId>swagger-codegen-maven-plugin</artifactId>
<version>3.0.0-rc1</version>	
...
  <dependencies>
	  <dependency>
		<groupId>io.swagger</groupId>
		<artifactId>swagger-codegen-generators</artifactId>
		<version>1.0.0-SNAPSHOT</version>
	  </dependency>
	  <dependency>
		<groupId>io.swagger</groupId>
		<artifactId>swagger-codegen-cli</artifactId>
		<version>3.0.0-SNAPSHOT</version>
	  </dependency>
   </dependencies>
</plugin>	

The reference to swagger-codegen-maven-plugin 3.0.0-SNAPSHOT does not work...

**Comment by filbert3** [comment] 2018-09-05 15:43
Hello, is this fixed in 3.0.0-rc1?

**Comment by HugoMario** [comment] 2018-09-12 20:50
hey @filbert3, this is fixed in [3.0.0](https://github.com/swagger-api/swagger-codegen/releases/tag/v3.0.0)

**Comment by filbert3** [comment] 2018-09-14 14:29
@HugoMario Thank you for the great work!

**Comment by lordnighton** [comment] 2018-11-15 15:30
Got the same thing with `3.0.0-rc1`:

```yml
             <plugin>
                <groupId>io.swagger</groupId>
                <artifactId>swagger-codegen-maven-plugin</artifactId>
                <version>3.0.0-rc1</version>
                <executions>
                    <execution>
                        <id>fapi_data</id>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <inputSpec>${basedir}/src/main/resources/fapi.yml</inputSpec>
                            <language>spring</language>
                            <modelPackage>com.ubs.wma.cdx.model.ui.fapi</modelPackage>
                            <generateApis>false</generateApis>
                            <generateModelTests>false</generateModelTests>
                            <generateSupportingFiles>false</generateSupportingFiles>
                            <configOptions>
                                <dateLibrary>java8</dateLibrary>
                                <serializableModel>true</serializableModel>
                            </configOptions>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
```

**Comment by alvgarvilla** [comment] 2019-01-30 17:57
Same for me, this is not fix in 3.0.0.rc1

**Comment by evipin** [comment] 2019-02-06 16:24
Gettting Same error with **3.0.0-rc1** . It does not seems to be fixed.

[ERROR]
java.lang.RuntimeException: Could not generate model 'XXXABC'
        at io.swagger.codegen.DefaultGenerator.generateModels(DefaultGenerator.java:409)
        at io.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:728)
        at io.swagger.codegen.plugin.CodeGenMojo.execute(CodeGenMojo.java:534)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: java.util.regex.PatternSyntaxException: Illegal/unsupported escape sequence near index 3
v2\Java
   ^
        at java.util.regex.Pattern.error(Pattern.java:1957)
        at java.util.regex.Pattern.escape(Pattern.java:2473)
        at java.util.regex.Pattern.atom(Pattern.java:2200)
        at java.util.regex.Pattern.sequence(Pattern.java:2132)
        at java.util.regex.Pattern.expr(Pattern.java:1998)
        at java.util.regex.Pattern.compile(Pattern.java:1698)
        at java.util.regex.Pattern.<init>(Pattern.java:1351)
        at java.util.regex.Pattern.compile(Pattern.java:1028)
        at java.lang.String.replaceFirst(String.java:2178)
        at io.swagger.codegen.DefaultGenerator.getHandlebars(DefaultGenerator.java:1014)
        at io.swagger.codegen.DefaultGenerator.processTemplateToFile(DefaultGenerator.java:744)
        at io.swagger.codegen.DefaultGenerator.generateModels(DefaultGenerator.java:396)
        ... 24 more

**Comment by nabil86** [comment] 2019-02-20 13:27
I have the same problem:
`java.net.MalformedURLException: no protocol: /api/1.0
        at java.net.URL.<init>(URL.java:593)
        at java.net.URL.<init>(URL.java:490)
        at java.net.URL.<init>(URL.java:439)
        at io.swagger.codegen.utils.URLPathUtil.getServerURL(URLPathUtil.java:30)
        at io.swagger.codegen.DefaultGenerator.configureGeneratorProperties(DefaultGenerator.java:211)
        at io.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:722)
        at io.swagger.codegen.plugin.CodeGenMojo.execute(CodeGenMojo.java:534)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[WARNING] String to be sanitized is null. Default to Object
[WARNING] String to be sanitized is null. Default to Object
[WARNING] String to be sanitized is null. Default to Object
[WARNING] String to be sanitized is null. Default to Object
[WARNING] String to be sanitized is null. Default to Object
[WARNING] String to be sanitized is null. Default to Object
[ERROR]
java.lang.RuntimeException: Could not generate model 'adresseNaissance'
        at io.swagger.codegen.DefaultGenerator.generateModels(DefaultGenerator.java:409)
        at io.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:728)
        at io.swagger.codegen.plugin.CodeGenMojo.execute(CodeGenMojo.java:534)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: java.util.regex.PatternSyntaxException: Illegal/unsupported escape sequence near index 3
v2\Java
   ^
        at java.util.regex.Pattern.error(Pattern.java:1955)
        at java.util.regex.Pattern.escape(Pattern.java:2471)
`

**Comment by PetervLeeuwen** [comment] 2019-06-25 08:51
I was also facing this issue.
But in the maven repository [website ](https://mvnrepository.com/artifact/io.swagger/swagger-codegen-maven-plugin)you can see the artifact was moved.

You should use this [dependency](https://mvnrepository.com/artifact/io.swagger.codegen.v3/swagger-codegen-maven-plugin/3.0.8):

`<dependency>
    <groupId>io.swagger.codegen.v3</groupId>
    <artifactId>swagger-codegen-maven-plugin</artifactId>
    <version>3.0.8</version>
</dependency>
`

Also, adjust it like that in the plugin.

After that, it compiles for me.

**Comment by fabricio-entringer** [comment] 2022-10-05 15:01
> I was also facing this issue. But in the maven repository [website ](https://mvnrepository.com/artifact/io.swagger/swagger-codegen-maven-plugin)you can see the artifact was moved.
> 
> You should use this [dependency](https://mvnrepository.com/artifact/io.swagger.codegen.v3/swagger-codegen-maven-plugin/3.0.8):
> 
> ```
> <dependency>
>     <groupId>io.swagger.codegen.v3</groupId>
>     <artifactId>swagger-codegen-maven-plugin</artifactId>
>     <version>3.0.8</version>
> </dependency>
> ```
> 
> Also, adjust it like that in the plugin.
> 
> After that, it compiles for me.

After try that, now I'm facing this error:
```

Caused by: com.github.jknack.handlebars.HandlebarsException: /handlebars/Java/licenseInfo.mustache:2:6: java.lang.reflect.InaccessibleObjectException: Unable to make public boolean java.util.Collections$EmptyMap.isEmpty() accessible: module java.base does not "opens java.util" to unnamed module @196ae579
    /handlebars/Java/licenseInfo.mustache:2:6
```

Any trick?
