### ISSUE TITLE
Scalatra petstore sample compile error

### ISSUE THREAD

**Issue by clasnake** [swagger-api/swagger-codegen#3171] opened 2016-06-19 11:21 UTC
##### Description

The current scalatra petstore sample generated by the latest template in master doesn't compile.

![image](https://cloud.githubusercontent.com/assets/1590497/16177001/8dda7048-3652-11e6-86bb-cf5d5e06f1de.png)

##### Swagger-codegen version

Current master branch.

##### Steps to reproduce

mvn clean package
./bin/scalatra-petstore-server.sh
cd samples/server/petstore/scalatra/
sbt compile

##### Suggest a Fix

@wing328 Please check if it's a common issue. If yes, I'll take a look at it and create a PR to fix later.

**Comment by wing328** [comment] 2016-06-19 11:44
I will take a look when back home. My guess is due to old mustache tags not
yet migrated as part of the generator migration from scala to Java a year
ago.

**Comment by wing328** [comment] 2016-06-20 07:29
The issue is due to https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/scalatra/api.mustache#L38

It uses several mustache partial for declaring method parameters.

I suggest we reuse the method declaration in Scala API client template to avoid using several partials if possible.

**Comment by clasnake** [comment] 2016-06-20 13:28
Ok, I'll take a look.

**Comment by wing328** [comment] 2016-07-23 13:24
Fixed via https://github.com/swagger-api/swagger-codegen/pull/3394

**Closed by wing328** 2016-07-23 13:24 UTC
Labels: Issue: Bug, Need community contribution, Server: Scala
