### ISSUE TITLE
[nodejs] generated service.js files are placed in the wrong folder

### ISSUE THREAD

**Issue by sandro97git** [swagger-api/swagger-codegen#6443] opened 2017-09-06 09:22 UTC
##### Description

When generating nodejs server code with swagger-codegen-cli, the generated service.js files are placed in the controllers folder but they should be in a folder called service. This folder is not created.

##### Swagger-codegen version

swagger-codegen from master branch. commit b8183fb

##### Swagger declaration file content or url

```yaml
swagger: "2.0"
info:
  description: "This is a sample server Petstore server.  You can find out more about     Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).      For this sample, you can use the api key `special-key` to test the authorization     filters."
  version: "1.0.0"
  title: "Swagger Petstore"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "apiteam@swagger.io"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "petstore.swagger.io"
basePath: "/v2"
tags:
- name: "pet"
  description: "Everything about your Pets"
  externalDocs:
    description: "Find out more"
    url: "http://swagger.io"

schemes:
- "http"
paths:
  /pet/findByStatus:
    get:
      tags:
      - "pet"
      produces:
      - "application/xml"
      - "application/json"
      responses:
        '200':
          headers:
            MyHeader:
              type: string
              default: "*"
          description: "successful operation"
```

##### Command line used for generation

java -DdebugOpeations -jar swagger-codegen-cli.jar generate -i swagger.yaml -l nodejs-server -o out

##### Suggest a fix/enhancement

Probably something has to be corrected in [NodeJSServerCodegen.java](https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/NodeJSServerCodegen.java), so that the service files are correctly placed in the service folder.

**Comment by sandro97git** [comment] 2017-09-06 11:11
I never faced the issue with the online code generator, which I think is because it uses an older release which does not have this bug.

Also I never faced the issue with the docker image of the codegen-cli from docker hub. I don't know why the issue isn't present there. (I think the docker image has always latest source code from master, right?). Maybe this is the case because the docker image runs in linux and not windows? (Path syntax or somethin like this?)

**Comment by DmyMi** [comment] 2017-09-08 19:24
The issue is present only on windows machines with 2.3.0 snapshot codegen. Linux machines are working as intended. 
2.2.x are resolving **-Dservice** flag as intended

**Comment by dlarr** [comment] 2018-02-15 11:25
Hello I have same issue, how is it possible to fix it ?

**Comment by dlarr** [comment] 2018-02-15 15:20
I modified two files in codeGen so generation works

1- DefaultCodegen.java (commented, the old code)
```
    public String apiFilename(String templateName, String tag) {
        String suffix = apiTemplateFiles().get(templateName);
//        return apiFileFolder() + '/' + toApiFilename(tag) + suffix;
        return apiFileFolder() + File.separator + toApiFilename(tag) + suffix;
    }
```

2- NodeJSServerCodegen (commented the old code)

```
@Override
    public String apiFilename(String templateName, String tag) {
        String result = super.apiFilename(templateName, tag);
        LOGGER.warn("In apiFilename");
        LOGGER.warn("templateName = " + templateName);
        LOGGER.warn("tag = " + tag);
        LOGGER.warn("result = " + result);
        
        if (templateName.equals("service.mustache")) {
        	LOGGER.warn("INTO IF");
            String stringToMatch = File.separator + "controllers" + File.separator;
//            String replacement = File.separator + implFolder + File.separator;
            String replacement = (java.io.File.separator.equals("\\") ?  java.io.File.separator + java.io.File.separator : java.io.File.separator) 
        			+ implFolder + 
        			(java.io.File.separator.equals("\\") ?  java.io.File.separator + java.io.File.separator : java.io.File.separator) ;
            LOGGER.warn("stringToMatch = " + stringToMatch);
            LOGGER.warn("replacement = " + replacement);
            String quote = Pattern.quote(stringToMatch);
            LOGGER.warn("quote = " + quote);
            result = result.replaceAll(quote, replacement);
        }
        LOGGER.warn("After if => result = " + result);
        return result;
    }
```

So far it works for now , for node js codegen on windows, with latest 2.4.0-SNAPSHOT project version

**Comment by wing328** [comment] 2018-03-09 12:45
@dlarr do you mind filing a PR so that we can review the fix more easily?

**Comment by dlarr** [comment] 2018-03-09 12:55
Hey, what is a PR ?

**Comment by wing328** [comment] 2018-03-09 12:56
@dlarr I mean a pull request to make changes in the master.

**Comment by dlarr** [comment] 2018-03-09 12:57
Ah ok, I never did this, I can try though.

**Comment by wing328** [comment] 2018-03-09 13:09
I think I know what the problem is. I can file a PR later if you want me to fix it.

**Comment by dlarr** [comment] 2018-03-09 13:16
You can do it no problem !

But just to make sure, I don't know about this PR thing:

1- I need to make my own branche (say fix#6443)
2- I need to commit / push my changes
3- I now have to create a PR from my fix#6443 branch to master

If these steps are ok, I don't have any right to push my branch ;'(

You can fix it yourself as i changed the only 2 lines below original commented code.

Thanks.

**Comment by wing328** [comment] 2018-03-09 13:23
You will need to first folk the repo and makes the changes (in a new branch) in your own repo.

I'll do it shortly and would need your help to review the fix. (I couldn't repeat the issue in my Mac)

**Comment by wing328** [comment] 2018-03-09 14:27
@dlarr @arkolbus I've filed https://github.com/swagger-api/swagger-codegen/pull/7808 to fix the issue. Please review when you've time. Thanks.

**Comment by dlarr** [comment] 2018-03-09 15:52
@wing328 that's not working on windows., That's because File.Separator = '\'

This need to be escaped.
In NodeJSServerCodegen.java, line 172. Delete : 
```java
String replacement = File.separator + implFolder + File.separator;
```

Instead write : 
```java
String replacement = (java.io.File.separator.equals("\\") ?  java.io.File.separator + java.io.File.separator : java.io.File.separator) 
        			+ implFolder + 
        			(java.io.File.separator.equals("\\") ?  java.io.File.separator + java.io.File.separator : java.io.File.separator) ;
```

Should do the trick for all systems

**Closed** 2018-03-12 15:21 UTC
Labels: Issue: Platform, Server: Nodejs

**Comment by wing328** [comment] 2018-03-13 16:19
@sandro97git @DmyMi @dlarr can you please try the latest SNAPSHOT version to see if the issue still occurs?

Ref: https://oss.sonatype.org/content/repositories/snapshots/io/swagger/swagger-codegen-cli/2.4.0-SNAPSHOT/swagger-codegen-cli-2.4.0-20180312.162029-170.jar

**Comment by sandro97git** [comment] 2018-03-17 10:52
@wing328 I just tried with the petstore yml file.
Here's the console output:
```shell
> java -DdebugOpeations -jar .\swagger-codegen-cli-2.4.0-20180312.162029-170.jar generate -i
 .\swaggerfile.yaml -l nodejs-server -o out
[main] INFO io.swagger.parser.Swagger20Parser - reading from ./swaggerfile.yaml
[main] INFO io.swagger.codegen.ignore.CodegenIgnoreProcessor - No .swagger-codegen-ignore file found.
Exception in thread "main" java.lang.RuntimeException: Could not generate api file for 'Pet'
        at io.swagger.codegen.DefaultGenerator.generateApis(DefaultGenerator.java:543)
        at io.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:750)
        at io.swagger.codegen.cmd.Generate.run(Generate.java:285)
        at io.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:35)
Caused by: java.lang.IllegalArgumentException: character to be escaped is missing
        at java.util.regex.Matcher.appendReplacement(Unknown Source)
        at java.util.regex.Matcher.replaceAll(Unknown Source)
        at java.lang.String.replaceAll(Unknown Source)
        at io.swagger.codegen.languages.NodeJSServerCodegen.apiFilename(NodeJSServerCodegen.java:161)
        at io.swagger.codegen.DefaultGenerator.generateApis(DefaultGenerator.java:496)
        ... 3 more
```

Am I doing something wrong or is there a problem with this SNAPSHOT version?
