### ISSUE TITLE
Add cookieParams to CodegenOperation

### ISSUE THREAD

**Issue by rbiersbach** [swagger-api/swagger-codegen#8794] opened 2018-10-09 15:25 UTC
##### Description

On writing a new code generator for scala akka http server I noticed that for open api 3.0 cookies can be defined as parameters. As all other parameters, cookies should also be provided as List<CodegenParameter> in the CodegenOperation class, as they are allready added to the "allParams" variable.

##### Swagger-codegen version

3.x.x

##### Suggest a fix/enhancement
**Before:**
`  
public List<CodegenParameter> allParams = new ArrayList<CodegenParameter>();
public List<CodegenParameter> bodyParams = new ArrayList<CodegenParameter>();
public List<CodegenParameter> pathParams = new ArrayList<CodegenParameter>();
public List<CodegenParameter> queryParams = new ArrayList<CodegenParameter>();
public List<CodegenParameter> headerParams = new ArrayList<CodegenParameter>();
public List<CodegenParameter> formParams = new ArrayList<CodegenParameter>();
`
**After:**
`   
public List<CodegenParameter> allParams = new ArrayList<CodegenParameter>();
public List<CodegenParameter> bodyParams = new ArrayList<CodegenParameter>();
public List<CodegenParameter> pathParams = new ArrayList<CodegenParameter>();
public List<CodegenParameter> queryParams = new ArrayList<CodegenParameter>();
public List<CodegenParameter> headerParams = new ArrayList<CodegenParameter>();
public List<CodegenParameter> formParams = new ArrayList<CodegenParameter>();
public List<CodegenParameter> cookieParams = new ArrayList<CodegenParameter>();
`

**Comment by nataliaoliveira** [comment] 2019-10-29 10:50
any updates on this issue?

**Comment by frantuma** [comment] 2019-12-11 14:27
this should be duplicate of #9820 which has been fixed

**Closed by frantuma** 2019-12-11 14:27 UTC
Labels: Enhancement: General
