### ISSUE TITLE
error when building swagger file with relative $ref files

### ISSUE THREAD

**Issue by jamiehannaford** [swagger-api/swagger-codegen#1193] opened 2015-09-04 14:08 UTC
When I generate HTML docs from [this](https://github.com/jamiehannaford/swagger-magnum/blob/jamie/v1/swagger.json) Swagger file, I get an error. This is the command I'm using:

```bash
./run-in-docker.sh generate \
-i https://raw.githubusercontent.com/jamiehannaford/swagger-magnum/jamie/v1/swagger.json \
-o samples/html \
-l html
```

and this is the error I get:

> + docker run -it -w /gen -v /Users/jamie/projects/other/swagger-codegen:/gen -v /Users/jamie/.m2/repository:/root/.m2/repository maven:3-jdk-7 java -jar /gen/modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate -i https://raw.githubusercontent.com/jamiehannaford/swagger-magnum/jamie/v1/swagger.json -o samples/html -l html
reading from https://raw.githubusercontent.com/jamiehannaford/swagger-magnum/jamie/v1/swagger.json
PATH refs can not be internal references (through reference chain: io.swagger.models.RefPath["$ref"]) (through reference chain: io.swagger.models.Swagger["paths"]->java.util.LinkedHashMap["/baymodels"])
reading from https://raw.githubusercontent.com/jamiehannaford/swagger-magnum/jamie/v1/swagger.json
PATH refs can not be internal references (through reference chain: io.swagger.models.RefPath["$ref"]) (through reference chain: io.swagger.models.Swagger["paths"]->java.util.LinkedHashMap["/baymodels"])
Exception in thread "main" java.lang.RuntimeException: missing swagger input or config!
	at io.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:60)
	at io.swagger.codegen.cmd.Generate.run(Generate.java:134)
	at io.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:35)

Why is it not accepting `$ref`s to internal or relative files? The [example](https://github.com/swagger-api/swagger-spec/blob/master/examples/v2.0/json/petstore-separate/spec/swagger.json#L36) in the spec allows it.

**Comment by jamiehannaford** [comment] 2015-09-04 15:14
@wing328 ah okay, no worries :smile: 

Does `swagger-ui` support it? I noticed some JS errors when I tried the same thing

**Comment by wing328** [comment] 2015-09-04 15:19
I'm not sure. I would suggest you to ask in `swagger-ui` project page to get the official answer.

**Comment by ChrisTitos** [comment] 2015-09-07 09:48
This exception is caused by something in swagger-core. A pull request has been opened, but not merged yet.

https://github.com/swagger-api/swagger-core/issues/1388

**Comment by fehguy** [comment] 2015-09-09 14:28
@jamiehannaford Looks like you have a JSON parse error in your referenced file:

https://raw.githubusercontent.com/jamiehannaford/swagger-magnum/jamie/v1/baymodels/operations.json#

The `delete` 204 response has a trailing comma.

**Comment by jamiehannaford** [comment] 2015-09-09 16:56
@fehguy Good catch, thanks! When I fix that JSON line, I still get various errors. When I specify a local file:

> java.io.FileNotFoundException: /Users/jamie/projects/openstack/swagger-magnum/v1/swagger.json (No such file or directory)
	at java.io.FileInputStream.open(Native Method)
	at java.io.FileInputStream.<init>(FileInputStream.java:146)
	at com.fasterxml.jackson.core.JsonFactory.createParser(JsonFactory.java:708)
	at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:1861)
	at io.swagger.parser.SwaggerCompatConverter.readResourceListing(SwaggerCompatConverter.java:147)
	at io.swagger.parser.SwaggerCompatConverter.read(SwaggerCompatConverter.java:82)
	at io.swagger.parser.SwaggerParser.read(SwaggerParser.java:36)
	at io.swagger.codegen.cmd.Generate.run(Generate.java:133)
	at io.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:35)
Exception in thread "main" java.lang.RuntimeException: missing swagger input or config!
	at io.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:60)
	at io.swagger.codegen.cmd.Generate.run(Generate.java:134)
	at io.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:35)

When I specify a remote file:

> reading from https://raw.githubusercontent.com/jamiehannaford/swagger-magnum/master/v1/swagger.json
java.net.UnknownHostException: raw.githubusercontent.com
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:178)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:579)
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:637)
	at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:160)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:275)
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:371)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:933)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:153)
	at io.swagger.parser.util.RemoteUrl.urlToString(RemoteUrl.java:98)
	at io.swagger.parser.Swagger20Parser.read(Swagger20Parser.java:27)
	at io.swagger.parser.SwaggerParser.read(SwaggerParser.java:27)
	at io.swagger.codegen.cmd.Generate.run(Generate.java:133)
	at io.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:35)
raw.githubusercontent.com
reading from https://raw.githubusercontent.com/jamiehannaford/swagger-magnum/master/v1/swagger.json
java.net.UnknownHostException: raw.githubusercontent.com
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:178)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:579)
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:637)
	at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:160)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:275)
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:371)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:933)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:153)
	at io.swagger.parser.util.RemoteUrl.urlToString(RemoteUrl.java:98)
	at io.swagger.parser.Swagger20Parser.read(Swagger20Parser.java:27)
	at io.swagger.parser.SwaggerParser.read(SwaggerParser.java:36)
	at io.swagger.codegen.cmd.Generate.run(Generate.java:133)
	at io.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:35)
raw.githubusercontent.com
java.net.UnknownHostException: raw.githubusercontent.com
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:178)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:579)
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:637)
	at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:160)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:275)
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:371)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:933)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:153)
	at io.swagger.parser.util.RemoteUrl.urlToString(RemoteUrl.java:98)
	at io.swagger.parser.SwaggerCompatConverter.readResourceListing(SwaggerCompatConverter.java:144)
	at io.swagger.parser.SwaggerCompatConverter.read(SwaggerCompatConverter.java:82)
	at io.swagger.parser.SwaggerParser.read(SwaggerParser.java:36)
	at io.swagger.codegen.cmd.Generate.run(Generate.java:133)
	at io.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:35)
java.net.UnknownHostException: raw.githubusercontent.com
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:178)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:579)
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:637)
	at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:160)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:275)
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:371)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:933)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:153)
	at io.swagger.parser.util.RemoteUrl.urlToString(RemoteUrl.java:98)
	at io.swagger.parser.SwaggerCompatConverter.readResourceListing(SwaggerCompatConverter.java:144)
	at io.swagger.parser.SwaggerCompatConverter.read(SwaggerCompatConverter.java:82)
	at io.swagger.parser.SwaggerParser.read(SwaggerParser.java:36)
	at io.swagger.codegen.cmd.Generate.run(Generate.java:133)
	at io.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:35)
Exception in thread "main" java.lang.RuntimeException: missing swagger input or config!
	at io.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:60)
	at io.swagger.codegen.cmd.Generate.run(Generate.java:134)
	at io.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:35)

**Comment by fehguy** [comment] 2015-10-26 00:13
Hi, you must be experiencing some network issue.  The UnknownHostErrors are valid, but not (I think) caused by codegen.  Please reopen if you need more help.

**Closed by fehguy** 2015-10-26 00:13 UTC
