### ISSUE TITLE
[Python] Flask server Swagger validation fails for GET and type file

### ISSUE THREAD

**Issue by etsardou** [swagger-api/swagger-codegen#3786] opened 2016-09-13 11:02 UTC
##### Description

I'm trying to implement a GET call which returns a file from the server using Swagger 2.0 specifications and python-flask server autogeneration from the Swagger online service (https://generator.swagger.io/#/). My swagger specifications are valid Swagger 2.0 as can be checked from the swagger editor (http://editor.swagger.io/#/) and the Python Flask server code is auto-generated successfully, but upon launch a validation error arises.
##### Swagger-codegen version

The online version https://generator.swagger.io/#/
##### Swagger declaration file content or url

The specifications follow:

```
swagger: '2.0'
info:
  version: "0.0.0"
  title: Test
paths:
  /file/{id}:
    get:
      description: Returns a specific file from the server
      parameters:
        - name: id
          in: path
          description: The file to be transferred
          required: true
          type: integer
      produces:
        - 'multipart/form-data'
      consumes:
        - 'application/json'
      responses:
        200:
          description: Successful response
          schema:
            type: file
```

, the python-flask server is successfully generated, but upon launch I get the following error:

```
Traceback (most recent call last):
  File "app.py", line 7, in <module>
    app.add_api('swagger.yaml', arguments={'title': 'No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)'})
  File "/usr/local/lib/python2.7/dist-packages/connexion/app.py", line 149, in add_api
    debug=self.debug)
  File "/usr/local/lib/python2.7/dist-packages/connexion/api.py", line 107, in __init__
    validate_spec(spec)
  File "/usr/local/lib/python2.7/dist-packages/swagger_spec_validator/validator20.py", line 82, in validate_spec
    http_handlers=http_handlers)
  File "/usr/local/lib/python2.7/dist-packages/swagger_spec_validator/common.py", line 22, in wrapper
    sys.exc_info()[2])
  File "/usr/local/lib/python2.7/dist-packages/swagger_spec_validator/common.py", line 17, in wrapper
    return method(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/swagger_spec_validator/validator20.py", line 125, in validate_json
    cls=Draft4Validator)
  File "/usr/local/lib/python2.7/dist-packages/swagger_spec_validator/ref_validators.py", line 34, in validate
    instance_cls(schema, *args, **kwargs).validate(instance)
  File "/usr/local/lib/python2.7/dist-packages/jsonschema/validators.py", line 123, in validate
    raise error
swagger_spec_validator.common.SwaggerValidationError: {'description': 'Successful response', 'schema': {'type': 'file'}} is not valid under any of the given schemas

Failed validating 'oneOf' in schema['properties']['paths']['patternProperties']['^/']['properties']['get']['properties']['responses']['patternProperties']['^([0-9]{3})$|^(default)$']:
    {'oneOf': [{'$ref': '#/definitions/response'},
               {'$ref': '#/definitions/jsonReference'}]}

On instance['paths']['/file/{id}']['get']['responses']['200']:
    {'description': 'Successful response', 'schema': {'type': 'file'}}
make: *** [server-launch-python] Error 1
```

**Comment by wing328** [comment] 2016-10-02 08:26
@etsardou thanks for reporting the issue. I don't think `file` response type is supported in the Python Flask generator at the moment.

May I know if you've time to help contribute a fix? If yes, I can show you some good starting points.

**Comment by etsardou** [comment] 2016-10-02 08:49
My available time is quite limited at the moment, but I guess pointing out some directions would be useful for the community, since anyone can get into it.

**Comment by wing328** [comment] 2016-10-02 12:21
@etsardou no worry. I'll take a look tomorrow and hopefully file a PR for the fix.

**Comment by wing328** [comment] 2016-10-03 01:26
@etsardou according to the error:
```
swagger_spec_validator.common.SwaggerValidationError: {'description': 'Successful response', 'schema': {'type': 'file'}} is not valid under any of the given schemas

Failed validating 'oneOf' in schema['properties']['paths']['patternProperties']['^/']['properties']['get']['properties']['responses']['patternProperties']['^([0-9]{3})$|^(default)$']:
    {'oneOf': [{'$ref': '#/definitions/response'},
               {'$ref': '#/definitions/jsonReference'}]}

On instance['paths']['/file/{id}']['get']['responses']['200']:
    {'description': 'Successful response', 'schema': {'type': 'file'}}
```

`type: file` is not valid according to JSON schema validator. 

As a workaround, please change it to `type: string` instead.

I discover another issue when `tags` is not provided and am working on it. Please workaround it by adding a tag to the endpoint for the time being: https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/test/resources/2_0/petstore.yaml#L442

**Comment by wing328** [comment] 2016-10-03 01:57
The endpoint without tag issue has been addressed by #3913.

Please pull the latest to give it a try.

**Comment by etsardou** [comment] 2016-10-03 04:58
Thanks, I will give it a try with the string type. 

Just to clarify things, the ```type: file``` is not a valid swagger specification (since the error is raised by SwaggerValidationError)? If yes this is strange since the ```type: file``` exists in the Swagger 2.0 specifications and the Swagger online editor accepts it as valid.

Do you know where I can ask or open an issue about this?

Thanks in advance!

**Comment by wing328** [comment] 2016-10-03 05:12
`type: file` is valid from Swagger/OpenAPI standpoint but since Python Flask leverages JSON schema validator to validate the input spec, the error is related to JSON schema but not Swagger.

In the future we may want to update the validator to throw warnings instead of errors.

**Comment by etsardou** [comment] 2016-10-03 06:56
Ok great, thnx!

**Comment by SellamiRami** [comment] 2017-01-19 09:46
@etsardou , @wing328 

I have the error message as @etsardou : 
```

$ python3 -m swagger_server
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/swagger_spec_validator/common.py", line 17, in wrapper
    return method(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/swagger_spec_validator/validator20.py", line 125, in validate_json
    cls=Draft4Validator)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/swagger_spec_validator/ref_validators.py", line 34, in validate
    instance_cls(schema, *args, **kwargs).validate(instance)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/jsonschema/validators.py", line 123, in validate
    raise error
jsonschema.exceptions.ValidationError: {'description': 'Successful response', 'schema': {'$ref': '#/definitions/Response', 'x-scope': ['']}, 'examples': {'data': {'referencePoints': [{'inputAddress': 'Rue Francois Van Assche 1, 1140 Evere', 'StreetSegment': '21006A001003690AH32_2', 'PositionX': '4.3985262', 'PositionY': '50.8766102', 'Mosaic': 'H32', 'QualityCodeMosaic': '1', 'QualityCodeLocalisation': '1', 'QualityCodeINS9': '1'}]}, 'metadata': 'This is a metadata description'}} is not valid under any of the given schemas

Failed validating 'oneOf' in schema['properties']['paths']['patternProperties']['^/']['properties']['get']['properties']['responses']['patternProperties']['^([0-9]{3})$|^(default)$']:
    {'oneOf': [{'$ref': '#/definitions/response'},
               {'$ref': '#/definitions/jsonReference'}]}

On instance['paths']['/referencepoint']['get']['responses']['200']:
    {'description': 'Successful response',
     'examples': {'data': {'referencePoints': [{'Mosaic': 'H32',
                                                'PositionX': '4.3985262',
                                                'PositionY': '50.8766102',
                                                'QualityCodeINS9': '1',
                                                'QualityCodeLocalisation': '1',
                                                'QualityCodeMosaic': '1',
                                                'StreetSegment': '21006A001003690AH32_2',
                                                'inputAddress': 'Rue '
                                                                'Francois '
                                                                'Van '
                                                                'Assche 1, '
                                                                '1140 '
                                                                'Evere'}]},
                  'metadata': 'This is a metadata description'},
     'schema': {'$ref': '#/definitions/Response', 'x-scope': ['']}}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/rs/swagger-codegen/output/flask/swagger_server/__main__.py", line 10, in <module>
    app.add_api('swagger.yaml', arguments={'title': 'This API enables to get the positions X and Y, and the mosaic code based on a given address'})
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/connexion/app.py", line 149, in add_api
    debug=self.debug)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/connexion/api.py", line 109, in __init__
    validate_spec(spec)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/swagger_spec_validator/validator20.py", line 82, in validate_spec
    http_handlers=http_handlers)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/swagger_spec_validator/common.py", line 22, in wrapper
    sys.exc_info()[2])
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/swagger_spec_validator/common.py", line 17, in wrapper
    return method(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/swagger_spec_validator/validator20.py", line 125, in validate_json
    cls=Draft4Validator)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/swagger_spec_validator/ref_validators.py", line 34, in validate
    instance_cls(schema, *args, **kwargs).validate(instance)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/jsonschema/validators.py", line 123, in validate
    raise error
swagger_spec_validator.common.SwaggerValidationError: {'description': 'Successful response', 'schema': {'$ref': '#/definitions/Response', 'x-scope': ['']}, 'examples': {'data': {'referencePoints': [{'inputAddress': 'Rue Francois Van Assche 1, 1140 Evere', 'StreetSegment': '21006A001003690AH32_2', 'PositionX': '4.3985262', 'PositionY': '50.8766102', 'Mosaic': 'H32', 'QualityCodeMosaic': '1', 'QualityCodeLocalisation': '1', 'QualityCodeINS9': '1'}]}, 'metadata': 'This is a metadata description'}} is not valid under any of the given schemas

Failed validating 'oneOf' in schema['properties']['paths']['patternProperties']['^/']['properties']['get']['properties']['responses']['patternProperties']['^([0-9]{3})$|^(default)$']:
    {'oneOf': [{'$ref': '#/definitions/response'},
               {'$ref': '#/definitions/jsonReference'}]}

On instance['paths']['/referencepoint']['get']['responses']['200']:
    {'description': 'Successful response',
     'examples': {'data': {'referencePoints': [{'Mosaic': 'H32',
                                                'PositionX': '4.3985262',
                                                'PositionY': '50.8766102',
                                                'QualityCodeINS9': '1',
                                                'QualityCodeLocalisation': '1',
                                                'QualityCodeMosaic': '1',
                                                'StreetSegment': '21006A001003690AH32_2',
                                                'inputAddress': 'Rue '
                                                                'Francois '
                                                                'Van '
                                                                'Assche 1, '
                                                                '1140 '
                                                                'Evere'}]},
                  'metadata': 'This is a metadata description'},
     'schema': {'$ref': '#/definitions/Response', 'x-scope': ['']}}
```

The problem is related to the use of the `examples` object in the swagger-editor. It is noteworthy that I tried to remove all the `examples` blocks and the error message dissiperas. I illustrate a part of the yaml specification file: 

```yaml
...
responses:
        # Response code
        200:
          description: "Successful response"
          schema:
            $ref: "#/definitions/Response"
          examples: 
            data:
              referencePoints:
              - inputAddress: "Rue Francois Van Assche 1, 1140 Evere"
                StreetSegment: "21006A001003690AH32_2"
                PositionX: "4.3985262"
                PositionY: "50.8766102" 
                Mosaic: "H32"
                QualityCodeMosaic: "1"
                QualityCodeLocalisation: "1"
                QualityCodeINS9: "1"
            metadata: "This is a metadata description" 
...
```
Could you please help me in fixing my problem.

I am very thankful in advance.

**Comment by etsardou** [comment] 2017-01-19 09:49
I think this issue was fixed in a newer version of the swagger-codegen (I do not know if the online version was updated yet). @klpanagi can you elaborate on the solution?

**Comment by SellamiRami** [comment] 2017-01-19 09:51
Thank you @etsardou for your reactivity. 

I am using the latest version of the swagger-codegen. I done yesterday a clone.

**Comment by klpanagi** [comment] 2017-01-19 13:02
Hi @SellamiRami 

The is an issue of the  [swagger-spec-validator v2.0.2](https://github.com/Yelp/swagger_spec_validator) that [connexion](https://github.com/zalando/connexion/blob/master) uses to validate responses and has been resolved in **v2.0.3**.

Resources:
- OAI/OpenAPI-Specification#260
- Yelp/swagger_spec_validator#50

An easy way to install (or upgrade) **swagger-spec-validator-v2.0.3** is to fetch directly from the upstream repo:

```bash
$ pip install https://github.com/Yelp/swagger_spec_validator/archive/v2.0.3.zip -U
```

**Comment by etsardou** [comment] 2017-01-19 13:11
@wing328 I think with @klpanagi 's answer the issue can be closed!

**Comment by SellamiRami** [comment] 2017-01-19 13:56
@klpanagi thank you for response. I have already detected the problem. In fact, I putted the `type` of `parameters` (e.g. string, integer, etc.) between " " and the boolean values ( true or false)  of the `required` attribute between " " also. 

I removed that and it perfectly works now. 

Thank you for your support.

Have a nice day :)

**Closed** 2017-01-19 14:00 UTC
Labels: Issue: Bug, Server: Python

**Comment by sagnik** [comment] 2019-08-07 04:16
I am seeing the exact same error with this spec:

```
  /file/download/{sha1}/:
    get:
      tags:
      - "xpctl"
      summary: "download a file"
      description: ""
      operationId: "download_file"
      consumes:
      - "application/json"
      produces:
      - "application/binary"
      parameters:
      - name: "sha1"
        in: "path"
        type: "string"
        required: True
      responses:
        200:
          schema:
            type: "file"
        default:
          description: "unexpected error"
          schema:
            $ref: "#/definitions/Response"
```

I am using [swagger codegen cli jar 2.4.5](http://central.maven.org/maven2/io/swagger/swagger-codegen-cli/2.4.5/swagger-codegen-cli-2.4.5.jar)

**Comment by sagnik** [comment] 2019-08-07 04:41
I found out the reason: 
```
        200:
          schema:
            type: "file"
 ```
should have a `description` field. The error message is a bit cryptic though for this problem.
