### ISSUE TITLE
[angular5] typescript-angular5 support coming?

### ISSUE THREAD

**Issue by lukas41** [swagger-api/swagger-codegen#7324] opened 2018-01-05 07:39 UTC
##### Description

swagger-codegen currently only supports typescript-angular (alias angularjs) and typescript-angular2 (I assume angular 2 and 4).
Now there is angular5 available to use, but it is a bit different from angular 2 and 4. There are some changes in syntax and in some (core) modules.

In my case

> **core**: `OpaqueToken` has been removed as it was deprecated since v4. Use `InjectionToken` instead. 

##### Command line used for generation

`node ./node_modules/swagger-codegen-cli/bin/swagger-codegen generate -i path/to/swagger.json -l typescript-angular2 -o ./src/app/services/swagger-connector/`

##### Steps to reproduce

Try to use swagger-code gen with angular5 dependencies and a variable which should be exported and injected.

##### Suggest a fix/enhancement

Will there be support for typescript-angular5 any time soon?
I assume more and more people will use angular5 in the future

**Comment by wing328** [comment] 2018-01-07 01:52
@lukas41 I'm not aware of anyone working on that. Would you have time to contribute the enhancement?

cc @TiFu  @taxpon  @sebastianhaas  @kenisteward  @Vrolijkx

**Comment by kenisteward** [comment] 2018-01-07 01:56
What do you mean by "angular 5 support"?

**Comment by kenisteward** [comment] 2018-01-07 01:56
The codegen currently work with angular 5 just fine

**Comment by kenisteward** [comment] 2018-01-07 01:59
Sorry was on my phone. You can simply pass the angular version you are using in additional properties.  

Also I believe you aren't using latest because the language should be typescript-angular not angular2

**Comment by macjohnny** [comment] 2018-01-08 06:38
I can confirm @kenisteward s post: the generated code works fine with angular 5 by specifying `ngVersion: 4.3` when generating the code

**Comment by wing328** [comment] 2018-01-08 10:02
@lukas41 let us know if you still need help with the `typescript-angular` generator. Closing this issue for the time being..

**Closed by wing328** 2018-01-08 10:02 UTC
Labels: Client: TypeScript, Enhancement: Feature

**Comment by kenisteward** [comment] 2018-01-08 13:01
You can specufy 5 as the library will add angular as a peer dependency

**Comment by lukas41** [comment] 2018-02-19 13:00
sorry for the long wait.

Maybe I don't get it, or I wasn't able to explain my problem.

If I use typescript-angular to generate my code, it uses angular.js (angular1). Or in other words, I get many more errors.

If I use typescript-angular2 it still uses the OpaqueToken, which is not supported in angular5 anymore.
Perhaps this is a fault in our backend, but I don't think so.

@wing328 where can I change the ngVersion?
@macjohnny should it be ngVersion: 4.3 or 5.1.0? @wing328 said 4.3 is default and I should use 5.1

**Comment by wing328** [comment] 2018-02-25 09:59
@lukas41 you can change it in the config.json (passed via `-c` command), e.g.
```
{
  "ngVersion": "5.1"
}
```

Hope this helps.

**Comment by lukas41** [comment] 2018-02-26 07:50
@wing328 I am sorry, but this didn't change anything.

Here is someone else facing the same issue, maybe this post helps: 
https://stackoverflow.com/questions/48260208/why-error-in-angular-5-as-has-no-exported-member-opaquetoken

**Comment by kenisteward** [comment] 2018-02-26 15:53
@lukas41 You are using the incorrect version of the cli....
you need to update to at least version 2.3.0 to get the proper generation.  

There is no longer typescript-angular   typescript-angular2

There is typescript-angularjs  and typescript-angular.

Please update and let me know.

**Comment by lukas41** [comment] 2018-02-27 07:09
@kenisteward wow, finally. Thank you.
@wing328 It is working with the config file as well.

Using Version 2.3.1 (which won't install via npm@latest) and either the config file, or the additional-properties flag it generates valid angular5 without the removed `OpaqueToken`.

(I noticed the name change from `typescript-angular2` to `typescript-angular`.
Much better and less confusing:+1:)

**Comment by kenisteward** [comment] 2018-02-27 14:01
Glad to hear it buddy ;)
