### ISSUE TITLE
[Java-PlayFramework] Error 500 on bad user input

### ISSUE THREAD

**Issue by edrevo** [swagger-api/swagger-codegen#6126] opened 2017-07-20 13:25 UTC
##### Description

The generated controllers do not perform parameter validation. Specifically:

- if a required parameter is not passed, the controller does not return a 401, it just reads `null` and continues with the execution (which will probably generate an exception somewhere down the line)
- if a parameter doesn't conform to the expected type, an error 500 is returned, since the conversion will throw an exception (example: parameter `test` is of type `integer` but a request has a value of `"thisIsAString"`)
- if a parameter has a `default` value and no value is passed, null is used (which will fail type conversion and return error 500)
- "maximum", "minimum", "pattern", "enum" and similar properties of swagger (see https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#parameter-object) are not validated

##### Swagger-codegen version

2.2.3

##### Swagger declaration file content or url

```json
{
  "swagger": "2.0",
  "info": {
    "title": "My Sample API",
    "version": "0.0.1"
  },
  "schemes": [
    "https"
  ],
  "host": "www.example.com",
  "basePath": "/v1",
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "paths": {
    "/event": {
      "get": {
        "summary": "Event Types",
        "description": "The event endpoint returns information about all the registered event types in the system\n",
        "parameters": [
          {
            "in": "query",
            "name": "test",
            "type": "integer",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "An array of event definitions",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Event"
              }
            }
          }
        }
      }
    }
  },
  "definitions": {
    "Event": {
      "type": "object",
      "properties": {
        "event_id": {
          "type": "string",
          "description": "URL-safe unique identifier representing a specific event type"
        },
        "description": {
          "type": "string",
          "description": "A human readable description of what the event represents"
        }
      }
    }
  }
}
```

**Comment by JFCote** [comment] 2017-07-20 14:56
Hi @edrevo, thanks for the report.
I realized this morning that I forgot to submit a very important PR like 1 month ago that, I think, fix most of the issue listed here. You can follow it here: #6125 

Can you please try with the code in this PR when it will be merged in the master and report back if it fixes most of your problems? We will work from there to improve.

Thanks

**Comment by JFCote** [comment] 2017-08-07 16:59
@wing328 : This should be closed since it was closed in #6125

**Comment by edrevo** [comment] 2017-08-16 07:05
I don't think this issue is fixed. AFAICT, #6125 adds explicit validation for some of the issues I mentioned, but the result of the validation is still an exception, which will still yield error 500 on bad user input.

**Comment by JFCote** [comment] 2017-08-16 11:56
@edrevo : Can you give a sample spec with a use case so I can understand what exactly the problem is? Also, what do you suggest to fix the issue. I have some time this week so I could work on the issue. But first, I need to understand it completely.

**Comment by JFCote** [comment] 2017-08-16 12:20
Let's look at each of your points one by one: :)

> if a required parameter is not passed, the controller does not return a 401, it just reads null and continues with the execution (which will probably generate an exception somewhere down the line)

Since the spec and the server is expecting a value, isn't it normal for the server to throw some kind of exception when something excepted is not there? I believe it is. Also, 401 http code is for Unauthorized and is related to authentication. This has nothing to do with data validation. By the way, with fix #6125 , all of the Bean Validations are done, but if the bean itself is missing, right now it will throw an exception. Maybe I could add a better handling of this but what you can do right now is add a switch case with most common exception you want to handle in the ErrorHandler class and do your business logic related to that (issue a special http code, redirect to a page, etc...). @wing328 , is there some standard way to deal with this kind of problem in the other generators?

> if a parameter doesn't conform to the expected type, an error 500 is returned, since the conversion will throw an exception (example: parameter test is of type integer but a request has a value of "thisIsAString")

What do you suggest the server should do instead? @wing328 , is there any "standard" in the other generator for this specific case? Adding try/catch for each conversion could be a solution but it would send an exception in the end anyway.

> if a parameter has a default value and no value is passed, null is used (which will fail type conversion and return error 500)

This seems to be a bug. Can you provide a sample yaml for this specific case and a sample client request to the server so I can test it and fix it.

> "maximum", "minimum", "pattern", "enum" and similar properties of swagger (see https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#parameter-object) are not validated

This has been fixed in #6125 .

On a more general note, **I think most of these use cases should not append often in real life**. You need to generate client using swagger-codegen and give it to developer using your server. That way, they will not try to provide bad input. If people still want to use your REST api by hands, then it is not a big deal that the server throw some exception since it's a special case.

But like I said, I'm open for enhancements (and have a little bit of time) and will be waiting for your explanation/details on each case stated above and I will do my best to provide a fix.

Thanks for using and testing the Play Framework Generator :)

**Comment by JFCote** [comment] 2017-11-15 13:46
@edrevo Do you have additional information related to my comment above or should we close this bug?

**Comment by edrevo** [comment] 2017-11-16 07:45
Hi @JFCote, we ended up forking this codegen to suit our needs, so feel free to close the bug if you want. Wrt to your comments, I think the correct behavior if a client is breaking the swagger contract by passing in an invalid value is to return an error 400 (bad request). In my previous comment I mixed up 400 and 401, sorry about that. Cheers!

**Comment by JFCote** [comment] 2017-11-16 13:31
Ok thanks for the feedback @edrevo 
There is definitely things that can be improved in the error handling. I'm taking notes of you comment for my next improvement PR.

If, in the meantime, you come back to our codegen, please  consider creating a new bug for the things you think are important. If you can separate each problem in its own task/bug, it will also help us to prioritize each of them.

@wing328 You can close this.

**Closed** 2017-12-17 14:35 UTC
Labels: Issue: Bug, Server: Java
