### ISSUE TITLE
go-client: cannot use a.Configuration.GetAPIKeyWithPrefix("apikey") (type string) as type []string in assignment

### ISSUE THREAD

**Issue by loretoparisi** [swagger-api/swagger-codegen#3849] opened 2016-09-22 10:13 UTC
When  generating the `go-client-generated.zip` from editor.swagger.io I get several error in the generated code like

`swagger/album_api.go:139: cannot use a.Configuration.GetAPIKeyWithPrefix("apikey") (type string) as type []string in assignment`

due to a bad assign to `[]string` literal of a `string`.
I'm pretty new to `go`, so I'm not sure if this is due to a recent go compiler (See later).
##### Description

``` go
queryParams["apikey"] =  a.Configuration.GetAPIKeyWithPrefix("apikey")
```
##### Swagger-codegen version

I'm using

```
$ go version
go version go1.7.1 darwin/amd64
```

and latest swagger codegen from editor.swagger.io.
##### Swagger declaration file content or url

The file is available online at https://playground.musixmatch.com/swagger.json.
##### Steps to reproduce
1. import from url the swagger definition above in the Swagger Editor
2. Generate the Go client
3. Open README.md
## 
##### Suggest a Fix

The fix is to replace this assignment

``` go
queryParams["apikey"] =  a.Configuration.GetAPIKeyWithPrefix("apikey")
```

with

``` go
queryParams.Add("apikey",a.Configuration.GetAPIKeyWithPrefix("apikey"))
```

I have achieved this from [this](http://stackoverflow.com/questions/13820280/encode-decode-urls) example of usage of `url.Values{}`.

**Comment by wing328** [comment] 2016-09-22 10:56
@loretoparisi thanks for reporting the issue.

cc @guohuang

**Comment by loretoparisi** [comment] 2016-09-22 12:34
Welcome!
I also suggest to add this example, that for `go` beginners like me, took half a day to complete it!

```go
/*
 * Musixmatch Go Client
 * @uses Swagger generated Go client
 * @author Loreto Parisi (loreto at musixmatch dot com)
 * @see https://developer.musixmatch.com/documentation
 *  @copy 2016 Musixmatch Spa
*/
package main

import (
    "fmt"
    "bytes"
    "encoding/json"
    "./swagger"
    "io"
    "io/ioutil"
    "os"
)

func jsonPrettyPrint(in string) string {
    var out bytes.Buffer
    err := json.Indent(&out, []byte(in), "", "\t")
    if err != nil {
        return in
    }
    return out.String()
}
func main() {

    albumApi := swagger.NewAlbumApi()

    configuration := albumApi.Configuration
    configuration.SetDebug(true)
    configuration.APIKey["apikey"] = "YOUR_API_KEY"

    var albumId = "14250417"
    jsonResponse, response, _  := albumApi.AlbumGetGet(albumId,"json","")

    defer response.Body.Close()
   htmlData, err := ioutil.ReadAll(io.LimitReader(response.Body, 2048))
   // unmarshall struct to json
    b, err := json.Marshal(jsonResponse.Message)
    if err != nil {
        fmt.Println(err)
        return
    }
    var c = jsonPrettyPrint( string(b) )
    fmt.Println(c)

}
```

**Comment by guohuang** [comment] 2016-09-22 17:51
@loretoparisi I tried using Go version 1.7.1 on windows, I couldn't reproduce the compilation issue that you have,  the function `GetAPIKeyWithPrefix` is only returning string, not []string, so i don't know what the issue is.

**Comment by wing328** [comment] 2017-02-16 16:47
Closing this as there's no further update.

**Closed by wing328** 2017-02-16 16:47 UTC
Labels: Client: Go, Issue: Bug
