### ISSUE TITLE
[JAVA] Bug generating top level enum definitions (doesn't compile)

### ISSUE THREAD

**Issue by diega** [swagger-api/swagger-codegen#3355] opened 2016-07-12 21:19 UTC
##### Description
If I create an enum definition for using it in many objects, I get this file generated with compiling errors.

##### Swagger-codegen version
I'm using `master`

##### Swagger declaration file content or url
```yaml
swagger: '2.0'

info:
  version: "1.0.0"
  title: Title was not specified
host: 'localhost:9090'
basePath: /base
schemes:
  - http
paths:
  /test:
    get:
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/FooObject'
      operationId: getFooObject
definitions:
  FooObject:
    properties:
      myEnum:
        $ref: '#/definitions/BarEnum'
  BarEnum:
    type: string
    enum:
      - AENUM
      - BENUM
```

##### Command line used for generation
`java -jar swagger-codegen-cli.jar generate -i test.yml -l spring -o swagger-output/`

#### Output
I get this exact output
```
package io.swagger.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonValue;

public enum BarEnum {
    {values&#x3D;[AENUM, BENUM], enumVars&#x3D;[{name&#x3D;AENUM, value&#x3D;&quot;AENUM&quot;}, {name&#x3D;BENUM, value&#x3D;&quot;BENUM&quot;}]},
}
```

**Comment by jeff9finger** [comment] 2016-07-12 21:30
I'm seeing this as well. Shouldn't this work? I am using language=jaxrs and library=jersey2

**Comment by wing328** [comment] 2016-07-13 03:53
Can you try `library=okhttp-gson` instead to see if that works for you?

(we've not applied enum enhancement to all Java-related generator yet)

**Comment by diega** [comment] 2016-07-13 04:18
This doesn't work:
`java -jar swagger-codegen-cli.jar generate -i test.yml -l spring --library okhttp-gson -o swagger-output/` 
  > unknown library: okhttp-gson

**Comment by wing328** [comment] 2016-07-13 07:04
@diega sorry I was not clear. `okhttp-gson` is for Java API client so please use `-l java` instead.

**Comment by diega** [comment] 2016-07-13 08:24
@wing328 no problem!
Yes, it seems like running `java -jar swagger-codegen-cli.jar generate -i test.yml -l java --library okhttp-gson -o swagger-output/` generates the enum properly, but it does `java -jar swagger-codegen-cli.jar generate -i test.yml -l java -o swagger-output/` as well. Indeed, I tried setting `--library` for all the options in the documentation (jersey2, feign, okhttp-gson, retrofit and retrofit2) and all generates the enum just fine.
It looks like something related to the **spring** language (and **jaxrs**, as pointed by @jeff9finger)

**Comment by wing328** [comment] 2016-07-13 08:28
@diega thanks for performing more test to confirm. If you've cycle, we would welcome contribution to apply the same fix in Java API client to Java server stub generator.

**Comment by diega** [comment] 2016-07-13 08:37
@wing328 sure, is there some fix already applied to _client_ generation you think could be applied to the _server_ generation?

**Comment by wing328** [comment] 2016-07-13 10:02
@diega are you using the latest master to generate the `spring` server stub? 

As shown in https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/JavaSpring/model.mustache, the model generated in `spring` has support for enum already.

**Comment by diega** [comment] 2016-07-13 10:06
@wing328 yes I am.
Has you been able to reproduce it using the _yml_ definition I attached in my original report?

**Comment by wing328** [comment] 2016-07-13 10:08
@diega I will give it a try later today (busy with other things at the moment...)

**Comment by diega** [comment] 2016-07-13 10:09
@wing328 thanks! is there any chance for it to be included into the v2.2.0 milestone?

**Comment by wing328** [comment] 2016-07-13 10:13
cc @cbornet

**Comment by lucazamador** [comment] 2016-07-14 14:23
I'm affected by this **critical** issue as well. Any news regarding including the fix in v2.2.0? Thanks!

**Comment by wing328** [comment] 2016-07-14 14:59
I could repeat the issue using the spec provided by @diega 

I'll try to fix it but not sure if we can merge the fix into 2.2.0 release, which should be due shortly.

**Comment by jeff9finger** [comment] 2016-07-15 20:01
I am going to give this a try. It looks like changes in the mustache templates.

**Comment by jeff9finger** [comment] 2016-07-15 21:01
@wing328 Are you working on this? Don't want to duplicate effort.

**Comment by wing328** [comment] 2016-07-16 03:49
@jebentier I'm busy with other works. If you've time, please give it a try. Thanks.

**Comment by wing328** [comment] 2016-07-16 03:49
As 2.2.0 will be out soon, we'll not include the fix, if ready, in the 2.2.0 release.

**Comment by diega** [comment] 2016-07-20 17:47
Just in case somebody needs some kind of _workaround_, running this on the root of your project cleanups the enums
`$ find . -name *.java -print0 | xargs -0 sed -i '' 's/.*\[\(.*\)\],.*/    \1/'`

**Comment by dennisTS** [comment] 2016-08-02 12:49
The issue is really annoying and presumably isn`t related to mustache templates, but rather to the input to those templates. Looking forward to the fix a lot

**Comment by wing328** [comment] 2016-08-02 13:52
@jeff9finger did you have a chance to work on the fix?

**Comment by wing328** [comment] 2016-08-02 17:39
UPDATE: I've submitted to https://github.com/swagger-api/swagger-codegen/pull/3506 to fix the issue for JAX-RS (and also another issue with PHP enum handling).

I'll work on the fix for `spring` tomorrow.

**Comment by jeff9finger** [comment] 2016-08-02 21:35
Thanks. I have not been able to get to this.

**Comment by wing328** [comment] 2016-08-03 11:03
#3511 (fixed models with enum properties for `spring`) has been merged into master.

Please pull the latest master to give it a try.

**Closed** 2016-08-03 11:02 UTC
Labels: Feature: Enum, Issue: Bug, Server: Java

**Comment by diega** [comment] 2016-08-03 14:19
I can confirm this is working now. Thanks @wing328!

**Comment by jeff9finger** [comment] 2016-08-03 14:57
Yes thanks @wing328 !!!!
