### ISSUE TITLE
Android Codegen - Apache HTTP Client Removal

### ISSUE THREAD

**Issue by maneeshsahu** [swagger-api/swagger-codegen#1478] opened 2015-10-30 20:11 UTC
The Android codegen uses Apache HTTP Client. Android 6 has removed support for Apache HTTP Client and recommends using HttpURLConnection instead. See: http://developer.android.com/about/versions/marshmallow/android-6.0-changes.html#behavior-apache-http-client

**Comment by wing328** [comment] 2015-10-31 14:51
@maneeshsahu the Java client can also be compatible with Android and Scala depending on what HTTP library is chosen when generating the client. Please run the following for more information on how to customize the Java API client.
```
java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar config-help -l java
```

If you've cycle, we would appreciate your contribution to add the support of "HttpURLConnection" in the Java API client.

**Comment by cbornet** [comment] 2015-11-02 10:18
Duplicate of #1353 ?

**Comment by wing328** [comment] 2016-01-23 08:06
@maneeshsahu We've added the support of `android-valley` in the Android API client thanks to the contribution from @shyri 

Please use that one instead.

**Closed by wing328** 2016-01-23 08:06 UTC
Labels: Client: Android, Need community contribution
