### ISSUE TITLE
PHP Generator does not generate comma's between string array values

### ISSUE THREAD

**Issue by Klyner007** [swagger-api/swagger-codegen#8345] opened 2018-06-22 13:44 UTC
##### Description

When generating a project, the generated models contain array properties which are not formatted right. Between multiple array values there should be a comma but it is not there.

##### Swagger-codegen version

3.0.0 SNAPSHOT

**Comment by HugoMario** [comment] 2018-06-28 08:59
Hello @Klyner007 , can you please check an example of your `output`? Also if it's possible for you to share the spec you used it would be helpful too.

**Comment by hampsterx** [comment] 2018-10-03 01:27
@HugoMario half fixed~

3.0.0-SNAPSHOT/swagger-codegen-cli-3.0.0-20180710.190537-87.jar

```
 protected static $swaggerTypes = [
        'id' => 'int',
        'title' => 'string',
        'description' => 'string'
    ];
```

but still busted here..

```
  protected static $attributeMap = [
        'id' => 'id''title' => 'title''description' => 'description'
    ];
```

**Comment by bnowak** [comment] 2018-12-10 09:16
Hi,
Any news here?

I have similar problem in version 3.0.3. It's not generate commas properly in method parameters:
`java -jar swagger-codegen-cli-3.0.3.jar generate -i https://developer.allegro.pl/swagger.yaml -o . -l php --type-mappings BigDecimal=integer`

generated code:
```php
    /**
     * Operation changePublicationStatusUsingPUT
*
     * Modify multiple offers publication at once.
*
* @param  \GreenCell\AllegroRestApiClient\Model\PublicationChangeCommandDto $body publicationChangeCommandDto (required)
* @param  string $commandId commandId (required)
*
     * @throws \GreenCell\AllegroRestApiClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \GreenCell\AllegroRestApiClient\Model\GeneralReport
     */
    public function changePublicationStatusUsingPUT($body$commandId)
    {
        list($response) = $this->changePublicationStatusUsingPUTWithHttpInfo($body$commandId);
        return $response;
    }
```
Do you know anything about this problem? How now can I modify templates for `php`? - I don't see any directory with templates in 3.x version.

**Comment by Avacadros** [comment] 2019-01-16 15:09
@bnowak Hey, I have a solution. It's not great, but it looks like this problem was introduced after 3.0.0 (at least for Spring/Spring Boot). Try reverting version back from 3.0.3 to 3.0.0 and see if this is fixed for you. Hoping to see this fixed in 3.0.4 so I can stay up to date! 😄

**Comment by HugoMario** [comment] 2019-01-23 10:39
@hampsterx , can you please check again? i checked this for 3.0.4 and it's fixed. going to close it but let me know if the issue is still present and i'll work on it.

**Closed by HugoMario** 2019-01-23 10:39 UTC

**Comment by zefj** [comment] 2019-02-19 17:20
@HugoMario are you sure it's fixed? I'm running `swaggerapi/swagger-codegen-cli-v3:3.0.4` Docker container and just got this exact issue. Generated code:

`public function method($body$arg1, $arg2, $arg3)`

**Comment by bnowak** [comment] 2019-02-26 08:42
it works in 3.0.5  
thanks :smile:
