### ISSUE TITLE
C# client does not support text/html output

### ISSUE THREAD

**Issue by ThomasBarnekow** [swagger-api/swagger-codegen#928] opened 2015-06-29 08:08 UTC
I have created a swagger.json file (through Swashbuckle) describing an API that produces text/html (nothing else). The response for "200" defines a schema with a prinitive "type": "string" (no format). 

Now, with swagger-ui, everything works nicely. The response body contains the HTML returned by the Web API. The generated C# client, however, tries to deserialize the string into JSON, which obviously fails. When I (1) remove the generated line of code that attempts to deserialize the `response.Content` and (2) replace that with a simple `return response.Content`, everything works as expected.

Since it works in swagger-ui, which also says the swagger is valid, I'd expect it to work in the generated clients as well. But the code generation seems to ignore the "produces" declaration alltogether. If the API does not prodoce any JSON (text/json, application/json), the client will nevertheless try to deserialize `response.Content` into JSON (unless the `type` passed to the `ApiClient`'s `Deserialize` method is `Object`).

**Comment by wing328** [comment] 2015-06-29 14:26
@ThomasBarnekow thanks for reporting the issue. I've put in a fix in my latest C# PR #927 

I wonder if you can help perform a test to confirm it fixes the issue for you.

I notice you've other feedback as well such as C# style guide (which is partly addressed in the same PR) but I'll review again to make sure the output (C# code) conforms to the style guide.

**Comment by ThomasBarnekow** [comment] 2015-06-29 15:09
Happy to test. How would I do that?

**Comment by wing328** [comment] 2015-06-29 15:27
I just pushed a fix to the parameter naming (e.g. petId instead of PetId). Please help review that as well

Here are the steps:
- git clone https://github.com/wing328/swagger-codegen
- git checkout csharp_file_response
- mvn clean && ./bin/csharp-petstore.sh

or you can use the CLI to test: 
```
java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate \
  -i http://petstore.swagger.io/v2/swagger.json \
  -l csharp \
  -o /var/tmp/csharp/
```

**Comment by ThomasBarnekow** [comment] 2015-06-29 21:13
I've now tested your PR. Here's what I found out:

1. The naming convention issues are fixed. This looks good now (and I'll spare you any other nitpicks for now ;-)
2. The `using IO.Swagger.Model;` is still generated, even though I don't have any models defined in my swagger.son (which I manually edited because Swashbuckle creates an `Object` model that is not used (about which the swagger editor then complains)).
3. You turned the `string` parameter representing the file name (for `"type": "file"`) into a `FileStream`. Not sure why exactly you did that. At a later point, only the stream's `Name` property is used. Thus, sticking to a `string` parameter containing the name of the file to be uploaded might be a better choice.
4. Whatever changes you made (possibly in addition to number 3), this seems to break something. The request is aborted (i.e., the final `return (Object) await restClient.ExecuteTaskAsync(request);` in `ApiClient.CallApiAsync` returns a response with empty `Content` and an `ErrorMessage` saying "Request aborted".

Please tell me if there's anything else I can do to help.

**Comment by ThomasBarnekow** [comment] 2015-06-29 21:53
I've now replaced `FileStream upload` with `string upload` in the signature of the API methods that are created (with upload being the name of the parameter denoting the name of the file to be uploaded in my example). It now works! Thus, using `FileStream` as the C# type for Swagger input parameters having `"type": "file"` created the problem.

**Comment by lakeba** [comment] 2015-06-29 22:55
@ThomasBarnekow Could you please share here your API methods signature?

**Comment by wing328** [comment] 2015-06-30 02:34
@ThomasBarnekow thanks for performing the tests. The reason why i switched to FileStream is because file can also be used as a response (file download) and returning a FileStream should be easier for developers to handle the downloaded file (so that they can read/move the file right away)

Here is an example on how to upload the file:
```
PetApi petApi = new PetApi ();
petApi.UploadFile(petId, "new form name", new System.IO.FileStream("/var/tmp/small.gif", FileMode.Open, FileAccess.Read));
```

For 4, did you get the same error using the sync version of the method ?
I tested with GetPetByIdAsync and UploadFileAsync and didn't encounter the issue you mentioned above.

**Comment by wing328** [comment] 2015-06-30 02:40
For 2, are you using the latest version of Swashbuckle, which should have the `Object` issue fixed?

**Comment by ThomasBarnekow** [comment] 2015-06-30 07:40
@labeka Here's the swagger.json for my web service (running on Azure):
```
{
  "swagger" : "2.0",
  "info" : {
    "version" : "v1",
    "title" : "ContractArchitect.WebApi"
  },
  "host" : "contractarchitect.azurewebsites.net",
  "schemes" : [ "http" ],
  "paths" : {
    "/api/Transformation" : {
      "post" : {
        "tags" : [ "Transformation" ],
        "operationId" : "Transformation_PostFormData",
        "consumes" : [ "multipart/form-data" ],
        "produces" : [ "text/html" ],
        "parameters" : [ {
          "name" : "upload",
          "in" : "formData",
          "description" : "The file to be uploaded",
          "required" : true,
          "type" : "file"
        }, {
          "name" : "docTypeAndNumber",
          "in" : "formData",
          "description" : "The document type and number",
          "required" : false,
          "type" : "string"
        }, {
          "name" : "docTitle",
          "in" : "formData",
          "description" : "The document title",
          "required" : false,
          "type" : "string"
        }, {
          "name" : "docSetType",
          "in" : "formData",
          "description" : "The document set type",
          "required" : false,
          "type" : "string"
        }, {
          "name" : "docSetTitle",
          "in" : "formData",
          "description" : "The document set title",
          "required" : false,
          "type" : "string"
        }, {
          "name" : "customerName",
          "in" : "formData",
          "description" : "The customer name",
          "required" : false,
          "type" : "string"
        }, {
          "name" : "providerName",
          "in" : "formData",
          "description" : "The provider name",
          "required" : false,
          "type" : "string"
        }, {
          "name" : "docRevisionNumber",
          "in" : "formData",
          "description" : "The document revision number",
          "required" : false,
          "type" : "string"
        }, {
          "name" : "issueDate",
          "in" : "formData",
          "description" : "The issue date",
          "required" : false,
          "type" : "string"
        }, {
          "name" : "responseDate",
          "in" : "formData",
          "description" : "The response date",
          "required" : false,
          "type" : "string"
        } ],
        "responses" : {
          "200" : {
            "description" : "Successful transformation",
            "schema" : {
              "type" : "string"
            }
          },
          "400" : {
            "description" : "Malformed request"
          },
          "415" : {
            "description" : "Unsupported media type"
          }
        }
      }
    }
  }
}
```
Here is the C# interface that is generated:
```
  public interface ITransformationApi {
    
    /// <summary>
    ///  
    /// </summary>
    /// <param name="upload">The file to be uploaded</param>
    /// <param name="docTypeAndNumber">The document type and number</param>
    /// <param name="docTitle">The document title</param>
    /// <param name="docSetType">The document set type</param>
    /// <param name="docSetTitle">The document set title</param>
    /// <param name="customerName">The customer name</param>
    /// <param name="providerName">The provider name</param>
    /// <param name="docRevisionNumber">The document revision number</param>
    /// <param name="issueDate">The issue date</param>
    /// <param name="responseDate">The response date</param>
    /// <returns>string</returns>
    string TransformationPostFormData (FileStream upload, string docTypeAndNumber, string docTitle, string docSetType, string docSetTitle, string customerName, string providerName, string docRevisionNumber, string issueDate, string responseDate);

    /// <summary>
    ///  
    /// </summary>
    /// <param name="upload">The file to be uploaded</param>
    /// <param name="docTypeAndNumber">The document type and number</param>
    /// <param name="docTitle">The document title</param>
    /// <param name="docSetType">The document set type</param>
    /// <param name="docSetTitle">The document set title</param>
    /// <param name="customerName">The customer name</param>
    /// <param name="providerName">The provider name</param>
    /// <param name="docRevisionNumber">The document revision number</param>
    /// <param name="issueDate">The issue date</param>
    /// <param name="responseDate">The response date</param>
    /// <returns>string</returns>
    Task<string> TransformationPostFormDataAsync (FileStream upload, string docTypeAndNumber, string docTitle, string docSetType, string docSetTitle, string customerName, string providerName, string docRevisionNumber, string issueDate, string responseDate);
  }
```
When I change `FileStream upload` into `string upload` (everywhere, of course), everything works fine.

In my code, I created the stream with `new FileStream("Contract.docx", FileMode.Open)` (note the absence of `FileAccess.Read`). The generated code passes only the file name to the `ApiClient` instance. I suspect that the `RestClient` instance tries to open a `FileStream` on the same file. That likely fails because I opened it in ReadWrite mode implicitly.

I'd say that if we can't pass a `FileStream` instance to the `RestClient`, using `FileStream` as the type of the `file` parameter is not a good idea. If you can pass stream's, though, I'd say it is better to use `Stream` instead of a `FileStream`, because you could also create files in memory, e.g., in a `MemoryStream` and pass that on to the `RestClient`.

**Comment by wing328** [comment] 2015-06-30 08:04
@ThomasBarnekow thanks for sharing with us how you create the FileStream and the issue you encountered.

Seems like using Stream (e.g. FileStream) would make things complicated. I'll switch back to the old method using "string" (full path to the file) and update the response to return the file path (in the temp folder) instead. If this won't meet your requirement or you foresee potential issue, please let me know.

**Comment by lakeba** [comment] 2015-06-30 08:52
@ThomasBarnekow How you getting contractarchitect.azurewebsites.net in host ? I am only able to get domain:80

**Comment by wing328** [comment] 2015-06-30 09:52
@ThomasBarnekow updated the PR to use "String" for file type. Please kindly perform another test to see if now works better for you.

**Comment by ThomasBarnekow** [comment] 2015-06-30 10:00
@lakeba I'm not sure I understand your question. The swagger.json was generated by Swashbuckle which infers the host name from the server's URL. I did not enter that manually. And note that I manually removed the model declaration from the generated file, which is why the one I posted here does not contain that.

Anyhow, as I deployed the same web service to multiple servers, I create the `ApiClient` with an explicit URL, like so:
```
var apiClient = new ApiClient("http://contractarchitect.azurewebsites.net");
```
If you go to http://contractarchitect.azurewebsites.net/swagger, you should see the swagger-ui for my Web API. If you go to http://contractarchitect.azurewebsites.net/swagger/docs/v1, you can download the auto-generated swagger.json (with the definition of an `"Object"` model).

**Comment by ThomasBarnekow** [comment] 2015-06-30 10:09
@wing328 Thanks, I will be able to test in the evening (German time).

Considering the response type, getting a `Stream` back as the response is fine. I would ideally have the choice of processing everything in memory rather than having to store files on disk. File I/O will slow things down, so I'd only want to create a file if that's what I need.

Can you know and control how the whole processing chain works? Does the `RestClient` return a `Stream` or the name of the file it has already stored on disk?

**Comment by wing328** [comment] 2015-06-30 10:23
Given that the type `file` is used for both upload and download, it must be of the same type - both set to `String` in the latest PR. 

I would like to custom it to use stream but it would not be easy (like we need a separate type in the spec to achieve this)

To answer your question, the returned `file` is a String (full path) with the file stored on disk (in the temp directory or a directory specified in Configuration). Would this meet your requirement? I know ideally you want to use a MemoryStream to process but it may require a lot of effort.

**Comment by ThomasBarnekow** [comment] 2015-06-30 11:05
Leave it like that that for now. We can talk about optimizations at a later point in time. Thanks a lot!

**Comment by lakeba** [comment] 2015-06-30 19:35
The Json you shared with us have the "host" : "contractarchitect.azurewebsites.net", the json from  http://contractarchitect.azurewebsites.net/swagger/docs/v1 have "host" : "contractarchitect.azurewebsites.net:80", just curious to understand the difference.

**Comment by ThomasBarnekow** [comment] 2015-06-30 20:10
@lakeba As I said, I edited the swagger.json, e.g., to remove the unused Object model. I guess I removed the ":80" as well.

Did you have an issue with the HTTP port number being added? I don't know whether that is added by Swashbuckle or the swagger-ui.

**Comment by lakeba** [comment] 2015-06-30 20:41
Yes I have an issue with the HTTP port number as Android VM is interpreting the :80 wrongly and I am still trying to understand from Swashbuckle guys how to remove it.

**Comment by ThomasBarnekow** [comment] 2015-06-30 20:54
@wing328 Good news. I've tested your latest commit and it works :-)

I then thought it would be time to talk about some nitpicks, e.g., the fact that some comments are not well-formed and that we could optimize some code. In the following example, the param tag is not closed and the constructor could be streamlined:
```
    /// <summary>
    /// Initializes a new instance of the <see cref="TransformationApi"/> class.
    /// </summary>
    /// <param name="apiClient"> an instance of ApiClient (optional)
    /// <returns></returns>
    public TransformationApi(ApiClient apiClient = null) {
      if (apiClient == null) { // use the default one in Configuration
        this.ApiClient = Configuration.DefaultApiClient; 
      } else {
        this.ApiClient = apiClient;
      }
    }
```
It could look like this:
```
    /// <summary>
    /// Initializes a new instance of the <see cref="TransformationApi"/> class.
    /// </summary>
    /// <param name="apiClient">An instance of ApiClient.</param>
    public TransformationApi(ApiClient apiClient = null)
    {
        ApiClient = apiClient ?? Configuration.DefaultApiClient;
    }
```
I closed the `param` tag and removed the `returns` tag (which is never used with constructors). I also streamlined the body.

I also thought that using `String` instead of `string` for the file name was just an inconsistency, because all "string" parameters are using `string`. But then I saw this:
```
    // if return type is "String" (not "string"), it implies a Filestream and should return the file path
    String returnTypeString = "string";
    Type returnType = returnTypeString == "String" ? typeof(FileStream) : typeof(string);
    return (string) ApiClient.Deserialize(response.Content, returnType, response.Headers);
```
To be honest, this looks like a hack. Don't you have access to the actual swagger type, i.e., "file" or "string"? Should that be the case I would generate code that is appropriate for "file" vs. other return types rather than doing runtime checking.

Further, you should use `string` instead of `String` in C#. While they are really one and the same (with `string` being an alias for `String`, which is why your code above looks like a hack), general guidance is to go with `string` (see http://stackoverflow.com/questions/7074/whats-the-difference-between-string-and-string, for example).

**Comment by ThomasBarnekow** [comment] 2015-06-30 21:20
@lakeba Just tried a URL with a port number, using the C# client. No problem here. 

In this case, the port number is not really required because 80 is the well-known port for HTTP. But what would happen if you had to access a web service listening to 8080, for example? Would that be a general problem with the Android VM?

**Comment by wing328** [comment] 2015-07-01 01:19
@ThomasBarnekow yes, it's a hack and understood that they're essentially the same. I'll take another look to see if the "original" type (file) is available somehow.

For the return tag, I'll update it to make it available only if it has a return.

**Comment by wing328** [comment] 2015-07-01 07:41
Updated the PR to omit <return></return> if the endpoint returns void.

For "File" type, I checked again and confirm currently there's no way for the template to obtain the original type before the mapping. I totally agree the workaround (hack) is not pretty.

To avoid the hack, one way we discussed before is to use `Stream` for file (parameter input and response) but it would take some time to implement.

Another approach that might work is using byte[] (byte array) for file: parameter input and response.

**Comment by ThomasBarnekow** [comment] 2015-07-01 07:52
@wing328 I have had a look at the `RestSharp.RestClient`. It uses the `FileParameter` class to represent files to be uploaded. It is in fact very flexible because you can effectively use multiple ways to provide file data.
* Firstly, you can just specify a file's path, meaning the `RestRequest` instance will create an `Action<Stream>` that reads the file and copies its contents onto the `Stream` instance provided at a later point in time. 
* Secondly, you can provide a `byte[]` containing the file's contents. This effectively creates an `Action<Stream>` that will write the whole array to the `Stream` instance.
* Thirdly, you can provide an `Action<Stream>` instance. If you wanted to have the API caller provide a `FileStream` (or better `Stream`), you could create an action that reads from that stream and writes to the output stream.
To do that, though, you'd have to change the `ApiClient` class.

**Comment by wing328** [comment] 2015-07-01 08:05
@ThomasBarnekow so I think the way to go is to use `Stream` unless anyone has any concern.

**Comment by wing328** [comment] 2015-07-01 13:55
@ThomasBarnekow updated the PR with "Stream" for file (method parameter, response). For response, the actual type is "FileStream", which can capture the (optional) file name in content-disposition
```
Content-Disposition: attachment; filename=FILENAME
```
I tested with the following and the results are good
1) MemoryStream as method parameter
2) FileStream as method parameter
3) Return type set to `string`
4) Return type set to  `file`

I wonder if you can spend some time to review to see if it looks good from your perspective.

**Comment by ThomasBarnekow** [comment] 2015-07-01 16:37
@wing328 I pulled (and received changes), built (using `mvn package`), and generated code as follows:
```
java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate -i swagger.json -l csharp -o csharp
```
The jars are new and the C# files get updated, but the "file" parameter is still a `String`. Am I doing something wrong?

**Comment by ThomasBarnekow** [comment] 2015-07-01 22:29
OK, did a `mvn clean` and a `mvn package` and re-generated code. Now I see a `Stream` parameter for a "file" input. However, the request is aborted again. I have no idea why that happens because it happens silently. No exception is thrown and the error message is not helpful, either.

Any idea?

**Comment by wing328** [comment] 2015-07-02 00:20
@ThomasBarnekow do you mind showing me the code on how you called the method ?

**Comment by wing328** [comment] 2015-07-02 03:20
@ThomasBarnekow Updated PR to selectively import `models` when at least one model is defined. Please help perform a test.

**Comment by ThomasBarnekow** [comment] 2015-07-02 16:08
@wing328 Here's the code:
```
var apiClient = new ApiClient();
var testApi = new TransformationApi(apiClient);

const string relativePath = "Contract.docx";
var result = testApi.TransformationPostFormData(new FileStream(relativePath, FileMode.Open, FileAccess.Read), 
    "Exhibit 1", "Service Catalog", null, null, null, null, null, null, null);
```

**Comment by ThomasBarnekow** [comment] 2015-07-02 19:22
@wing328 Just out of curiosity: why is the `ApiClient` even needed? Couldn't you use the `RestClient` directly?

**Comment by ThomasBarnekow** [comment] 2015-07-02 19:59
@wing328 `RestClient` keeps telling me `The request was aborted`. This seems to be a `System.Net.WebException`. Thus, whatever you have done lately introduced that error.

**Comment by wing328** [comment] 2015-07-03 06:31
The reason why we use ApiClient is to make the C# SDK design more consistent with SDKs of other languages. Also wrapping RestSharp with ApiClient would make it easier to switch to other REST/HTTP library with ease in the future should there be a better alternative.

May I know which .net framework and OS you're using ?

**Comment by ThomasBarnekow** [comment] 2015-07-03 06:42
@wing328 Developing with VS 2013. Targeting 4.5.1. Installed Runtime 4.5.2. Running on Windows 7 (latest Service Pack and all).

**Comment by wing328** [comment] 2015-07-03 07:13
For RestSharp, are you using the DLL included in the SDK or obtain it from NuGet ?

**Comment by ThomasBarnekow** [comment] 2015-07-03 09:03
I obtained it from NuGet (latest version). As that just said "The request was aborted", I cloned the GitHub repo, built, and included the DLL targeting 4.5.1. Both created the same error message with the generated API. Even through debugging, I couldn't find out why the request is aborted.

I then created some API methods manually, using the `RestClient` directly and leaving out some of my parameters to keep it a bit shorter:
```
    public class CustomTransformationApi
    {
        public CustomTransformationApi(string baseUrl)
        {
            RestClient = new RestClient(baseUrl);
        }

        private RestClient RestClient { get; set; }

        public string PostFormData(string path, string docTypeAndNumber, string docTitle)
        {
            var request = new RestRequest("api/Transformation", Method.POST);
            request.AddFile("upload", path);
            request.AddParameter("docTypeAndNumber", docTypeAndNumber);
            request.AddParameter("docTitle", docTitle);

            return RestClient.Execute(request).Content;
        }

        public string PostFormData(Stream stream, string fileName, string docTypeAndNumber, string docTitle)
        {
            var request = new RestRequest("api/Transformation", Method.POST);
            request.AddFile("upload", stream.ReadAsBytes(), fileName);
            request.AddParameter("docTypeAndNumber", docTypeAndNumber);
            request.AddParameter("docTitle", docTitle);

            return RestClient.Execute(request).Content;
        }

        public string PostFormData(byte[] bytes, string fileName, string docTypeAndNumber, string docTitle)
        {
            var request = new RestRequest("api/Transformation", Method.POST);
            request.AddFile("upload", bytes, fileName);
            request.AddParameter("docTypeAndNumber", docTypeAndNumber);
            request.AddParameter("docTitle", docTitle);

            return RestClient.Execute(request).Content;
        }
    }
```
Using the `Stream` example, this is called as follows:
```
    const string baseUrl = "http://contractarchitect.azurewebsites.net";
    const string relativePath = "Contract.docx";
    const string docTypeAndNumber = "Exhibit 1";
    const string docTitle = "Service Catalog";

    var api = new CustomTransformationApi(baseUrl);

    using (var stream = new FileStream(relativePath, FileMode.Open, FileAccess.Read))
    {
        var result = api.PostFormData(stream, relativePath, docTypeAndNumber, docTitle);
        ...
    }
```
All variants work without any issue. When omitting `FileAccess`, this works as well.

The following still doesn't work, though (using the same constants as above):
```
    var api = new TransformationApi(baseUrl);

    using (var stream = new FileStream(relativePath, FileMode.Open, FileAccess.Read))
    {
        var result = api.TransformationPostFormData(stream, relativePath, docTypeAndNumber, docTitle, null, null, null, null, null, null);
        ...
    }
```
The error message (mind you no exception is thrown) is always "The request was aborted".

**Comment by ThomasBarnekow** [comment] 2015-07-03 09:10
BTW, `ReadAsBytes()` is an extension method provided by RestSharp. It is exactly the same as the corresponding `ApiClient` method that you took from stackoverflow.com.

**Comment by wing328** [comment] 2015-07-03 09:46
@ThomasBarnekow thanks for the test result above. I was able to narrow down the issue to Async call and the filename. 

`CallApi` relies on the async version of `CallApi` to make the request. I've updated `CallApi` to directly make the call using `RestSharp.Execute` and tcpdump confirms the body "looks" good.

Another issue is the filename. The server (petstore) is expecting just the file name while the methods send the file name with full path (e.g. /var/tmp/small.gif). Using `Path.GetFileName` resolves the issue.

Please kindly pull the latest and let me know if the fixes above work for you.

For the Async issue, I'll report it to RestSharp.

**Comment by ThomasBarnekow** [comment] 2015-07-03 10:33
@wing328 Unfortunately, nothing really changed. As you now throw an exception, the error is no longer silently ignored. However, it is still the same issue, i.e., the request is aborted.

The interesting thing is that all works well when using the `RestClient` directly. When debugging the server, my server method is not invoked when using the generated API.

Here's the server-side method:
```
        /// <summary>
        /// Takes a Word file posted as part of multi-part form data and transforms the
        /// file into HTML.
        /// </summary>
        /// <returns>The HTTP response containing the HTML document</returns>
        [HttpPost]
        [SwaggerResponse(HttpStatusCode.OK, "Successful transformation", typeof(string))]
        [SwaggerResponse(HttpStatusCode.BadRequest, "Malformed request")]
        [SwaggerResponse(HttpStatusCode.UnsupportedMediaType, "Unsupported media type")]
        public async Task<HttpResponseMessage> PostFormData()
        {
            if (!Request.Content.IsMimeMultipartContent())
            {
                return Request.CreateErrorResponse(HttpStatusCode.BadRequest,
                    "Malformed request. Please post multipart/form-data.");
            }
            ...
        }
```
When I put a breakpoint on the first `if` expression, it is never hit when using the generated API. It is hit when using `RestClient` directly.

Are you testing against the pet store server or mine? Does it work with the pet store server? Could you try using mine for testing? You should have everything that's required (e.g., swagger.json). If you pass a Word file (.docx), you will get HTML back.

**Comment by wing328** [comment] 2015-07-03 10:40
Under samples/client/petstore/csharp/, there should be a project that contains unit testing for the C# client. One of the test cases is uploadFile for Petstore. Would you please run the test case to see if it reports any issue ?

**Comment by ThomasBarnekow** [comment] 2015-07-03 11:48
All tests pass. The only issue was that `c:\var\tmp\small.gif` originally did not exist on my machine. It would be better to include that with the solution.

I've tried both the original solution and also replaced the RestClient DLL with the one that I built (targeting 4.5.1). In both situations, all tests passed. Having had a look at the version number of the RestClient DLL, we should be talking about the exact same version, the only difference being that I have taken the one targeting 4.5.1 where the one that comes bundled targets 4.5.

**Comment by wing328** [comment] 2015-07-03 13:14
I did a test with the swagger spec you provided and it seems to work for me without the issue you encountered. Here is the result:
```
result=<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html><html xmlns="http://www.w3.org/1999/xhtml"><head><meta charset="UTF-8" />
<title></title>
<style>span { white-space: pre-wrap; }
p.ca-Normal {
    font-family: Droid Sans;
    font-size: 11pt;
    line-height: 108%;
    margin-top: 0;
    margin-left: 0;
    margin-right: 0;
    margin-bottom: .001pt;
}
span.ca-DefaultParagraphFont {
    font-family: Droid Sans;
    font-size: 11pt;
    font-style: normal;
    font-weight: normal;
    margin: 0;
    padding: 0;
}
body { max-width: 21cm; margin: 0 auto; padding: 2cm 1cm; }</style>
<meta name="generator" content="Contract Architect" />
</head>
<body><div><p dir="ltr" class="ca-Normal"><span lang="en-us" class="ca-DefaultParagraphFont">Example</span></p>
<p dir="ltr" class="ca-Normal"><span lang="en-us" class="ca-DefaultParagraphFont">Blah</span></p>
<p dir="ltr" class="ca-Normal"><span lang="en-us" class="ca-DefaultParagraphFont">Blah</span></p>
</div>
</body>
</html>


read: -p: no coprocess

[Process completed]
```
Here is the C# code I used to test:
```
using System;
using System.IO;
using IO.Swagger.Api;
using IO.Swagger.Client;

namespace thomas
{
	class MainClass
	{
		public static void Main (string[] args)
		{
			
			var apiClient = new ApiClient();
			var testApi = new TransformationApi(apiClient);

			const string relativePath = "/Users/williamcheng/Downloads/example.docx";
			string result = testApi.TransformationPostFormData(new FileStream(relativePath, FileMode.Open, FileAccess.Read), 
				"Exhibit 1", "Service Catalog", null, null, null, null, null, null, null);
			Console.WriteLine ("result=" + result);
		}
	}
}
```
Have you done a "mvn clean" to ensure the package has been recompiled with the latest change ?

**Comment by ThomasBarnekow** [comment] 2015-07-03 15:59
Yes, I have done a `mvn clean`. My process for generating the C# files is as follows:
```
$ git pull
$ mvn clean
$ mvn package
$ java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate -i swagger.json -l csharp -o csharp
```
Here's the latest revision I pulled as per `git log`:
```
commit 987a61640b8fe3f1ba093f93de18ffcda49bf1e4
Author: wing328 <wing328hk@gmail.com>
Date:   Fri Jul 3 17:39:27 2015 +0800

    fix file upload issue. add error handling for status code 0
```

But here it comes ... I replaced the Newtonsoft.Json DLL that I installed through NuGet with the one that is provided with the generated code. And, voila, now it works!

:-) :-) :-)

Thus, the RestClient was not the problem. However, you are shipping a pretty outdated release of the Newtonsoft.Json library. It's 5.0.5 from May 2013. The current version is 7.0.1 from June 2015.

Anyhow, I'd say we are now covering topics in this issue that are beyond supporting text/html output. Should we start a new thread as required?

**Comment by ThomasBarnekow** [comment] 2015-07-03 16:24
Just FYI, I've now tested it with the latest RestSharp (105.1.0) and Newtonsoft.Json (7.0.1) packages from NuGet. That now works as well.

**Comment by ThomasBarnekow** [comment] 2015-07-03 19:35
@wing328 Let's wait until your pull request is merged before we close this. Thanks a lot for your help!

**Comment by wing328** [comment] 2015-07-06 03:36
@ThomasBarnekow thanks for confirming the issue is fixed. I've updated the PR with the latest version of the JSON DLL and a README on obtaining the latest version of the dependencies via NuGet

**Comment by wing328** [comment] 2015-07-23 14:51
Merged into develop_2.0.

**Closed by wing328** 2015-07-23 14:51 UTC
Labels: Client: C-Sharp
