### ISSUE TITLE
Upgrade to version 3.0.0-rc1 not working because of exception

### ISSUE THREAD

**Issue by danielzimmermann** [swagger-api/swagger-codegen#8458] opened 2018-07-20 11:27 UTC
#8457 #### Description

I tried to upgrade the swagger-codegen-maven-plugin plugin from 2.3.1 to 3.0.0-rc1.

My Plugin config looks like this:
```
<plugin>
                <groupId>io.swagger</groupId>
                <artifactId>swagger-codegen-maven-plugin</artifactId>
                <version>${swagger-codegen-maven-plugin-version}</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <configOptions>
                                <dateLibrary>java8</dateLibrary>
                                <delegatePattern>true</delegatePattern>
                            </configOptions>
                            <apiPackage>at.openapi.facade.v1.server.api</apiPackage>
                            <generateApis>true</generateApis>
                            <generateApiDocumentation>false</generateApiDocumentation>
                            <generateApiTests>false</generateApiTests>
                            <generateModels>false</generateModels>
                            <generateModelDocumentation>false</generateModelDocumentation>
                            <generateModelTests>false</generateModelTests>
                            <generateSupportingFiles>false</generateSupportingFiles>
                            <inputSpec>${basedir}/../facade-yaml-v1/src/main/resources/facade-v1.yaml</inputSpec>
                            <language>spring</language>
                            <modelPackage>at.openapi.facade.v1.dto</modelPackage>
                            <library>spring-boot</library>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
```

But what i receive on doing clean install is the following:
```
[ERROR] 
java.lang.RuntimeException: Could not generate api file for 'facade'
    at io.swagger.codegen.DefaultGenerator.generateApis (DefaultGenerator.java:527)
    at io.swagger.codegen.DefaultGenerator.generate (DefaultGenerator.java:731)
    at io.swagger.codegen.plugin.CodeGenMojo.execute (CodeGenMojo.java:534)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:208)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:154)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:146)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:956)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:290)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:194)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
Caused by: com.github.jknack.handlebars.HandlebarsException: /v2/JavaSpring/api.mustache:100:54: java.lang.ClassCastException: java.util.HashMap cannot be cast to io.swagger.codegen.VendorExtendable
    /v2/JavaSpring/api.mustache:100:54

```

##### Swagger-codegen version
3.0.0-rc1

##### Swagger declaration file content or url

```yaml
swagger: '2.0'
info:
  description: >
    Some desc
  version: "1.0"
  title: API Facade
  contact:
    email: abc@abc.com
tags:
  - name: Facade
    description:  API facade
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /facade/subject/privacy/settings/update:
    parameters:
      - name: subject
        in: query
        description: Opaque subject identifier.
        type: string
        required: true
      - name: settings
        in: query
        description: "List of settings to update"
        type: array
        items:
          type: string
        required: true
      - name: timestamp
        in: query
        type: integer
        format: int64
        description: >-
          Milliseconds since 01.01.1970 to avoid HTTP caching since we are using
          HTTP GET for state changes. This timestamp can be also for request
          signing if the endpoint is public.
        required: true
      - name: source
        in: query
        type: string
        description: >-
          URL or the channel at which subject agreed/objected to data processing to
          be used for auditing
        required: true
      - name: action
        in: query
        type: string
        description: 'The signing action, e.g. clicking a button, used for auditing.'
        required: true
      - name: category
        in: query
        description: Filter on a category of privacy settings
        type: string
      - name: language
        in: query
        description: Language code to filter the localized text entries
        type: string
    get:
      tags:
        - Facade
      summary: Change privacy settings of a subject
      description: >-
        This is basically a hack to change permissions using a simple HTTP GET
        since this is the most simple way to integrate in any platform.
      operationId: updateSubjectPrivacySetting
      responses:
        '200':
          description: Successful operation - returned list of privacy items
          schema:
            $ref: '#/definitions/PrivacySettings'
        '400':
          $ref: '#/responses/InvalidInput'
        '401':
          $ref: '#/responses/Unauthorized'
        '403':
          $ref: '#/responses/WrongScope'
        '404':
          $ref: '#/responses/EntityNotFound'
responses:
  InvalidInput:
    description: Invalid input - sent entity failed to validate
  EntityNotFound:
    description: Entity with the given id can't be found
  OutdatedEntity:
    description: >-
      Entity has been updated before this operation. Fetch current version,
      apply changes and retry
  Unauthorized:
    description: >-
      Could not validate the authorization token(it's missing, malformed or
      invalid)
  WrongScope:
    description: Authorization token used to access the resource is different than required
definitions:
  Link:
    description: HATEOAS-style links to avoid building URLs
    type: object
    properties:
      href:
        description: The URL of the link.
        type: string
        minLength: 1
        maxLength: 2000
        example: >-
          /privacy/subject/settings/update?setting=EMAIL_NEWSLETTER_CONSENT&subject=user&value=false
      rel:
        description: 'The type of relation, e.g. [agree|disagree]'
        type: string
        minLength: 1
        maxLength: 32
        example: agree
      type:
        description: The HTTP method used to invoke the link.
        type: string
        minLength: 1
        maxLength: 8
        example: GET
    required:
      - href
      - rel
      - type
  LocalizedText:
    description: Represents localized body of an agreement presented to a subject.
    type: object
    properties:
      language:
        description: Code of the language used in content
        type: string
        pattern: '^[a-zA-Z]{2}(-[a-zA-Z]{2})?$'
        example: en
      content:
        description: >-
          Key-value store of attributes of the agreement definition. Data
          controllers can keep here all the data presented to the subject that
          constitute an agreement definition i.e. complete agreement text,
          questions, descriptions of processing purposes etc.
        type: object
        additionalProperties:
          type: string
          minLength: 1
          maxLength: 2000
        example:
          header: Newsletter
          overview: >-
            Would you like to receive updates on trends and new features by
            email?
    required:
      - language
      - content
  PrivacyPermissions:
    description: List of PrivacyPermission
    type: object
    properties:
      permissions:
        type: array
        items:
          $ref: '#/definitions/PrivacyPermission'
        minItems: 0
        uniqueItems: true
    required:
      - permissions
  PrivacyPermission:
    description: Details of the allowed processing actions for a particular subject
    type: object
    properties:
      purpose:
        type: string
        example: 'directMarketing'
      data:
        description: >-
          Categories of personal data which can be used for this purpose. This
          field will be present only if there are any limitations in data
          processing.
        type: array
        items:
          type: string
          minItems: 0
          uniqueItems: true
          example: 'location'
    required:
      - purpose
      - data
  PrivacySettings:
    description: List of PrivacySettings
    type: object
    properties:
      settings:
        type: array
        items:
          $ref: '#/definitions/PrivacySetting'
        minItems: 0
        uniqueItems: true
      links:
        description: HATEOAS-style links to change the value
        type: array
        items:
          $ref: '#/definitions/Link'
        minItems: 0
        uniqueItems: true
    required:
      - settings
      - links
  PrivacySetting:
    description: Captures the mimimum information of consent/objection for the given subject
    type: object
    properties:
      subject:
        description: Opaque subject identifier
        type: string
        minLength: 1
        maxLength: 254
        example: 'someExample'
      setting:
        description: Opaque identification of the underlying LBMP template
        type: string
        minLength: 1
        maxLength: 254
        example: EMAIL_NEWSLETTER_CONSENT
      value:
        description: Current value of the setting
        type: boolean
        default: true
      text:
        description: List of available translation of content this agreement.
        type: array
        items:
          $ref: '#/definitions/LocalizedText'
        minItems: 1
        uniqueItems: true
      links:
        description: HATEOAS-style links to change the value
        type: array
        items:
          $ref: '#/definitions/Link'
        minItems: 0
        uniqueItems: true
    required:
      - subject
      - setting
      - value
      - text
      - links
  UpdateSetting:
    description: Identification of setting and current value
    type: object
    properties:
      setting:
        description: Opaque identification of the underlying LBMP template or processing
        type: string
        minLength: 1
        maxLength: 254
        example: EMAIL_NEWSLETTER_CONSENT
      value:
        description: Current value of the setting
        type: boolean
        default: true
    required:
      - setting
      - value
```

##### Command line used for generation

mvn clean install

**Comment by lzkill** [comment] 2018-07-26 14:36
The issue doesn't happen on _swagger-codegen-cli-3.0.0-20180717.153005-90_.

**Comment by jledesma84** [comment] 2018-09-21 15:30
> 

> Hey @danielzimmermann that's an error with tamplte, i'm going to check if it was fixed for `3.0.0-SNAPSHOT` and let you know.

Hello. Using version 3.0.0-rc1 the problem also occurs. Do you know if there is a date for a release of version 3.0.1?

**Comment by HugoMario** [comment] 2018-09-21 15:33
hi @jledesma84 can you please try with https://github.com/swagger-api/swagger-codegen/releases and let me know if the issue is still present?

**Comment by jledesma84** [comment] 2018-09-21 16:28
It works! Thank you!

**Comment by HugoMario** [comment] 2018-09-21 16:44
great! let's close this one

**Closed by HugoMario** 2018-09-21 16:44 UTC
