### ISSUE TITLE
[Typescript-Angular] This member must have an 'override' modifier because it overrides a member in the base class 'HttpUrlEncodingCodec'.

### ISSUE THREAD

**Issue by idc77** [swagger-api/swagger-codegen#12068] opened 2023-02-19 13:01 UTC
##### Description

add `override` to `api/encoder.ts` functions

##### Swagger-codegen version

The one that's currently used in the swagger editor online

##### Swagger declaration file content or url

N/A

##### Command line used for generation

swagger editor generate client typescript angular

##### Steps to reproduce

generate an angular typescript client

##### Related issues/PRs

Not as far as I know

##### Suggest a fix/enhancement

Generated Code:
```ts
import { HttpUrlEncodingCodec } from '@angular/common/http';

/**
* CustomHttpUrlEncodingCodec
* Fix plus sign (+) not encoding, so sent as blank space
* See: https://github.com/angular/angular/issues/11058#issuecomment-247367318
*/
export class CustomHttpUrlEncodingCodec extends HttpUrlEncodingCodec {
    encodeKey(k: string): string {
        k = super.encodeKey(k);
        return k.replace(/\+/gi, '%2B');
    }
    encodeValue(v: string): string {
        v = super.encodeValue(v);
        return v.replace(/\+/gi, '%2B');
    }
}
```

fix
```ts
import { HttpUrlEncodingCodec } from '@angular/common/http';

/**
* CustomHttpUrlEncodingCodec
* Fix plus sign (+) not encoding, so sent as blank space
* See: https://github.com/angular/angular/issues/11058#issuecomment-247367318
*/
export class CustomHttpUrlEncodingCodec extends HttpUrlEncodingCodec {
    override encodeKey(k: string): string {
        k = super.encodeKey(k);
        return k.replace(/\+/gi, '%2B');
    }
    override encodeValue(v: string): string {
        v = super.encodeValue(v);
        return v.replace(/\+/gi, '%2B');
    }
}
```

**Comment by fvilers** [comment] 2023-08-26 07:35
Duplicate of #11852

**Closed** 2023-10-05 00:37 UTC

**Comment by HugoMario** [comment] 2023-11-10 11:10
the override keyword can be set using:
```
--additional-properties useOverride=true
```
This will be available for next release
