### ISSUE TITLE
DockerHub image swaggerapi/swagger-generator-v3 not working

### ISSUE THREAD

**Issue by tsproesser** [swagger-api/swagger-codegen#10141] opened 2020-03-29 17:57 UTC
None of the DockerHub-images is working for me. All start up a service responding with a 404 error. Neither does the Dockerfile build correctly.

**Comment by tsproesser** [comment] 2020-03-30 07:38
The file /generator/webapps/ROOT.xml looks broken. One path starts with a "," and the reference paths do not exists. Changing them brings me to a 503 error. Something with this image seams completely wrong.

**Comment by frantuma** [comment] 2020-03-30 13:00
duplicate of #10140, please see #10140

**Closed by frantuma** 2020-03-30 13:00 UTC
