### ISSUE TITLE
[Kotlin] using allOf with reference end in field duplication

### ISSUE THREAD

**Issue by huehnerlady** [swagger-api/swagger-codegen#9791] opened 2019-10-17 12:54 UTC
##### Description

I am generating kotlin data classes from a swagger.json file.
among others there are enums to generate.

Unfortunately java and kotlin-client languages seem to duffer using the same `enumPropertyNaming="UPPERCASE"`

##### Swagger-codegen version

`io.swagger.codegen.v3:swagger-codegen-cli:3.0.13`

##### Swagger declaration file content or url

My swagger sample file:
```json
{
	"swagger": "2.0",
	"schemes": [
		"http"
	],
	"definitions": {
		"SomeModel": {
			"type": "object",
			"required": [
				"b"
			],
			"properties": {
				"a": {
					"type": "string",
					"description": "a"
				},
				"b": {
					"type": "string",
					"description": "The enum"
				}
			}
		},
		"SomeSecondModel": {
			"allOf": [
				{
					"$ref": "#/definitions/SomeModel"
				},
				{
					"type": "object",
					"required": ["c"],
					"properties": {
						"c": {
							"type": "string",
							"minLength": 2,
							"maxLength": 2,
							"description": "c"
						}
					}
				}
			]
		}
	}
}
```
my config file:

```json
{
  "modelPackage": "my.package",
  "packageName": "my.package",
  "dateLibrary": "joda",
  "interfaceOnly": false,
  "enumPropertyNaming": "UPPERCASE"
}

```

##### Command line used for generation

I used the [gradle swagger codegen plugin](https://github.com/int128/gradle-swagger-generator-plugin)

##### Steps to reproduce

when using `java` you get a class extending the other class:
```

public class SomeSecondModel extends SomeModel { //<----

  private String c = null;

  public SomeSecondModel c(String c) {
    this.c = c;
    return this;
  }

   /**
   * c
   * @return c
  **/
  @Schema(required = true, description = "c")
  public String getC() {
    return c;
  }

  public void setC(String c) {
    this.c = c;
  }
}

```

When you use `kotlin-client` you get:

```
/**
 * 
 * @param c c
 */
data class SomeSecondModel (
    /* c */
    val c: kotlin.String, //<-----
    /* The enum */
    val b: kotlin.String,
    /* c */
    val c: kotlin.String //<-----
,
    /* a */
    val a: kotlin.String? = null
) {
}
```

##### Suggest a fix/enhancement

I would expect the property not to be duplicated, unfortunately I do not know where that comes from.

Is there maybe a known workaround for this? E.g. use a different version of the codegen-cli?

Many thanks

**Comment by cristiadu** [comment] 2019-12-06 02:07
This is also happening for me on the java swagger-codegen 2.4.10 using maven

**Comment by Gama11** [comment] 2020-06-12 14:41
This seems to be a duplicate of #9265.

**Closed** 2024-09-19 09:23 UTC
