### ISSUE TITLE
[typescript-angular] upgrade to support angular v6 (breaking changes due to rxjs v6)

### ISSUE THREAD

**Issue by crhistianramirez** [swagger-api/swagger-codegen#8179] opened 2018-05-12 15:59 UTC
##### Description

Angular v6 just released which has a dependency on rxjs v6. Specifically, imports for Observables have changed: https://github.com/ReactiveX/rxjs/blob/master/MIGRATION.md

It looks like we'll need to update:
```import { Observable } from 'rxjs/Observable';```

to:

```import { Observable } from 'rxjs'```

##### Suggest a fix/enhancement

I propose we add an additional property `useRxjsVersion6Imports` that is `true` if `ngVersion` is greater than 6.0.0 to determine which import to display. I'd also be willing to take a shot at this if approved.

**Comment by macjohnny** [comment] 2018-05-14 05:40
this has already been implemented by @akehir in https://github.com/swagger-api/swagger-codegen/pull/8155, so this issue can be closed.

**Comment by pegaltier** [comment] 2018-06-12 08:59
The issue is always present when i use typescript-angular api : https://generator.swagger.io/api/gen/clients/typescript-angular

**Comment by macjohnny** [comment] 2018-06-12 09:02
@pegaltier this is because generator.swagger.io uses version 2.3.1, and the fix is in the current master branch. however, there is a current release of OpenAPI Generator that fully supports rxjs v6. see [https://github.com/openapitools/openapi-generator](https://github.com/openapitools/openapi-generator)

**Comment by akehir** [comment] 2018-06-12 10:02
@pegaltier  if you need to use swagger-generator, you can use the following 2 mustache files from swagger master, if you just override the default mustache files with these 2:
https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/typescript-angular/api.service.mustache
https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/typescript-angular/apiInterface.mustache

For example in your pom:
```xml
<groupId>io.swagger</groupId>
                <artifactId>swagger-codegen-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <id>swagger-wallet-api-codegen</id>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <inputSpec>${project.build.directory}/swagger/wallet/meta/swagger.json</inputSpec>
                            <language>typescript-angular</language>
                            <output>src/generated/wallet-api</output>
                            <templateDirectory>../_mustache</templateDirectory>
                            <configOptions>
                                <ngVersion>6.0</ngVersion>

                            </configOptions>
                        </configuration>
                    </execution>
```

**Comment by fizxmike** [comment] 2018-06-28 17:13
SNAPSHOT builds of master do not work for me due to at least [one open issue and unmerged PR](https://github.com/swagger-api/swagger-codegen/issues/7586). So, is the answer "use openapi-generator instead"?

**Comment by Sef1995** [comment] 2018-07-04 21:55
@fizxmike Could you explain a little bit more on how you got the generator working so it can be used with angular 6?

**Comment by fizxmike** [comment] 2018-07-05 00:21
The main issue is that with the current "release" of swagger-codegen (v2.3.1), the typescript-angular client for version 6 uses the wrong version of rxjs, so build of client will fail. The "workaround" is to install the right version of rxjs (version 6) **AND** rxjs-compat (version 6). So do this in client folder (after codegen):
```bash
npm install
npm install rxjs@6 rxjs-compat@6
npm build
```

Of course, when you codegen, use the `"ngVersion":"6"` option in your config.json
```json
{
    "npmName":"my-swagger-package",
    "npmVersion":"0.0.1",
    "ngVersion":"6"
}
```

### Summary
```bash
java -jar swagger-codegen-cli-2.3.1.jar -l typescript-angular -c config.json -i swagger.yml -o angular6clinet
cd angular6client
npm install
npm install rxjs@6 rxjs-compat@6
npm build
```

To make the fix "stick" add this line to your angular6clinet/.swagger-codegen-ignore file:
```bash
# keep package.json frozen since it has fix (https://github.com/swagger-api/swagger-codegen/issues/8179#issuecomment-401208765)
package.json
```
This way you can update your swagger.yml and rebuild the client without clobbering the fix.

**Closed** 2018-07-16 17:49 UTC
