### ISSUE TITLE
[Go] [Bug] QueryParam struct field names must be exported (UpperCamelCase)

### ISSUE THREAD

**Issue by neilotoole** [swagger-api/swagger-codegen#2564] opened 2016-04-11 19:25 UTC
Currently, the Go generator can produce code like this:

````go
    _sling = _sling.Path(path)

    type QueryParams struct {
        userId    int32 `url:"user_id,omitempty"`  
}
    _sling = _sling.QueryStruct(&QueryParams{ userId: userId })
````

Note that `userId` is not exported (first letter is lowercase). Therefore sling doesn't see the `userId` value, and doesn't send it in the request.

**Comment by wing328** [comment] 2016-04-14 17:10
PR merged. Issue closed.

**Comment by nnathan** [comment] 2016-07-21 01:27
I fetched latest master and found the commit 2f3897f but the changes aren't reflecting. I sense a later merge commit undid the change?

**Comment by wing328** [comment] 2016-07-21 03:44
@nnathan did you do a `mvn clean package` to build the JAR using the latest master?

**Comment by nnathan** [comment] 2016-07-21 03:55
Yep. I did a fresh clone and ran `mvn clean package`.

```
$ git rev-parse HEAD
c888434580c601ac9c4734e19d8eefac63518031
$ grep "vendorExtensions.x-exportParamName" modules/swagger-codegen/src/main/resources/go/api.mustache
$ echo $?
1
```

From the above, you can see at HEAD the corresponding changes from commit 2f3897f aren't merged.  Specifically this: https://github.com/swagger-api/swagger-codegen/commit/2f3897f6d5b5df557bf2de526081cb1edcb0d8c2#diff-293df8239a8ee15d445676a48a96a143R87

**Comment by wing328** [comment] 2016-07-21 03:59
You're right. Looks like the fix has been removed accidentally. I'll take a deeper look later today.

cc @neilotoole @guohuang

**Comment by guohuang** [comment] 2016-07-21 18:56
@wing328 I don't think we need this commit anymore, as we have already switched to use resty instead of sling, let me know if you still think it is an issue.

**Comment by wing328** [comment] 2016-07-22 02:32
@guohuang thanks for looking into the issue.

@nnathan what issue did you get when using the latest Go API client? can you show us the code/error to illustrate the issue more?

**Comment by nnathan** [comment] 2016-07-22 07:18
Our API uses GET query parameters but the generated API (due to the bug mentioned in this ticket) ignores them since the fields in the QueryParams struct are not visible (exported).

**Comment by wing328** [comment] 2016-07-22 07:40
Can you confirm you are using 2.2.0 or the latest master to generate the Go
API client?

**Comment by wing328** [comment] 2016-07-22 08:41
I greped the latest Go Petstore API client and confirmedthe `QueryParams` struct has been removed:
```
$ grep -R QueryParams samples/client/petstore/go/*       
samples/client/petstore/go/go-petstore/api_client.go:		request.SetMultiValueQueryParams(queryParams)
```

**Comment by wing328** [comment] 2016-07-22 08:42
Please do a `mvn clean package` to ensure you're creating the JAR based on the latest source code if you're building it from the latest master.

**Closed** 2016-08-08 09:38 UTC
Labels: Client: Go, Issue: Bug
