### ISSUE TITLE
Spring Generator imports wrong class if configPackage set

### ISSUE THREAD

**Issue by dlabordus** [swagger-api/swagger-codegen#12488] opened 2024-11-05 14:30 UTC
##### Description

We are using de Spring Generator to generate classes from a OpenApi.yaml file.
A new additional property "validationMode" was added recently with default value "strict".
This cause the statement "import io.swagger.configuration.NotUndefined;" to be added in the model classes.
But when the plugin is configured with config option "configPackage" this class is generated in that package.
Causing the model class to fail to compile, because class "io.swagger.configuration.NotUndefined" can't be found.

##### Swagger-codegen version

3.0.63

##### Steps to reproduce

Add the Maven Plugin to generate the classes.

            <plugin>
                <groupId>io.swagger.codegen.v3</groupId>
                <artifactId>swagger-codegen-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <id>api</id>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <inputSpec>${project.basedir}/src/main/api/openapi.yml</inputSpec>
                            <language>spring</language>
                            .....
                            <configOptions>
                                <configPackage>com.somepackage.configuration</configPackage>
                                ....
                            </configOptions>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

##### Suggest a fix/enhancement

Our workaround for now is using the legacy validation mode.

                            <additionalProperties>
                                <additionalProperty>validationMode=legacy</additionalProperty>
                            </additionalProperties>

**Comment by frantuma** [comment] 2024-11-06 08:17
Duplicate of https://github.com/swagger-api/swagger-codegen-generators/issues/1319

This has been fixed in https://github.com/swagger-api/swagger-codegen-generators/pull/1322 and https://github.com/swagger-api/swagger-codegen/pull/12487, available in latest 3.0.64-SNAPSHOT (release will follow in 1-2 days).

Closing ticket, please reopen if you're still experiencing issues

**Closed by frantuma** 2024-11-06 08:17 UTC
