### ISSUE TITLE
[swift] crashes if server returns invalid response

### ISSUE THREAD

**Issue by romk1n** [swagger-api/swagger-codegen#2379] opened 2016-03-15 02:44 UTC
Could not cast value of type 'NSNull' (0x111232378) to 'NSDictionary' (0x111231d60).

``` let sourceDictionary = source as! [NSObject:AnyObject]```

**Comment by fehguy** [comment] 2016-03-15 03:19
Can you please give a test case or way to reproduce?  Invalid meaning invalid payload?  Or unexpected return code?

**Comment by romk1n** [comment] 2016-03-15 03:44
sure. i.e.

```response code: 204```
```
{
  "date": "Tue, 15 Mar 2016 02:37:55 GMT",
  "x-powered-by": "Servlet/3.1 JSP/2.3 (GlassFish Server Open Source Edition  4.1.1  Java/Oracle Corporation/1.8)",
  "connection": "keep-alive",
  "access-control-allow-methods": "GET, POST, DELETE, PUT",
  "access-control-allow-headers": "Content-Type, accept-language, user-agent",
  "access-control-allow-origin": "*",
  "content-type": null
}```

**Comment by wing328** [comment] 2016-06-07 10:59
@romk1n I wonder if you can pull the latest master and give it another try as there are 20+ PRs (improvements, bug fixes) to Swift API client since Mar 15.

**Comment by wing328** [comment] 2016-06-20 08:17
@romk1n closing this as there's no update from you.

**Closed by wing328** 2016-06-20 08:17 UTC
Labels: Bug, Client: Swift
