### ISSUE TITLE
webpack error building javascript generated client

### ISSUE THREAD

**Issue by saharj** [swagger-api/swagger-codegen#3537] opened 2016-08-05 15:11 UTC
_From @zsimo on August 3, 2016 16:17_

**Swagger File**

``` json
 {
  "swagger": "2.0",
  "info": {
    "title": "Test",
    "description": "Test",
    "version": "1.0.0"
  },
  "host": "localhost",
  "schemes": [
    "http"
  ],
  "basePath": "/services/search",
  "paths": {
    "/institutions": {
      "post": {
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "value",
            "in": "query",
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Records found",
            "schema": {
              "$ref": "#/definitions/QuickSearchRecords"
            }
          },
          "400": {
            "description": "Invalid parameters"
          },
          "404": {
            "description": "No record found"
          },
          "500": {
            "description": "Unexpected error"
          }
        }
      }
    }
  },


  "definitions": {
    "QuickSearchRecords": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/QuickSearchRecord"
      }
    },
    "QuickSearchRecord": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "label": {
          "type": "string"
        },
        "count": {
          "type": "integer"
        }
      }
    }

  }
}
```
- Version: 
- Browser/OS: 

**Issue**
Hello!
It seems Webpack (I'm using 1.13.1) fail to manage AMD syntax: by changing the source code, forcing to use CommonJs syntax Webpack succeeds in compiling the scripts. Can you please try/fix?

Thanks!

_Copied from original issue: swagger-api/swagger-editor#1035_

**Comment by saharj** [comment] 2016-08-05 15:11
Can you provide more details? Are you trying to modify Swagger Editor code base?

**Comment by saharj** [comment] 2016-08-05 15:11
_From @zsimo on August 4, 2016 9:39_

Hello,

No, I just try to edit the client source code generated by the Swagger Editor.
It seems Webpack (I'm using 1.13.1) fail to manage AMD syntax: by disabling the Module system the Javascript client works.
Disabling directly edit the code source :
```
// commenting the first IF branch
  //if (typeof define === 'function' && define.amd) {
  //  // AMD. Register as an anonymous module.
  //  define(['superagent'], factory);
  //} else
  if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('superagent'));
  }
```

or via Webpack configs:
```
npm install --save-dev imports-loader
// and then add this loader to the webpack configs
{ test: /\.js/, loader: 'imports?define=>false'}
```

Have you ever try to bundle your Js client generated code via Webpack?

Thanks!

**Comment by saharj** [comment] 2016-08-05 15:11
This is a Codegene issue. let me move your issue there.

**Comment by hasangilak** [comment] 2016-12-12 13:47
i wrote a template for webpack build. may help
https://github.com/hasangilak/webpack-swagger-template

**Comment by wing328** [comment] 2017-02-16 16:38
@hasangilak thanks for sharing the link. Is that something we can add back to the JS generator? I'm sure the JS developers would welcome the enhancements.

**Comment by frol** [comment] 2017-03-04 20:44
It seems to be a duplicate of #3466.

**Comment by akeemphilbert** [comment] 2017-03-04 21:11
I think you're right but I can't seem to do what was advised

**Comment by wing328** [comment] 2017-03-06 07:59
Closed via https://github.com/swagger-api/swagger-codegen/issues/3466#issuecomment-284187483

**Closed by wing328** 2017-03-06 07:59 UTC
Labels: Client: Javascript/Node.js, Issue: Bug, Need community contribution
