### ISSUE TITLE
[java] codegen fails on JDK 16. Need a way to pass --add-opens option

### ISSUE THREAD

**Issue by jcd006** [swagger-api/swagger-codegen#11014] opened 2021-05-17 18:35 UTC
##### Description
I have an open-api v3 based YAML API definition. When compiling with JDK 16 the codegen maven plugin fails with an error 

```
Caused by: com.github.jknack.handlebars.HandlebarsException: /handlebars/JavaSpring/pojo.mustache:2:6: java.lang.reflect.InaccessibleObjectException: Unable to make public boolean java.util.Collections$EmptyMap.isEmpty() accessible: module java.base does not "opens java.util" to unnamed module @7b6419dd
    /handlebars/JavaSpring/pojo.mustache:2:6
    at java.lang.reflect.AccessibleObject.checkCanSetAccessible (AccessibleObject.java:357)
    at java.lang.reflect.AccessibleObject.checkCanSetAccessible (AccessibleObject.java:297)
    at java.lang.reflect.Method.checkCanSetAccessible (Method.java:199)
    at java.lang.reflect.Method.setAccessible (Method.java:193)
    at com.github.jknack.handlebars.context.MemberValueResolver.cache (MemberValueResolver.java:82)
    at com.github.jknack.handlebars.context.MemberValueResolver.resolve (MemberValueResolver.java:54)
    at com.github.jknack.handlebars.Context$CompositeValueResolver.resolve (Context.java:199)
    at com.github.jknack.handlebars.internal.path.PropertyPath.eval (PropertyPath.java:52)
    at com.github.jknack.handlebars.Context$PathExpressionChain.next (Context.java:361)
    at com.github.jknack.handlebars.Context$PathExpressionChain.eval (Context.java:381)
    at com.github.jknack.handlebars.Context.get (Context.java:621)
    at com.github.jknack.handlebars.Context$PartialCtx.get (Context.java:165)
    at com.github.jknack.handlebars.internal.Block.merge (Block.java:176)
    at com.github.jknack.handlebars.internal.BaseTemplate.apply (BaseTemplate.java:130)
    at com.github.jknack.handlebars.internal.TemplateList.merge (TemplateList.java:95)
    at com.github.jknack.handlebars.internal.BaseTemplate.apply (BaseTemplate.java:130)
    at com.github.jknack.handlebars.internal.ForwardingTemplate.apply (ForwardingTemplate.java:86)
    at com.github.jknack.handlebars.internal.Partial.merge (Partial.java:228)
    at com.github.jknack.handlebars.internal.BaseTemplate.apply (BaseTemplate.java:130)
    at com.github.jknack.handlebars.internal.TemplateList.merge (TemplateList.java:95)
    at com.github.jknack.handlebars.internal.BaseTemplate.apply (BaseTemplate.java:130)
    at com.github.jknack.handlebars.internal.BaseTemplate.apply (BaseTemplate.java:118)
    at com.github.jknack.handlebars.Options.apply (Options.java:538)
    at com.github.jknack.handlebars.Options.fn (Options.java:433)
    at com.github.jknack.handlebars.helper.UnlessHelper.apply (UnlessHelper.java:50)
    at com.github.jknack.handlebars.internal.Block.merge (Block.java:211)
    at com.github.jknack.handlebars.internal.BaseTemplate.apply (BaseTemplate.java:130)
    at com.github.jknack.handlebars.internal.TemplateList.merge (TemplateList.java:95)
    at com.github.jknack.handlebars.internal.BaseTemplate.apply (BaseTemplate.java:130)
    at com.github.jknack.handlebars.internal.BaseTemplate.apply (BaseTemplate.java:118)
    at com.github.jknack.handlebars.Options.apply (Options.java:538)
    at com.github.jknack.handlebars.Options.fn (Options.java:433)
    at com.github.jknack.handlebars.helper.UnlessHelper.apply (UnlessHelper.java:50)
    at com.github.jknack.handlebars.internal.Block.merge (Block.java:211)
    at com.github.jknack.handlebars.internal.BaseTemplate.apply (BaseTemplate.java:130)
    at com.github.jknack.handlebars.internal.TemplateList.merge (TemplateList.java:95)
    at com.github.jknack.handlebars.internal.BaseTemplate.apply (BaseTemplate.java:130)
    at com.github.jknack.handlebars.internal.BaseTemplate.apply (BaseTemplate.java:118)
    at com.github.jknack.handlebars.Options.apply (Options.java:538)
    at com.github.jknack.handlebars.Options.fn (Options.java:445)
    at com.github.jknack.handlebars.helper.WithHelper.apply (WithHelper.java:58)
    at com.github.jknack.handlebars.internal.Block.merge (Block.java:211)
    at com.github.jknack.handlebars.internal.BaseTemplate.apply (BaseTemplate.java:130)
    at com.github.jknack.handlebars.internal.TemplateList.merge (TemplateList.java:95)
    at com.github.jknack.handlebars.internal.BaseTemplate.apply (BaseTemplate.java:130)
    at com.github.jknack.handlebars.internal.BaseTemplate.apply (BaseTemplate.java:118)
    at com.github.jknack.handlebars.Options.apply (Options.java:538)
    at com.github.jknack.handlebars.helper.EachHelper.apply (EachHelper.java:73)
    at com.github.jknack.handlebars.internal.Block.merge (Block.java:211)
    at com.github.jknack.handlebars.internal.BaseTemplate.apply (BaseTemplate.java:130)
    at com.github.jknack.handlebars.internal.TemplateList.merge (TemplateList.java:95)
    at com.github.jknack.handlebars.internal.BaseTemplate.apply (BaseTemplate.java:130)
    at com.github.jknack.handlebars.internal.BaseTemplate.apply (BaseTemplate.java:118)
    at com.github.jknack.handlebars.internal.ForwardingTemplate.apply (ForwardingTemplate.java:72)
    at io.swagger.codegen.v3.templates.HandlebarTemplateEngine.getRendered (HandlebarTemplateEngine.java:26)
    at io.swagger.codegen.v3.DefaultGenerator.processTemplateToFile (DefaultGenerator.java:795)
    at io.swagger.codegen.v3.DefaultGenerator.generateModels (DefaultGenerator.java:438)
    at io.swagger.codegen.v3.DefaultGenerator.generate (DefaultGenerator.java:779)
    at io.swagger.codegen.v3.maven.plugin.CodeGenMojo.execute_ (CodeGenMojo.java:554)
    at io.swagger.codegen.v3.maven.plugin.CodeGenMojo.execute (CodeGenMojo.java:319)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:78)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:567)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
```

**Plugin configuration:**

`<plugin>
        <groupId>io.swagger.codegen.v3</groupId>
        <artifactId>swagger-codegen-maven-plugin</artifactId>
        <version>${io.swagger.codegen.v3.version}</version>
        <executions>
          <execution>
            <goals>
              <goal>generate</goal>
            </goals>
            <configuration>
              <inputSpec>${project.basedir}/src/main/resources/api.yaml</inputSpec>
              <language>spring</language>
              <output>${project.build.directory}/generated-sources/</output>
              <generateSupportingFiles>false</generateSupportingFiles>
              <apiPackage>com.server.rest.controllers</apiPackage>
              <modelPackage>com.api</modelPackage>
              <configOptions>
                <delegatePattern>true</delegatePattern>
                <serializableModel>true</serializableModel>
                <useTags>true</useTags>
              </configOptions>
            </configuration>
          </execution>
        </executions>
      </plugin>`

##### Swagger-codegen version
3.0.25

##### Command line used for generation

Generated using the maven plugin.

##### Steps to reproduce

Run codegen on open-api 3 based API definition on a system with JDK 16

##### Suggest a fix/enhancement

Provide a way to pass the `--add-opens` option in the plugin configuration that can be used to export the required packages to the plugin.

**Comment by pumpkinlink** [comment] 2021-07-30 18:18
this bug is making me stuck on jdk 15, are there any workarounds?

**Comment by fistons** [comment] 2021-08-05 08:50
Same here, I'm stuck with Java 11

**Comment by denis-yuen** [comment] 2021-09-14 16:00
Still an issue with 3.0.27

**Comment by chrlembeck** [comment] 2021-10-04 12:04
There is a related issue in the jknack project which was resolved some days ago.
Maybe the issue can be resolved by upgrading to the new version:
[https://github.com/jknack/handlebars.java/issues/667](https://github.com/jknack/handlebars.java/issues/667)

**Comment by frantuma** [comment] 2021-10-05 14:45
Duplicate of #10966

latest `handlebars` 4.2.1 version doesn't fix the issue, however this can be solved by one of the options detailed in https://github.com/swagger-api/swagger-codegen/issues/10966#issuecomment-934455905

**Closed by frantuma** 2021-10-05 14:45 UTC

**Comment by chrlembeck** [comment] 2021-10-05 15:02
The jknack fix is not contained in version 4.2.1.
It will be integrated into 4.3.0. See: https://github.com/jknack/handlebars.java/pull/893

**Comment by Birthright50** [comment] 2021-11-30 15:05
> @chrlembeck thanks! We'll track handlebars releases in #10966

Why was this fix not included in the latest release?

**Comment by origicom** [comment] 2021-12-13 03:57
Some please update handlebars version to latest to fix this issue
