### ISSUE TITLE
Array of string values as query parameter is not generated in jersey2 server side code

### ISSUE THREAD

**Issue by shailendrajain24** [swagger-api/swagger-codegen#4148] opened 2016-11-07 06:54 UTC
Please suggest how to pass List into GET type method.

```
paths:
'/test':
get:
   parameters:
      - name: test1
          in: query
          description: 'This field can contain List of test item.'
          required: true
          schema:
            type: array
            items:
              type: string
          collectionFormat: "multi"
```

```
Output:
@ApiParam(value = "This field can contain List of test item.",required=true) @QueryParam("test1") 
  @NotNull String test1

```

But we want List<String> instead of String like this:
```
@ApiParam(value = "This field can contain List of test item.",required=true) @QueryParam("test1") 
  @NotNull List<String> test1
```

**Comment by wing328** [comment] 2016-11-24 04:03
Which version of Swagger Codegen are you using? can you pull the latest master to build the local JAR to see if the issue is still there?

**Comment by wing328** [comment] 2017-02-17 15:03
Closing this as there's no update.

**Closed by wing328** 2017-02-17 15:03 UTC
Labels: Issue: Bug, Server: Java
