### ISSUE TITLE
Problem with allOf in Node.js codegen

### ISSUE THREAD

**Issue by mohsen1** [swagger-api/swagger-codegen#796] opened 2015-05-26 23:23 UTC
This Swagger gives me an error when I try it with online Node.js codegen

```yaml
---
swagger: '2.0'
info:
  version: 0.0.0
  title: Simple API
paths:
  /:
    get:
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/I1'
definitions:
  Base:
    properties:
      f1:
        type: string
      f2:
        type: integer
        format: int32
    required:
    - f1
  I1:
    type: object
    allOf:
      - $ref: '#/definitions/Base'
      - properties:
          f3:
            type: string
```

If I remove the `allOf` key from `I1` it works.

Error message:

```
Unable to build target: A target generation was attempted, but no files were created!
Code: 1
```

**Comment by webron** [comment] 2015-05-26 23:25
Duplicate of #358.

**Closed by webron** 2015-05-26 23:25 UTC
