### ISSUE TITLE
[typescript-angular2] Model import bug

### ISSUE THREAD

**Issue by sebastianhaas** [swagger-api/swagger-codegen#3969] opened 2016-10-12 10:13 UTC
##### Description

Since the change introducing the `.model` prefix, the Typescript Angular 2 codegen is not working correctly anymore, as models get marked for import twice. One time as `Model` and another time as `model.Model`.

The issue is currently masked since the generator doesn't use single imports but barrel imports (e.g. `import * from ./`). I would love to contribute a PR that updates the codegen to the requirements for the final Angular 2 release, but this is a blocking issue for me since I need to be able to import the required models only.
##### Swagger-codegen version

Latest master, https://github.com/swagger-api/swagger-codegen/commit/a76d69513c03baf5675d3ae8826315fcafa07ccc
##### Swagger declaration file content or url

Petstore sample 
##### Steps to reproduce

Run the following commands:

```
export JAVA_OPTS=-DdebugOperations=true
bin/typescript-angular2-petstore.sh | grep imports
```

See the line where `Order` gets imported improperly:

```
"imports" : [ "Order", "models.Order" ],
```
##### Related issues

Probably related to #3616.
##### Suggest a Fix

I tried to dig into this problem, but I'm lacking a proper debugging environment atm so I can't really tell. The problem originates somewhere in 

``` java
public CodegenParameter fromParameter(Parameter param, Set<String> imports)
```

probably around line 2370. Maybe @Vrolijkx knows more?

**Comment by Vrolijkx** [comment] 2016-11-07 09:37
Sorry for the late response. I am currently also having trouble with this. I think the problem is that we have taken a shortcut when importing models/api's instead of doing imports correctly. 
Instead of doing something like this:
```
import * as models from './models';

export interface Pet {
    id?: number;

    category?: models.Category;

    tags?: Array<models.Tag>;

}
```

we should do do it in the following way:
```
import {Category, Tag} from './models';

export interface Pet {
    id?: number;

    category?: Category;

    tags?: Array<Tag>;

}
```

This makes the generated code much cleaner and will probably solve your problem.

**Comment by sebastianhaas** [comment] 2016-11-07 12:05
@Vrolijkx I already did that, in preparation for the Angular 2 module system. (https://github.com/sebastianhaas/swagger-codegen/commit/262a110902154c6559b9a8762c676b9125801d96)

Everything is set up and works as expected, however, the issue regarding the model prefix arises somewhere in the `DefaultCodegen`/`Generator` so I feel like there is nothing I can do about in the Typescript area of swagger.

It would be really nice to resolve this, it's the only thing that blocks my PR for the Angular 2 final including the module structure.

**Comment by sebastianhaas** [comment] 2016-11-07 12:08
In addition to your example above: The generated code would then become
```typescript
import {Model.Category, Model.Tag} from './models';
import {Category, Tag} from './models';

export interface Pet {
    id?: number;

    category?: Category;

    tags?: Array<Tag>;

}
```
I'm running
```shell
# Remove double imports from services
for i in src/app/api/api/*; do
    sed -i '' 's/^import { Models.*$//' "$i";
done
```
now after every generation to fix this.

**Comment by Vrolijkx** [comment] 2016-11-08 08:54
I will take a look today.

**Comment by Vrolijkx** [comment] 2016-11-08 12:06
@sebastianhaas I checked out your branch and can't seem to reproduce the import problem you described above. I am however having some other problems.
- In the ```Pet``` model the ```Category``` import is missing but the ```Tag``` import is correctly present.
- I get an unwanted import of ```import { Map } from '../model/map';``` in store.service.ts

**Comment by Vrolijkx** [comment] 2016-11-08 15:01
@sebastianhaas fixed the issues i experienced [in this branch](https://github.com/Vrolijkx/swagger-codegen/tree/feature/fix-invalid-import-ng-module) If you still see problems with the ```Models``` prefix can you maybe create an test/intgerationtest confirming them so i can take another look.

**Comment by wing328** [comment] 2017-02-17 06:32
Fixed via https://github.com/swagger-api/swagger-codegen/pull/4223 in 2.3.0

**Closed by wing328** 2017-02-17 06:32 UTC
Labels: Client: TypeScript
