### ISSUE TITLE
Generate Server > Spring MVC only generates the Model object

### ISSUE THREAD

**Issue by mohsen1** [swagger-api/swagger-codegen#903] opened 2015-06-23 03:55 UTC
Moved from https://github.com/swagger-api/swagger-editor/issues/511

Generating a Spring MVC server only generates the model objects. 
Last week it generated a lot more for me. 
The controllers, api and other plumbing code is not there anymore.

Here is my swagger.yaml: 

````yaml
swagger: '2.0'
info:
  title: Rakuten Card Linked Offer API
  description: Give your customers the ability to link their credit cards to offers using the RCLON API
  version: '1.0.0'
  contact: 
    name: RCLON Affiliate Account Admin
    email: rclon-admin@ebates.com
host: api.rclon.com
schemes:
  - https
basePath: /v1
produces:
  - application/json
consumes:
  - application/json
paths:
  /merchants:
    post:
      tags:
        - Merchants
      summary: Add a new merchant to the network
      description: ""
      operationId: addMerchant
      parameters:
        - in: body
          name: body
          description: Merchant object that needs to be added to the network
          required: true
          schema:
            $ref: "#/definitions/Merchant"
      responses:
        "200":
          description: Merchant added successfully
        "405":
          description: Invalid input
    get: 
      parameters:
        - name: merchantId
          in: query
          type: string
          description: Filter by Merchant ID
        - name: merchantName
          in: query
          type: string
          description: Filter by Enterprise Name
        - name: enterpriseName
          in: query
          type: string
          description: Filter by Enterprise Name
        - name: visaMerchantEnterpriseId
          in: query
          type: string
          description: Filter by VISA Merchant Enterprise ID
        - name: aquirerBin
          in: query
          type: string
          description: Filter by Aquirer BIN
        - name: acquirerMerchantId
          in: query
          type: string
          description: Filter by Aquirer Merchant ID
        - name: cardAcceptorId
          in: query
          type: string
          description: Filter by Card Acceptor ID
        - name: visaCommunityCode
          in: query
          type: string
          description: Filter by Visa Community Code
        - name: city
          in: query
          type: string
          description: Filter by Merchant Address City
        - name: state
          in: query
          type: string
          description: Filter by Merchant Address State
        - name: postalCode
          in: query
          type: string
          description: Filter by Merchant Address Postal Code
        - name: country
          in: query
          type: string
          description: Filter by Merchant Address Country
        - $ref: "#/parameters/limitParam"
        - $ref: "#/parameters/startingAfterParam"
        - $ref: "#/parameters/endingBeforeParam"
        - $ref: "#/parameters/sortByParam"
        - $ref: "#/parameters/createdOnParam"
        - $ref: "#/parameters/createdBeforeParam"
        - $ref: "#/parameters/createdAfterParam"
      responses: 
        200:
          description: List of events returned succesfully
        405: 
          description: Invalid input
  /merchants/id/{merchantId}:
    put:
      tags:
        - Merchants
      summary: Updats an existing merchant
      description: ""
      operationId: saveMerchant
      parameters:
        - name: merchantId
          in: path
          type: string
          description: Unique identifier for the merchant
          required: true
        - name: body
          in: body
          description: The Merchant object state that you want to save
          required: true
          schema:
            $ref: "#/definitions/Merchant"
      responses:
        "200":
          description: Merchant updated successfully
        "405":
          description: Invalid input
    patch: 
      tags:
        - Merchants
      summary: Updats an existing merchant by sending only the changed state rather than the entire merchant graph. Can be used for adding or removing stores without having to retreive the merchant object first.
      description: ""
      operationId: saveMerchant
      parameters:
        - name: merchantId
          in: path
          type: string
          description: Unique identifier for the merchant
          required: true
        - name: body
          in: body
          description: The Merchant changes that you want to apply
          required: true
          schema:
            $ref: "#/definitions/Merchant"
      responses:
        "200":
          description: Merchant updated successfully
        "405":
          description: Invalid input
    get: 
      tags:
        - Merchants
      summary: Retrieves a merchant by ID
      description: ""
      operationId: getMerchantById
      parameters:
        - name: merchantId
          in: path
          type: string
          description: Unique identifier for the merchant
          required: true
        - $ref: "#/parameters/fetchParam"
      responses:
        "200":
          description: Merchant retreived successfully
        "405":
          description: Invalid input
  /offers:
    post:
      tags:
        - Offers
      summary: Add a new offer to the network
      description: ""
      operationId: addOffer
      parameters:
        - in: body
          name: body
          description: Offer object that needs to be added to the network
          required: true
          schema:
            $ref: "#/definitions/Offer"
      responses:
        "405":
          description: Invalid input
    get: 
      tags:
        - Offers
      summary: Retrieve a list of offers in the network
      operationId: getOffers
      parameters:
        - name: offerId
          in: query
          type: string
          description: Filter by Offer ID
        - name: visaOfferId
          in: query
          type: string
          description: Filter by Visa Offer ID
        - name: mcOfferId
          in: query
          type: string
          description: Filter by Master Card Offer ID
        - name: amexOfferId
          in: query
          type: string
          description: Filter by American Express Offer ID
        - name: lnOfferId
          in: query
          type: string
          description: Filter by Linkable Networks Offer ID
        - name: offerName
          in: query
          type: string
          description: Filter by Offer Name
        - name: offerType
          in: query
          type: string
          description: Filter by Offer Type
        - name: title
          in: query
          type: string
          description: Filter by Offer Title
        - name: status
          in: query
          type: string
          description: Filter by Visa Offer Status
        - name: merchantId
          in: query
          type: string
          description: Filter by associated Merchant ID
        - name: visaTemplateName
          in: query
          type: string
          description: Filter by Visa Template Name
        - name: awardFixed
          in: query
          type: number
          format: double
          description: Filter by Fixed Award Amount
        - name: awardMax
          in: query
          type: number
          format: double
          description: Filter by the Max Award Amount
        - name: awardPercent
          in: query
          type: string
          description: Filter by Award Percentage
        - name: redemptionStartDate
          in: query
          type: string
          format: date-time
          description: Filter by Redeption Start Date
        - name: redemptionEndDate
          in: query
          type: string
          format: date-time
          description: Filter by Redeption End Date
        - $ref: "#/parameters/limitParam"
        - $ref: "#/parameters/startingAfterParam"
        - $ref: "#/parameters/endingBeforeParam"
        - $ref: "#/parameters/sortByParam"
        - $ref: "#/parameters/createdOnParam"
        - $ref: "#/parameters/createdBeforeParam"
        - $ref: "#/parameters/createdAfterParam"
      responses: 
        200:
          description: List of offers returned succesfully
        405: 
          description: Invalid input
  /offers/id/{offerId}:
    put:
      tags:
        - Offers
      summary: Updats an existing offer
      description: ""
      operationId: saveOffer
      parameters:
        - name: offerId
          in: path
          type: string
          description: Unique identifier for the offer
          required: true
        - in: body
          name: body
          description: The Offer object state that you want to save
          required: true
          schema:
            $ref: "#/definitions/Offer"
      responses:
        "200":
          description: Offer updated successfully
        "405":
          description: Invalid input
    patch:
        tags:
          - Offers
        summary: Updats an existing offer by passing only the changes you want to apply. Can be used to link an offer to a customer 
        description: ""
        operationId: saveOffer
        parameters:
          - name: offerId
            in: path
            type: string
            description: Unique identifier for the offer
            required: true
          - in: body
            name: body
            description: The Offer changes that you want to save
            required: true
            schema:
              $ref: "#/definitions/Offer"
        responses:
          "200":
            description: Offer updated successfully
          "405":
            description: Invalid input
    get: 
      tags:
        - Offers
      summary: Retrieves an offer by ID
      description: ""
      operationId: getOfferById
      parameters:
        - name: offerId
          in: path
          type: string
          description: Unique RCLON identifier for the offer
          required: true
      responses:
        "200":
          description: Offer retrieved successfully
        "405":
          description: Invalid input
  /customers:
    post:
      tags:
        - Customers
      summary: Adds and enrolls a new customer to the network
      description: ""
      operationId: addCustomer
      parameters:
        - in: body
          name: body
          description: Customer object that needs to be added to the network
          required: true
          schema:
            $ref: "#/definitions/Customer"
      responses:
        "405":
          description: Invalid input
    get: 
      tags:
        - Customers
      summary: Retrieve a list of customers in the network
      operationId: getCustomers
      parameters:
        - name: customerId
          in: query
          type: string
          description: Filter by Customer ID
        - name: firstName
          in: query
          type: string
          description: Filter by First Name
        - name: lastName
          in: query
          type: string
          description: Filter by Last Name
        - name: visaProfileId
          in: query
          type: string
          description: Filter by Visa Profile Name
        - name: membershipNumber
          in: query
          type: string
          description: Filter by Membership Number
        - name: promoCode
          in: query
          type: string
          description: Filter by Promo Code
        - name: referrerId
          in: query
          type: string
          description: Filter by Referrer ID
        - name: email
          in: query
          type: string
          description: Filter by Email
        - name: phone
          in: query
          type: string
          description: Filter by Phone
        - name: isEmailPreferred
          in: query
          type: string
          description: Filter by Customer's that prefer to be contacted by email
        - name: isSMSPreferred
          in: query
          type: string
          description: Filter by Customer's that prefer to be contacted by text message
        - name: visaUserKey
          in: query
          type: number
          description: Filter by Visa User Key
        - name: visaEnrolled
          in: query
          type: boolean
          description: Filter by customers that are enrolled to Visa's Offer Platform
        - name: mcEnrolled
          in: query
          type: boolean
          description: Filter by customers that are enrolled to MasterCards's Offer Platform
        - name: amexEnrolled
          in: query
          type: boolean
          description: Filter by customers that are enrolled to American Express' Offer Platform
        - name: lnEnrolled
          in: query
          type: boolean
          description: Filter by customers that are enrolled to Linkable Networks
        - name: publisherVaultId
          in: query
          type: string
          description: Find a customer using the publisher's card vault ID
        - name: linkedOfferId
          in: query
          type: string
          description: Find customers that are linked to a particular offer
        - name: redeemedOfferId
          in: query
          type: string
          description: Find customers that have redeemed a particular offer
        - name: eventId
          in: query
          type: string
          description: Find customers are associated to a particular event
        - $ref: "#/parameters/limitParam"
        - $ref: "#/parameters/startingAfterParam"
        - $ref: "#/parameters/endingBeforeParam"
        - $ref: "#/parameters/sortByParam"
        - $ref: "#/parameters/createdOnParam"
        - $ref: "#/parameters/createdBeforeParam"
        - $ref: "#/parameters/createdAfterParam"
      responses: 
        200:
          description: List of events returned succesfully
        405: 
          description: Invalid input  
  /customers/id/{customerId}:
    put:
      tags:
        - Customers
      summary: Updates an existing customer
      description: ""
      operationId: saveCustomer
      parameters:
        - name: customerId
          in: path
          type: string
          description: Unique RCLON identifier for the customer
          required: true
        - in: body
          name: body
          description: The Customer object state you want to save
          required: true
          schema:
            $ref: "#/definitions/Customer"
      responses:
        "200":
          description: Customer updated successfully
        "405":
          description: Invalid input
    patch:
      tags:
        - Customers
      summary: Updats an existing customer by passing only a change object
      description: ""
      operationId: saveCustomer
      parameters:
        - name: customerId
          in: path
          type: string
          description: Unique RCLON identifier for the customer
          required: true
        - in: body
          name: body
          description: The Customer changes you want to apply
          required: true
          schema:
            $ref: "#/definitions/Customer"
      responses:
        "200":
          description: Customer updated successfully
        "405":
          description: Invalid input
    get: 
      tags:
        - Customers
      summary: Retrieves a customer by ID
      description: ""
      operationId: getCustomerById
      consumes:
        - application/json
        - application/xml
      produces:
        - application/json
        - application/xml
      parameters:
        - name: customerId
          in: path
          type: string
          description: Unique identifier for the customer
          required: true
      responses:
        "200":
          description: Customer retreived successfully
        "405":
          description: Invalid input
  /events/customerId/{customerId}:
    get:
      tags: 
        - Events
      summary: Retrieves a list of events for a given customer
      description: ""
      operationId: getEvents
      parameters: 
        - name: customerId
          in: path
          type: string
          description: You must specify which customer's events you want to retrieve
          required: true
        - name: eventType
          in: query
          type: string
          description: Filter by Event Type. Possible values are cardauthevent, cardsettlementevent, offertimeoutevent
        - $ref: "#/parameters/limitParam"
        - $ref: "#/parameters/startingAfterParam"
        - $ref: "#/parameters/endingBeforeParam"
        - $ref: "#/parameters/sortByParam"
        - $ref: "#/parameters/createdOnParam"
        - $ref: "#/parameters/createdBeforeParam"
        - $ref: "#/parameters/createdAfterParam"
      responses: 
        200:
          description: List of events returned succesfully
        405: 
          description: Invalid input
  /events/{cardAssociationCode}/type/{eventType}:
    get:
      operationId: getEvents
      parameters:
        - name: cardAssociationCode
          in: path
          type: string
          description: The card network that published the event. Possible values are visa, mc, amex, ln
          required: true
        - name: eventType
          in: path
          type: string
          description: The type of event. Possible values are cardauthevent, cardsettlementevent, offertimeoutevent
          required: true
        - name: merchantId
          in: query
          type: number
          description: Filter by Merchant ID
        - name: merchantStoreId
          in: query
          type: number
          description: Filter by Merchant Store ID
        - $ref: "#/parameters/limitParam"
        - $ref: "#/parameters/startingAfterParam"
        - $ref: "#/parameters/endingBeforeParam"
        - $ref: "#/parameters/sortByParam"
        - $ref: "#/parameters/createdOnParam"
        - $ref: "#/parameters/createdBeforeParam"
        - $ref: "#/parameters/createdAfterParam"
      responses: 
        200:
          description: List of events returned succesfully
        405: 
          description: Invalid input
  /events/id/{eventId}:
    get:
      operationId: getEventById
      parameters:
        - name: eventId
          in: path
          type: string
          description: Unique RCLON identifier for the event
          required: true
        - $ref: "#/parameters/limitParam"
        - $ref: "#/parameters/startingAfterParam"
        - $ref: "#/parameters/endingBeforeParam"
        - $ref: "#/parameters/sortByParam"
        - $ref: "#/parameters/createdOnParam"
        - $ref: "#/parameters/createdBeforeParam"
        - $ref: "#/parameters/createdAfterParam"
      responses: 
        200:
          description: Events object returned succesfully
  /events/{cardAssociationCode}/type/{eventType}/id/{eventId}:
    get: 
      operationId: getEventByAssociationId
      parameters:
        - name: cardAssociationCode
          in: path
          type: string
          description: The card network that published the event. Possible values are visa, mc, amex, ln
          required: true
        - name: eventType
          in: path
          type: string
          description: The type of event. Possible values are cardauthevent, cardsettlementevent, offertimeoutevent
          required: true
        - name: eventId
          in: path
          type: string
          description: The unique identifier as specified by the card association.
          required: true
        - $ref: "#/parameters/limitParam"
        - $ref: "#/parameters/startingAfterParam"
        - $ref: "#/parameters/endingBeforeParam"
        - $ref: "#/parameters/sortByParam"
        - $ref: "#/parameters/createdOnParam"
        - $ref: "#/parameters/createdBeforeParam"
        - $ref: "#/parameters/createdAfterParam"
      responses: 
        200:
          description: List of events returned succesfully
        405: 
          description: Invalid input
definitions:
  Customer:
    required:
      - customerId
      - firstName
      - lastName
    properties:
      customerId:
        type: integer
        format: int32
        example: '1'
      firstName:
        type: string
        example: sample firstName
      lastName:
        type: string
        example: sample lastName
      visaProfileId:
        type: string
        example: sample visaProfileId
      memberShipNumber:
        type: string
        example: sample membershipNumber
      promoCode:
        type: string
        example: sample promoCode
      referrerId:
        type: string
        example: sample referrerId
      email:
        type: string
        example: sample email
      phone:
        type: string
        example: sample phone
      isEmailPreferred:
        type: boolean
        example: 'false'
      isSMSPreferred:
        type: boolean
        example: 'false'
      visaUserKey:
        type: string
        example: 234231-21342
      visaEnrolled:
        type: boolean
        example: 'false'
      mcEnrolled:
        type: boolean
        example: 'false'
      amexEnrolled:
        type: boolean
        example: 'false'
      lnEnrolled:
        type: boolean
        example: 'false'
      cards:
       type: array
       items:
        $ref: "#/definitions/PaymentCard"
      authorizedOffers:
        type: array
        items:
          $ref: "#/definitions/CustomerAuthorizedOffer"
    description: "A Customer is the end-user of a Publisher's website or mobile app. Customers enter their credit card payment information and can link offers to their credit cards to earn cash back on in-store purchases."
    example: '{"customerId":1,"firstName":"sample firstName","lastName":"sample lastName","visaProfileId":"sample visaProfileId","memberShipNumber":"sample memberShipNumber","promoCode":"sample promoCode","referrerId":"sample referrerId","email":"sample email","phone":"sample phone","isEmailPreferred":false,"isSMSPreferred":false,"visaUserKey":"sample visaUserKey","visaEnrolled":false,"mcEnrolled":false,"lnEnrolled":false}'
  PaymentCard:
    properties:
      publisherVaultId:
        type: string
        example: sample uscVaultId
      cardType:
        type: string
        example: VISA
      visaCardId:
        type: string
        example: sample visaCardId
      cardNumber:
        type: string
        example: sample cardNumber
      visaProfileId:
        type: string
        example: sample visaProfileId
      contacts:
        type: array
        items:
          $ref: '#/definitions/CardHolderContact'
      cvv2:
        type: integer
        format: int32
        example: '1'
      expMonth:
        type: integer
        format: int32
        example: '1'
    example: '{"uscVaultId":"sample uscVaultId","cardType":"VISA","visaCardId":"sample visaCardId","cardNumber":"sample cardNumber","visaProfileId":"sample visaProfileId","contacts":[],"cvv2":1,"expMonth":1}'
  MerchantStore:
    required:
      - merchantId
      - storeId
    properties:
      merchantId:
        type: integer
        format: int32
        example: '1'
      storeId:
        type: string
        example: sample storeId
      visaStoreId:
        type: string
        example: sample visaStoreId
      storeName:
        type: string
        example: sample storeName
    description: A MerchantStore is a physical redeeming location that honors an offer.
    example: '{"merchantId":1,"storeId":"sample storeId","visaStoreId":"sample visaStoreId","storeName":"sample storeName"}'
  Merchant:
    required:
      - enterpriseName
    properties:
      merchantId:
        type: integer
        format: int32
        example: '1'
        description: RCLON Merchant Identifier
      enterpriseAddress:
        $ref: '#/definitions/MerchantEnterpriseAddress'
      enterpriseName:
        type: string
        example: sample enterpriseName
      visaFranchiseId:
        type: string
        example: sample visaFranchiseId
      visaMerchantId:
        type: string
        example: sample visaMerchantId
      visaMerchantName:
        type: string
        example: sample visaMerchantName
      visaMerchantEnterpriseId:
        type: string
        example: sample visaMerchantEnterpriseId
      aquirerBin:
        type: string
        example: sample aquirerBin
      acquirerMerchantId:
        type: string
        example: sample acquirerMerchantId
      cardAcceptorId:
        type: string
        example: sample cardAcceptorId
      visaCommunityCode:
        type: string
        example: sample visaCommunityCode
      stores:
        type: array
        items:
          $ref: '#/definitions/MerchantStore'
    description: 'A merchant is a business entity who sells commodities in order to earn a profit. In RCLON, they can manage offers that customers can link their credit cards to.'
    example: '{"merchantId":1,"enterpriseAddress":null,"enterpriseName":"sample enterpriseName","visaFranchiseId":"sample visaFranchiseId","visaMerchantId":"sample visaMerchantId","visaMerchantName":"sample visaMerchantName","visaMerchantEnterpriseId":"sample visaMerchantEnterpriseId","aquirerBin":"sample aquirerBin","acquirerMerchantId":"sample acquirerMerchantId","cardAcceptorId":"sample cardAcceptorId","visaCommunityCode":"sample visaCommunityCode","stores":[]}'
  CardHolderContact:
    properties:
      contactId:
        type: integer
        format: int32
        example: '1'
        description: Generated ID
      confirmationCode:
        type: string
        example: sample confirmationCode
      visaContactType:
        type: string
        example: sample visaContactType
      verified:
        type: string
        example: sample verified
      countryCode:
        type: string
        example: sample countryCode
    example: '{"contactId":1,"confirmationCode":"sample confirmationCode","visaContactType":"sample visaContactType","verified":"sample verified","countryCode":"sample countryCode"}'
  MerchantEnterpriseAddress:
    required:
      - line1
      - addressName
      - city
      - country
      - state
    properties:
      addressName:
        type: string
        example: Executive Office
      line1:
        type: string
        example: 101 1st. St
      line2:
        type: string
        example: Unit 201
      city:
        type: string
        example: San Diego
      state:
        type: string
        example: CA
      postalCode:
        type: string
        example: '92091'
      country:
        type: string
        example: USA
    example: '{"addressName":"Executive Office","addressLine1":"101 1st. St","addressLine2":"Unit 201","country":"USA","city":"San Diego","state":"CA","postalCode":"92091"}'
  Offer:
    required:
      - merchant
      - offerId
      - offerName
      - offerType
      - redemptionStartDate
      - redeptionEndDate
      - status
      - title
    properties:
      offerId:
        type: integer
        format: int32
        example: '1'
      visaOfferId:
        type: string
        example: sample visaOfferId
      lsOfferId:
        type: string
        example: sample lsOfferId
      mcOfferId:
        type: string
        example: sample mcOfferId
      amexOfferId:
        type: string
        example: sample amexOfferId
      offerName:
        type: string
        example: sample offerName
      title:
        type: string
        example: sample title
      status:
        type: string
        example: sample status
      merchant:
        $ref: '#/definitions/Merchant'
      visaTemplateName:
        type: string
        example: sample visaTemplateName
      awardFixed:
        type: number
        format: double
        example: '5.99'
      awardMax:
        type: number
        format: double
        example: '99.99'
      awardPercent:
        type: number
        format: double
        example: '23.54'
      redemptionStartDate:
        type: string
        format: date
        example: '1434831820328'
      redeptionEndDate:
        type: string
        format: date
        example: '1466406000000'
      offerType:
        type: string
        example: sample offerType
    description: An Offer is a merchants way of providing their commodities to customers with a discount incentive.
    example: '{"offerId":1,"visaOfferId":"sample visaOfferId","lsOfferId":"sample lsOfferId","mcOfferId":"sample mcOfferId","amexOfferId":"sample amexOfferId","offerName":"sample offerName","title":"sample title","status":"sample status","merchant":null,"visaTemplateName":"sample visaTemplateName","awardFixed":5.99,"awardMax":99.99,"awardPercent":23.54,"redemptionStartDate":1434831820328,"redeptionEndDate":1466406000000,"offerType":"sample offerType"}'
  CustomerAuthorizedOffer: 
    required:
      - offerId
      - customerId
    properties:
      offerId:
        type: integer
        format: int32
        example: '1'
      customerId:
        type: integer
        format: int32
        example: '1'
parameters: 
  limitParam:
    name: limit
    in: query
    description: Pagination parameter that limits the number of returned results
    required: false
    type: number
    format: int32
  startingAfterParam:
    name: startingAfter
    in: query
    description: Pagination parameter that tells the system which record to start the fetch cursor
    required: false
    type: number
    format: int32
  endingBeforeParam:
    name: endingBefore
    in: query
    description: Pagination parameter that tells the system when to end the fetch cursor
    required: false
    type: number
    format: int32
  fetchParam:
    name: fetch
    in: query
    description: Tells the system to also return the objects child collection  
    type: string
  createdOnParam:
    name: createdOn
    in: query
    description: Filter to return only records that were created on a certain date and time 
    type: string
    format: date-time
  createdBeforeParam:
    name: createdBefore
    in: query
    description: Filter to return only records that were created BEFORE a certain date and time
    type: string
    format: date-time
  createdAfterParam:
    name: createdAfter
    in: query
    description: Filter to return only records that were created AFTER a certain date 
    type: string
    format: date-time
  sortByParam:
    name: sortBy
    in: query
    type: string
    description: Field Name and Sort Direction settings when returning a list. Each sortBy field/direction pair is seperated by comma.
````

**Comment by wing328** [comment] 2015-06-23 04:31
I'm able to generate the following from the latest master
```
swagger-codegen|master⚡ ⇒ java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate \
>    -i http://petstore.swagger.io/v2/swagger.json \
>    -l spring-mvc \
>    -o /var/tmp/
reading from http://petstore.swagger.io/v2/swagger.json
writing file /var/tmp/src/main/java/io/swagger/model/Order.java
writing file /var/tmp/src/main/java/io/swagger/model/Category.java
writing file /var/tmp/src/main/java/io/swagger/model/User.java
writing file /var/tmp/src/main/java/io/swagger/model/Tag.java
writing file /var/tmp/src/main/java/io/swagger/model/Pet.java
writing file /var/tmp/src/main/java/io/swagger/model/ApiResponse.java
writing file /var/tmp/src/main/java/io/swagger/api/StoreApi.java
writing file /var/tmp/src/main/java/io/swagger/api/PetApi.java
writing file /var/tmp/src/main/java/io/swagger/api/UserApi.java
writing file /var/tmp/pom.xml
writing file /var/tmp/README.md
writing file /var/tmp/src/main/java/io/swagger/api/ApiException.java
writing file /var/tmp/src/main/java/io/swagger/api/ApiOriginFilter.java
writing file /var/tmp/src/main/java/io/swagger/api/ApiResponseMessage.java
writing file /var/tmp/src/main/java/io/swagger/api/NotFoundException.java
writing file /var/tmp/src/main/java/io/swagger/configuration/SwaggerConfig.java
writing file /var/tmp/src/main/java/io/swagger/configuration/WebApplication.java
writing file /var/tmp/src/main/java/io/swagger/configuration/WebMvcConfiguration.java
writing file /var/tmp/src/main/java/io/swagger/configuration/SwaggerUiConfiguration.java
```

I believe swagger editor is using http://generator.swagger.io/ so I will do a check with the online generator shortly

**Comment by cosbor11** [comment] 2015-06-23 05:22
swagger-codegen works fine; just not working from swagger-editor

**Comment by webron** [comment] 2015-06-23 07:36
@wing328 - the online generator is a runtime of the master version. If there's a problem, please let me know.

**Comment by wing328** [comment] 2015-06-23 07:43
We did test with the master version (zip file for version 2.1.2 and pull from github) and it's working fine so we're not sure why the online generator failed.

**Comment by webron** [comment] 2015-06-23 10:24
That is indeed odd. Will have to investigate the online generator.

**Comment by wing328** [comment] 2015-06-23 10:29
Agreed that it's odd. Not sure if bouncing the server would help.

**Comment by wing328** [comment] 2015-06-24 06:06
Not sure what has been done but now seems like the issue has gone for spring-mvc:

14|⇒ unzip 1435125721805 
Archive:  1435125721805
  inflating: spring-mvc-server/src/main/resources/swagger.properties  
  inflating: spring-mvc-server/src/main/java/io/swagger/model/User.java  
  inflating: spring-mvc-server/src/main/java/io/swagger/model/Order.java  
  inflating: spring-mvc-server/src/main/java/io/swagger/model/Tag.java  
  inflating: spring-mvc-server/src/main/java/io/swagger/model/Category.java  
  inflating: spring-mvc-server/src/main/java/io/swagger/model/ApiResponse.java  
  inflating: spring-mvc-server/src/main/java/io/swagger/model/Pet.java  
  inflating: spring-mvc-server/src/main/java/io/swagger/api/ApiOriginFilter.java  
  inflating: spring-mvc-server/src/main/java/io/swagger/api/ApiResponseMessage.java  
  inflating: spring-mvc-server/src/main/java/io/swagger/api/ApiException.java  
  inflating: spring-mvc-server/src/main/java/io/swagger/api/PetApi.java  
  inflating: spring-mvc-server/src/main/java/io/swagger/api/NotFoundException.java  
  inflating: spring-mvc-server/src/main/java/io/swagger/api/UserApi.java  
  inflating: spring-mvc-server/src/main/java/io/swagger/api/StoreApi.java  
  inflating: spring-mvc-server/src/main/java/io/swagger/configuration/SwaggerConfig.java  
  inflating: spring-mvc-server/src/main/java/io/swagger/configuration/SwaggerUiConfiguration.java  
  inflating: spring-mvc-server/src/main/java/io/swagger/configuration/WebMvcConfiguration.java  
  inflating: spring-mvc-server/src/main/java/io/swagger/configuration/WebApplication.java  
  inflating: spring-mvc-server/pom.xml  
  inflating: spring-mvc-server/README.md  

@cosbor11 @mohsen1 would you please give it another try to see if it also works for you ?

**Comment by wing328** [comment] 2015-06-25 05:23
@mohsen1 if you could no longer repeat the issue, would you please close this issue? Thanks.

**Comment by mohsen1** [comment] 2015-06-25 15:54
In online editor it's still not working properly. Just try it via Swagger Editor.

**Comment by wing328** [comment] 2015-06-26 00:51
Just tried SwaggerEditor and here is the result

![screen shot 2015-06-26 at 8 48 17 am](https://cloud.githubusercontent.com/assets/934260/8368689/35a8643a-1be0-11e5-97b7-9b27573651ed.png)

I could find ProductsApi.java, EstimatesApi.java, MeApi.java, HistoryApi.java.

**Comment by mohsen1** [comment] 2015-06-26 03:41
Please try using the swagger spec pasted in this issue

**Comment by cosbor11** [comment] 2015-06-26 08:18
Just tried again; not working. It only generated the model classes

**Comment by wing328** [comment] 2015-06-26 15:48
FYI. Did a test again with master version of swagger-codegen and confirmed it's able to generate the "api" files. Here is part of the output:

```
writing file /var/tmp/perl/test/src/main/java/io/swagger/client/api/DefaultApi.java
writing file /var/tmp/perl/test/src/main/java/io/swagger/client/api/CustomersApi.java
writing file /var/tmp/perl/test/src/main/java/io/swagger/client/api/MerchantsApi.java
writing file /var/tmp/perl/test/src/main/java/io/swagger/client/api/EventsApi.java
writing file /var/tmp/perl/test/src/main/java/io/swagger/client/api/OffersApi.java
writing file /var/tmp/perl/test/pom.xml
writing file /var/tmp/perl/test/src/main/java/io/swagger/client/ApiClient.java
writing file /var/tmp/perl/test/src/main/java/io/swagger/client/ApiException.java
writing file /var/tmp/perl/test/src/main/java/io/swagger/client/Configuration.java
writing file /var/tmp/perl/test/src/main/java/io/swagger/client/JsonUtil.java
writing file /var/tmp/perl/test/src/main/java/io/swagger/client/StringUtil.java
writing file /var/tmp/perl/test/src/main/java/io/swagger/client/auth/Authentication.java
writing file /var/tmp/perl/test/src/main/java/io/swagger/client/auth/HttpBasicAuth.java
writing file /var/tmp/perl/test/src/main/java/io/swagger/client/auth/ApiKeyAuth.java
writing file /var/tmp/perl/test/src/main/java/io/swagger/client/auth/OAuth.java
```

Really have no idea why the online codegen server behaves differently

**Comment by fehguy** [comment] 2015-07-21 06:31
After digging into this, it turns out to be a code bug, not deployment bug.  The SwaggerParser library, which reads the specification, will accept an optional `boolean resolve` flag, which tells the library to resolve all references.  It was not set in the online codegen.

See the parser fix here:  https://github.com/swagger-api/swagger-parser/commit/d8848ba6a93b75a3320cd23342a9b7c7da4d0a54

Pushing a fix to codegen as well.

**Comment by fehguy** [comment] 2015-07-21 06:32
Deployed to the online codegen

**Closed by fehguy** 2015-07-21 06:32 UTC

**Comment by wing328** [comment] 2015-07-21 09:40
@fehguy thanks for fixing the issue. I've filed a PR (merged) to update pom.xml to use 1.0.9-SNAPSHOT for swagger-parser so as to avoid the compilation error reported by Travis-CI.
