### ISSUE TITLE
[JAVA-JAXRS-server][Windows] Mixing of path separators causes ..ServiceImpl.java to be generated in wrong directory

### ISSUE THREAD

**Issue by williamd67** [swagger-api/swagger-codegen#9045] opened 2019-01-09 13:55 UTC
##### Description

When using the 2.4.0 release of swagger-codegen on a MS Windows machine the path of the generated <..>ServiceImpl.java files is incorrect. The path is in that case ./src/gen/java/io/swagger/impl/api/<..>ServiceImpl.java in stead of ./src/main/java/io/swagger/api/impl/<...>ServiceImpl.java.

This is caused by mixing the different path separators (Linux and Windows) in the code of the swagger code generator.

##### Swagger-codegen version

This is observed in version 2.4.0 and as far as I am aware this is a regression as we did not have this issue with version 2.3.1.

##### Swagger declaration file content or url

The standard petstore.yaml will show the issue.

##### Command line used for generation

java -jar swagger-codegen-cli.jar generate -i petstore.yaml -l jaxrs-resteasy -o tmp

##### Steps to reproduce

Run the above command on MS Windows.

##### Related issues/PRs

Issue #1391 describes the same kind of issue which has been resolved.
https://github.com/swagger-api/swagger-codegen/issues/1391

##### Suggest a fix/enhancement

It can be fixed by changing file: ./swagger-codegen/src/main/java/io/swagger/codegen/languages/AbstractJavaJAXRSServerCodegen.java especially the method apiFilename where the mix of Linux and Windows path separators is causing issues. The fix is to make all paths use the same path separator ('/') by replacing the Windows-separator '\\' with the Linux path-separator '/'.

**Comment by dott-ing** [comment] 2020-01-21 09:54
The issue is still happening.
I've used the swagger-codegen-maven-plugin version 2.4.12 and 2.4.10 with Maven 3.6.3 on Windows (the issue only occurs on windows).

As suggested by @williamd67 the path separator should be aligned in the two apiFilename methods.

[wrong_path_patch.txt](https://github.com/swagger-api/swagger-codegen/files/4090337/wrong_path_patch.txt)

**Comment by shrutscode** [comment] 2020-04-27 23:06
We are also facing this issue. Any update on fixing this?

**Comment by ttjarl** [comment] 2020-10-21 12:46
This problem also has as side-effect that importing a maven project to IntelliJ is not working (on Windows). The IntelliJ maven importer is not able to figure out what is the source root of generated code since there is mismatch between directory structure and package structure.

I have as an intermediate fix added a step to my build that rename the impl and factories directories to their correct names, but it would be preferable that this problem is fixed.

**Comment by HugoMario** [comment] 2022-08-27 07:10
fixed by https://github.com/swagger-api/swagger-codegen-generators/pull/1053

**Closed by HugoMario** 2022-08-27 07:10 UTC
