### ISSUE TITLE
c# code generated for "enum" does not work

### ISSUE THREAD

**Issue by saharj** [swagger-api/swagger-codegen#2429] opened 2016-03-22 19:11 UTC
_From @edarn on March 22, 2016 9:36_

It appears to me that the client side c# code generated for enums is not correct for enums. I don´t find any enum at all. However, it looks ok for Java.

 SalesItemBrief:
    type: object
    properties:
      ItemId:
        type: string
      ItemType:
        $ref: "#/definitions/ItemTypeEnum"

  ItemTypeEnum:
    type: string
    enum:
      - ART
      - SPR
      - GPR

Generated c# code:

namespace IO.Swagger.Model {

  /// <summary>
  /// 
  /// </summary>
  [DataContract]
  public class ItemTypeEnum {
    

    /// <summary>
    /// Get the string presentation of the object
    /// </summary>
    /// <returns>String presentation of the object</returns>
    public override string ToString()  {
      var sb = new StringBuilder();
      sb.Append("class ItemTypeEnum {\n");
      
      sb.Append("}\n");
      return sb.ToString();
    }

    /// <summary>
    /// Get the JSON string presentation of the object
    /// </summary>
    /// <returns>JSON string presentation of the object</returns>
    public string ToJson() {
      return JsonConvert.SerializeObject(this, Formatting.Indented);
    }

}

_Copied from original issue: swagger-api/swagger-editor#848_

**Comment by wing328** [comment] 2016-03-22 19:24
@edarn the latest master of swagger-codegen should have enum support for C#. Please pull the latest and give it a try.

**Comment by willerup** [comment] 2016-03-28 22:20
I think this is a duplicate of https://github.com/swagger-api/swagger-codegen/issues/2450.

**Comment by wing328** [comment] 2016-04-07 09:08
@edarn @willerup can you please give https://github.com/swagger-api/swagger-codegen/pull/2508 a try to see if it addresses the issue for your case?

**Comment by wing328** [comment] 2016-05-03 13:28
https://github.com/swagger-api/swagger-codegen/pull/2508 merged into master. Closing this one.

Please reply back if the latest master is not working for you.

**Closed by wing328** 2016-05-03 13:28 UTC
Labels: Bug, Client: C-Sharp
