### ISSUE TITLE
[csharp] Client generator ignore generatePropertyChanged parameter

### ISSUE THREAD

**Issue by lunat** [swagger-api/swagger-codegen#4206] opened 2016-11-17 14:20 UTC
##### Description

When generating Swagger Client with generatePropertyChanged = false, the generated client references PropertyChanged anyway.

Even so, the client is not working because file FodyWeavers.xml is missing so I must manually install Newtonsoft, RestSharp and Fody from Nuget.

But it is not enough: I manually need to edit FodyWeavers.xml by adding this row:

`<PropertyChanged />`

##### Swagger-codegen version

2.2.0

##### Steps to reproduce

Generate c# client with PropertyChanged = false

**Comment by wing328** [comment] 2016-11-22 17:39
@lunat does the following (petstore sample with PropertyChanged) works for you?

https://github.com/swagger-api/swagger-codegen/tree/master/samples/client/petstore/csharp/SwaggerClientWithPropertyChanged

**Comment by jimschubert** [comment] 2016-11-29 03:19
I compiled the linked project in Rider, then decompiled the DLL using dotPeek, and the `PropertyChanged` is generated as expected (master 93b6099):

```

    [DataMember(EmitDefaultValue = false, Name = "className")]
    public string ClassName
    {
      get
      {
        return this.\u003CClassName\u003Ek__BackingField;
      }
      set
      {
        if (string.Equals(this.\u003CClassName\u003Ek__BackingField, value, StringComparison.Ordinal))
          return;
        this.\u003CClassName\u003Ek__BackingField = value;
        this.OnPropertyChanged("ClassName");
      }
    }
```

I ran the same test case in Visual Studio 2015 in Windows 10 and got the same result.

I'll try regenerating the client to see if maybe the sample was manually edited.

**Comment by jimschubert** [comment] 2016-11-29 03:58
Did a little more digging into this issue. Version [2.2.0](https://github.com/swagger-api/swagger-codegen/blob/v2.2.0/modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/CSharpClientCodegen.java) in the report doesn't support `generatePropertyChanged`. Neither do [2.2.1](https://github.com/swagger-api/swagger-codegen/blob/v2.2.1/modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/CSharpClientCodegen.java) or the [2.3.0 branch](https://github.com/swagger-api/swagger-codegen/blob/2.3.0/modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/CSharpClientCodegen.java). It looks like this only exists in master (please correct me if I'm wrong).

The problem is that mustache's `{{#generatePropertyChanged}}` doesn't evaluate trues and falses, so a false value provided via `--additional-properties` needs to be removed. I'll open a PR for this.

The workaround is to just not pass the additional property with a `false` value. I assume this is an edge case and most usage would be with explicitly set to true (`--additional-properties=generatePropertyChanged=true`) and with `generatePropertyChanged` not provided when false.

This is a good catch, and I wonder if we should have some warning or throw an exception prior to generation when `additional-properties` still contain false values. @wing328 what's your thought on that?

**Comment by wing328** [comment] 2016-11-29 08:14
> This is a good catch, and I wonder if we should have some warning or throw an exception prior to generation when additional-properties still contain false values. @wing328 what's your thought on that?

My understanding is that `additional-properties` can be intentionally set to false to turn off certain features. I believe @jfiala  has written a function to handle boolean value obtained via `additional-properties` or  CLI options. We need to review our code to use that to prevent the same issue from happening again.

**Comment by wing328** [comment] 2016-12-06 17:05
@lunat #4280 merged into master. Please pull the latest and give it another try.

**Closed by wing328** 2016-12-06 17:05 UTC
Labels: Client: C-Sharp, Issue: Bug
