### ISSUE TITLE
[Javascript] useES6 is the default even though it shouldn't be

### ISSUE THREAD

**Issue by tray2100** [swagger-api/swagger-codegen#10305] opened 2020-06-07 09:01 UTC
##### Description

the ES5 templates should be used by default when generating a javascript client but it seems that the ES6 templates are actually being used by default.

##### Swagger-codegen version

3.0.19 ... not sure if this has worked in previous versions.

##### Swagger declaration file content or url

Used the petstore example to verify this issue

##### Command line used for generation

swagger-codegen generate -i https://raw.githubusercontent.com/OAI/OpenAPI-Specification/master/examples/v3.0/petstore.yaml -o testJavascript/ -l javascript

##### Steps to reproduce

swagger-codegen generate -i https://raw.githubusercontent.com/OAI/OpenAPI-Specification/master/examples/v3.0/petstore.yaml -o testJavascript/ -l javascript

**Comment by huang47** [comment] 2020-07-29 21:40
Is there a way to generate a ES5 client? I run below which doesn't seem to work though

```
swagger-codegen generate -i http://MY_SERVER/v2/swagger/governator-jaxrs.json -l javascript --additional-properties useES6=false
```

**Comment by jimni1222** [comment] 2021-07-05 05:30
I'm facing this issue also.. 
I created configuration file and added useES6 option like below

```
{
    "useES6": false
}
```

But this options seems like not work;

**Comment by alexaurus** [comment] 2022-09-28 18:09
anyone ever resolved this?

**Comment by waterwheels** [comment] 2024-02-06 03:44
I'm getting this same issue, I can't work out how to force it to use ES5

**Comment by HugoMario** [comment] 2024-02-06 04:43
I see... well, let's get this fixed :)

**Comment by HugoMario** [comment] 2024-02-08 00:43
I reviewed this issue and it was already fixed, so glong to close it. If you don't want to use ES6 templates. You just need to add the option:
```
--additional-properties useES6=false
```
in your CLI for code generation

**Closed by HugoMario** 2024-02-08 00:43 UTC

**Comment by waterwheels** [comment] 2024-02-08 00:50
That's weird, when I try `swagger-codegen generate -i $api_url -l javascript -o out --additional-properties useES6=false` it still generates code with class keyword classes

**Comment by HugoMario** [comment] 2024-02-08 01:58
What codegen version are you using?

**Comment by waterwheels** [comment] 2024-02-08 02:01
I'm using `3.0.52`, I installed via brew

**Comment by HugoMario** [comment] 2024-02-08 17:09
@waterwheels 
I noted the problem is actually the templates, no the option. Anyway this could be addressed in a different ticket.
