### ISSUE TITLE
[All] Codegen fails on encountering recursion

### ISSUE THREAD

**Issue by jonwakingup** [swagger-api/swagger-codegen#9608] opened 2019-07-29 08:38 UTC
##### Description

On encountering recursion in YAML OAS3, SwaggerHub Codegen fails with the following message:

> There was an error generating the documentation html code. Please ensure that the definition and all external refs (inc. domains) are valid.

I normally run CodeGen to produce HTML documentation.  As part of investigating the problem I found that it occurs with every type of Codegen output.  

Swagger-Editor reports the YAML as valid.

This problem is new and has appeared in SwaggerHub since the end of May 2019.

##### Swagger-codegen version

I use SwaggerHub and am not sure of the Codegen version.  The last time I successfully ran Codegen against a YAML document using recursion was 29th May 2019.  The first time I noticed this problem was 25th July 2019.  

##### Swagger declaration file content or url

[jon-stewart-Recursion-Issue-1.0.0-oas3-swagger.yaml.txt](https://github.com/swagger-api/swagger-editor/files/3033745/jon-stewart-Recursion-Issue-1.0.0-oas3-swagger.yaml.txt)

##### Command line used for generation

SwaggerHub export: any codegen option

##### Steps to reproduce

Load the YAML into SwaggerHub; perform any Codegen export

##### Related issues/PRs

[Codegen #8506](https://github.com/swagger-api/swagger-codegen/issues/8506) - I think this is similar but not the same: it looks like an HTML2 specific issue.

**Also of interest**

The Editor/UI also has a problem with recursion, as per issue [1973](https://github.com/swagger-api/swagger-editor/issues/1973).  The HTML documentation used to format recursion very nicely and issue 1973 quotes the HTML output as a way to do it.

##### Suggest a fix/enhancement

Look for potentially breaking changes in a release deployed to SwaggerHub after 29 May 2019.

**Comment by jonwakingup** [comment] 2019-07-30 07:06
P.S: Previously, the HTML document would render a simple recursive tree of TreeNode objects as follows:

**TreeNode**

  id
  _Integer_ The Id of this tree node 

  children (optional)
  _array[[TreeNode](.)]_ Array of child objects

**Comment by lemoinem** [comment] 2019-08-01 13:42
I believe this is caused by example generations (FYI: https://github.com/swagger-api/swagger-codegen-generators/issues/437, I didn't know your issue existed at the time)

Last time there was an issue with example generation, it took almost a year to fix (https://github.com/swagger-api/swagger-codegen/issues/6394).

For the command-line tool there is the `--disable-examples` that has been added in https://github.com/swagger-api/swagger-codegen/pull/9600 but not released yet.

It would be great if a release with this was provided soon.

**Comment by hkosova** [comment] 2019-08-21 08:10
According to #9546 this should be fixed in the latest SNAPSHOT version of the codegen.

**Comment by jonwakingup** [comment] 2019-08-21 11:05
Thanks @hkosova for the note - I will retest when the fix is available through SwaggerHub, and hopefully then close.

**Comment by hkosova** [comment] 2019-09-02 10:59
@jonwakingup SwaggerHub has updated their codegen, can you please retest?

**Comment by jonwakingup** [comment] 2019-09-02 12:30
The fix appears to be to remove all generation of Components with recursive elements.  This is disappointing: until recently the HTML documentation rendered them very nicely.  

Can anyone comment on this?  Are we now saying that Swagger Codegen does not support Components, such as tree structures, that have recursive elements?

I'll leave this open for 24 hours to see if anyone has anything else to say before closing.  It is good that it doesn't crash now.

**Closed** 2019-09-06 08:28 UTC
