### ISSUE TITLE
[Typescript] Regression: after #7112 the modelPropertyNaming is ignored

### ISSUE THREAD

**Issue by gennadiylitvinyuk** [swagger-api/swagger-codegen#7201] opened 2017-12-18 13:20 UTC
##### Description

Regression: after #7112 the modelPropertyNaming is ignored

##### Swagger-codegen version

3.0.0-20171123.081951-8

##### Steps to reproduce
Use
`
{
  "modelPropertyNaming": "original"
}
`
in config
##### Suggest a fix/enhancement

@JFCote has suggested a fix for the issue

**Comment by JFCote** [comment] 2017-12-18 13:51
@gennadiylitvinyuk Can you get my branch and try the fix please? 
https://github.com/swagger-api/swagger-codegen/pull/7202

Thanks!

**Comment by gennadiylitvinyuk** [comment] 2017-12-18 13:57
@JFCote Sorry, can't compile Java right now, I just use SNAPSHOTs to generate Client in Angular 5 project

**Comment by HermenOtter** [comment] 2017-12-27 10:55
@JFCote @wing328 There seems to be more regression since the change. Parameters with containing an _ are generated incorrectly.

Swagger definition:
`/sadr/v1/soorten_adres/{code_soort_adres}:`
is generated to 
`public removeSoortenAdres(code_soort_adres: string, <..snip..> {`
and
`return this.httpClient.delete<..snip..>soorten_adres/${encodeURIComponent(String(codeSoortAdres))}`,`

**Comment by JFCote** [comment] 2018-01-04 13:26
@HermenOtter Thanks for reporting the issue and opening a bug. I will check this today and report in 
 issue #7262 to keep things organized.

**Comment by wing328** [comment] 2018-01-29 13:46
Fixed in 2.3.1 stable release.

**Closed** 2018-01-29 13:46 UTC
