### ISSUE TITLE
when language is jaxrs the defined template is ignored

### ISSUE THREAD

**Issue by gpekofsky** [swagger-api/swagger-codegen#2800] opened 2016-05-08 01:14 UTC
If I set
 -l jaxrs -t /path/to/template
The template is always ignored.

This seems to be because in JavaJerseyServerCodegen.java
embeddedTemplateDir = templateDir = JAXRS_TEMPLATE_DIRECTORY_NAME + File.separator + "jersey1_18";

The specified template path is ignored altogether.

**Comment by wing328** [comment] 2016-05-08 16:02
@gpekofsky thanks for reporting the issue. Did you have a chance to try other server stub generator (e.g. springmvc) to see if the same issue persists? That would help us to easily plot the fix from other generator if the issue is jaxrs-specified. Thanks.

**Comment by narayanan** [comment] 2016-05-09 04:49
Generating server for jersey2 also does not work. Looks like these two are related. Code generator always generates jersey1_18 even if the value for `--library` option is `jersey2`. Here is the command I used to generate jersey2 server.

`java -jar swagger-codegen-cli.jar generate -i ./my-api-swagger.yaml -l jaxrs -o my-api --library jersey2`

**Comment by narayanan** [comment] 2016-05-09 05:21
Update: I don't see the "jersey2 server" not getting generated issue when I built the CLI jar from master and tried the same command. Looks like the issue is fixed recently.

Looking forward for 2.2.0 release to leverage the fix

**Comment by wing328** [comment] 2016-05-09 09:01
@gpekofsky would you please pull the latest master and give it another try?

**Comment by aboretum** [comment] 2016-05-09 19:16
It depends on where it works as intended, if the intended use for `-t` is for us to supply the entire template (`mustache`) files for server stub, then it is working on my machine for jersey-1.18. If it is used to overwrite only an individual file, the `-t` option seem to be ignored completely.

**Comment by wing328** [comment] 2016-06-02 08:47
@gpekofsky @narayanan please pull the latest and give it another try. (I've merged a PR that should have fixed the issue)

**Comment by qtstc** [comment] 2016-06-03 03:43
I am seeing the issue with version 2.16 and the current master build. Tried both cli tool and maven plugin, the template directory is not used. I don't think it is specific to jaxrs though, tried ruby, also seems to have the same problem. The template was used in 2.14 and 2.15.

**Comment by wing328** [comment] 2016-06-03 04:18
@qtstc thanks for doing a check with the latest master to confirm the issue. I'll look more into it and hopefully file a PR for the fix by this weekend.

**Comment by wing328** [comment] 2016-06-03 08:29
I did some tests and the `-t` (template) option works for me for both `ruby` and `jaxrs`.

Please share the full commands you used for repeating the issue.

**Comment by aboretum** [comment] 2016-06-03 15:11
I used the command below, and it is not working for me.
```
java -jar ./swagger-codegen/modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate   -i sample.yaml   -l jaxrs   -o ./test_template  -c codegen-config.json -t ./codgen/src/main/resources
```
It should take the templates in the directory specified by `-t`, right?

**Comment by wing328** [comment] 2016-06-03 15:14
You need to specify the exact location of the mustache files. e.g.
```
java -jar ./swagger-codegen/modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate -t /var/tmp/jaxrs_template/JavaJaxRS/libraries/jersey2 -i modules/swagger-codegen/src/test/resources/2_0/petstore.yaml -l jaxrs -o samples/server/petstore/jaxrs/jersey2 -DhideGenerationTimestamp=true
```
in which `/var/tmp/jaxrs_template/JavaJaxRS/libraries/jersey2` contains your customized mustache files.

**Comment by qtstc** [comment] 2016-06-03 17:49
Tried cli tool again with latest master. Command I used:
` java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate -i http://petstore.swagger.io/v2/swagger.json -t modules/swagger-codegen/src/main/resources/JavaJaxRS/libraries/jersey1/ -l jaxrs`
I changed modules/swagger-codegen/src/main/resources/JavaJaxRS/libraries/jersey1/api.mustache, but I am not seeing the change in the generated PetApi.java

**Comment by wing328** [comment] 2016-06-03 18:42
@qtstc can you please also try full path (e.g. /var/tmp/jaxrs_template/JavaJaxRS/libraries/jersey2) instead of relative path?

**Comment by qtstc** [comment] 2016-06-03 21:50
Tried with full path, still doesn't work. Full path worked with 2.15 though.

**Comment by qtstc** [comment] 2016-06-03 22:49
I see the problem now. In getFullTemplateFile of AbstractGenerator:
`
    if (library != null && !"".equals(library)) {
      String libTemplateFile = config.templateDir() + File.separator +
          "libraries" + File.separator + library + File.separator +
          templateFile;
`
So it worked when I passed in 
`codegen/src/main/resources/JavaJaxRS/`
instead of 
`codegen/src/main/resources/JavaJaxRS/libraries/jersey1/`
as the templateDir.

I am not sure if this is a feature or a bug... but I think it makes sense to change either the documentation or this code.

**Comment by wing328** [comment] 2016-06-04 09:01
@qtstc thanks for the fix. I think it's a bug (although I seldom use the -t option myself)

Using the example you provide, the correct path should be `codegen/src/main/resources/JavaJaxRS/libraries/jersey1/`

I'll review your PR later.

**Comment by wing328** [comment] 2016-06-07 15:26
PR merged. Closing the issue.

**Closed by wing328** 2016-06-07 15:26 UTC
Labels: Bug, Server: Java
