### ISSUE TITLE
Example code doesn't work with swagger-codegen

### ISSUE THREAD

**Issue by saharj** [swagger-api/swagger-codegen#2680] opened 2016-04-22 02:14 UTC
_From @tylerlong on April 21, 2016 12:36_

Go to http://editor.swagger.io/

Menu --> File --> Open examples --> twitter.yaml

Menu --> File --> Download YAML, the file was saved as swagger.yaml

```
wget http://repo1.maven.org/maven2/io/swagger/swagger-codegen-cli/2.1.6/swagger-codegen-cli-2.1.6.jar -O swagger-codegen-cli.jar

java -jar swagger-codegen-cli.jar generate -i swagger.yaml -l csharp -o /tmp/test
```

Error message:

```
LMXMN061:Downloads tyler.liu$ java -jar swagger-codegen-cli.jar generate -i swagger.yaml -l csharp -o /tmp/test
[main] INFO io.swagger.parser.Swagger20Parser - reading from swagger.yaml
[main] WARN io.swagger.util.PropertyDeserializer - no property from null, null, {ENUM=null, TITLE=null, DESCRIPTION=null, DEFAULT=null, PATTERN=null, DESCRIMINATOR=null, MIN_ITEMS=null, MAX_ITEMS=null, MIN_PROPERTIES=null, MAX_PROPERTIES=null, MIN_LENGTH=null, MAX_LENGTH=null, MINIMUM=null, MAXIMUM=null, EXCLUSIVE_MINIMUM=null, EXCLUSIVE_MAXIMUM=null, UNIQUE_ITEMS=null, EXAMPLE=null, TYPE=null, FORMAT=null, READ_ONLY=null, VENDOR_EXTENSIONS={}}
Exception in thread "main" java.lang.RuntimeException: Could not process model 'inline_response_200_3'
	at io.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:244)
	at io.swagger.codegen.cmd.Generate.run(Generate.java:223)
	at io.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:36)
Caused by: java.lang.NullPointerException
	at io.swagger.codegen.languages.AbstractCSharpCodegen.getSwaggerType(AbstractCSharpCodegen.java:459)
	at io.swagger.codegen.DefaultCodegen.getTypeDeclaration(DefaultCodegen.java:862)
	at io.swagger.codegen.languages.AbstractCSharpCodegen.getTypeDeclaration(AbstractCSharpCodegen.java:482)
	at io.swagger.codegen.languages.AbstractCSharpCodegen.getTypeDeclaration(AbstractCSharpCodegen.java:475)
	at io.swagger.codegen.DefaultCodegen.fromProperty(DefaultCodegen.java:1247)
	at io.swagger.codegen.DefaultCodegen.addVars(DefaultCodegen.java:2232)
	at io.swagger.codegen.DefaultCodegen.addVars(DefaultCodegen.java:2206)
	at io.swagger.codegen.DefaultCodegen.addVars(DefaultCodegen.java:2193)
	at io.swagger.codegen.DefaultCodegen.fromModel(DefaultCodegen.java:1013)
	at io.swagger.codegen.languages.CSharpClientCodegen.fromModel(CSharpClientCodegen.java:273)
	at io.swagger.codegen.DefaultGenerator.processModels(DefaultGenerator.java:799)
	at io.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:237)
	... 2 more
```

The issue is either about swagger-codegen or example of swagger-editor.

_Copied from original issue: swagger-api/swagger-editor#879_

**Comment by saharj** [comment] 2016-04-22 02:14
We have realized that there is a problem with twitter.yaml example. Do you have this issue with other example files as well?

**Comment by saharj** [comment] 2016-04-22 02:14
_From @tylerlong on April 22, 2016 1:50_

@saharj yes, I tested several yesterday. instagram.yaml has this issue too. Actually I was unable to get any of the examples working.

**Comment by tylerlong** [comment] 2016-04-22 02:33
@saharj 

I created an issue for this repo yesterday:  https://github.com/swagger-api/swagger-codegen/issues/2675

I created two because I didn't know what's the root cause of the issue: swagger-codegen or swagger-editor.  Since you closed the one in swagger-editor project, I guess you are sure that root cause is swagger-codegen.

You can close this issue.

**Comment by wing328** [comment] 2016-04-22 02:37
@tylerlong I just tested with petstore_full and petstore_simple, and both work fine in terms of generating C# API client. Do these work for you?

To generate API client or server stub, editor.swagger.io sends a HTTP request to https://generator.swagger.io, which generates the code, so please make sure the connection between your PC/MAC and generator.swagger.io is good.

**Comment by tylerlong** [comment] 2016-04-22 07:43
@wing328 From the original question you can see that I was generating code on my own machine:

```
wget http://repo1.maven.org/maven2/io/swagger/swagger-codegen-cli/2.1.6/swagger-codegen-cli-2.1.6.jar -O swagger-codegen-cli.jar

java -jar swagger-codegen-cli.jar generate -i swagger.yaml -l csharp -o /tmp/test
```

I didn't test petstore because I don't know what's it about. I tested the most famous two: twitter and instagram and neither worked.

**Comment by wing328** [comment] 2016-04-22 07:49
@tylerlong ok. we will add better exception handling for those spec.

**Comment by wing328** [comment] 2016-05-25 09:38
@tylerlong  I tested with both twitter and instagram and both work for me without errors.

**Closed by wing328** 2016-05-25 09:38 UTC
Labels: Bug, Enhancement
