### ISSUE TITLE
recursive model definitions causes crash

### ISSUE THREAD

**Issue by intrz** [swagger-api/swagger-codegen#728] opened 2015-05-07 15:26 UTC
If you have a model with a self reference, the code generator crashes:

```yaml
definitions:
  pet:
    required:
      - id
      - name
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
      tag:
        type: string
      children:
        type: array
        items: 
          $ref: '#/definitions/pet'
```

**Comment by wing328** [comment] 2015-05-07 16:20
Are you suggesting it should throw an exception with a proper error message instead ?

**Comment by intrz** [comment] 2015-05-07 16:34
I'm suggesting it could generate valid code instead. It is not impossible, in my manually implemented client library I have some code like this.

**Comment by wing328** [comment] 2015-05-07 16:43
For the client library you mentioned, may I know what programming language did you use ? I'm not sure if all programming languages support circular references.

**Comment by intrz** [comment] 2015-05-08 08:25
C# and Java. Both have no problems with something like this
public class Pet {
   private Pet pet;
}

**Comment by wing328** [comment] 2015-05-08 09:11
For the models with circular reference, does it work in swagger-ui? Just want to know if other swagger tools already support models with circular reference.

**Comment by intrz** [comment] 2015-05-08 09:23
Yes, and the swagger-editor added support for it a couple months ago.

**Comment by fehguy** [comment] 2015-05-13 13:23
I thought this was fixed, but I believe it's simple to do in [XmlExampleGenerator.java](https://github.com/swagger-api/swagger-codegen/blob/develop_2.0/modules/swagger-codegen/src/main/java/com/wordnik/swagger/codegen/examples/XmlExampleGenerator.java)

**Comment by webron** [comment] 2015-05-22 15:26
Fixed in develop_2.0.

**Closed by webron** 2015-05-22 15:26 UTC
Labels: Bug, P2

**Comment by JohnGalt1717** [comment] 2016-03-08 19:57
The better solution is that the UIs and processors need to handle this properly instead of endlessly looping.

**Comment by wing328** [comment] 2016-03-09 01:56
@JohnGalt1717 are you referring to swagger-ui?

**Comment by JohnGalt1717** [comment] 2016-03-09 13:03
Yes, among others. The problem is there code that doesn't cache entries and just link it back up again instead of just following the path blindly. (And their latest code as the same issue)

**Comment by wing328** [comment] 2016-03-09 13:27
Ok. Please open the issue in https://github.com/swagger-api/swagger-ui instead.

**Comment by JohnGalt1717** [comment] 2016-03-09 13:55
Already done. But I was just making a point that this isn't really an issue here, it's a UI and parsing issue on the other side.
