### ISSUE TITLE
[Swift] snake_case parameter names are not generated properly

### ISSUE THREAD

**Issue by bramley-turner-stride** [swagger-api/swagger-codegen#2181] opened 2016-02-19 06:55 UTC
Running codegen for an API with snake_case parameters doesn't work - the fields are converted to camelCase.

This works correctly for the java client.

eg

```
let nillableParameters: [String:AnyObject?] = [
"taxonSlug": taxonSlug,  //expected: "taxon_slug": taxonSlug
"brandSlugs": brandSlugs //expected: "brand_slugs": brandSlugs
]
```

java:

```
queryParams.addAll(ApiInvoker.parameterToPairs("", "taxon_slug", taxonSlug));
    
queryParams.addAll(ApiInvoker.parameterToPairs("csv", "brand_slugs", brandSlugs));
```

related: #2084 

```
{
   "swagger": "2.0",
   "info": {
      "title": "An API",
      "url": "https://github.com/somewhere"
   },
   "basePath": "/api/",
   "consumes": [
      "application/json"
   ],
   "produces": [
      "application/json"
   ],
   "paths": {
      "/catalogue/browse": {
         "get": {
            "summary": "Browse the store",
            "parameters": [
               {
                  "name": "taxon_slug",
                  "in": "query",
                  "type": "string",
                  "description": "Only show items in this taxon"
               },
               {
                  "name": "brand_slugs",
                  "in": "query",
                  "type": "array",
                  "collectionFormat": "csv",
                  "items": {
                     "type": "string"
                  },
                  "description": "Only show items with these brands"
               }
            ]
         }
      }
   }
}
```

**Comment by wing328** [comment] 2016-02-20 15:35
@bramley-turner-stride thanks for reporting the issue, which can be fixed in https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/swift/api.mustache with the use of `{{baseName}}` instead of `{{paramName}}`.

For example, the `baseName` can be `created-at` while the corresponding `paramName` is `createdAt` to avoid compilation error due to `-` 

Other languages (e.g. PHP) has similar "mapping" to handle the function parameter, e.g. https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/php/api.mustache#L146

Would have cycle to implement the fix?

Ref: https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md

**Comment by Glagnar** [comment] 2016-02-27 14:27
@bramley-turner-stride I do not understand why you want to generate snake_case. The Apple guidelines are to use camelCase:
https://developer.apple.com/library/prerelease/ios/documentation/Swift/Conceptual/Swift_Programming_Language/TheBasics.html

**Comment by wing328** [comment] 2016-02-27 14:52
@Glagnar I think the issue is that the server is expecting a query parameter `taxon_slug` but the Swift API client (which currently does not maintain any mapping between `baseName` and `paramName` in query parameter) is using `taxonSlug` instead, which will be ignore by the server.

That's why I said we need to implement similar mapping between `{{baseName}}` and `{{paramName}}` in Swift API client.

**Comment by wing328** [comment] 2016-02-27 14:53
@Glagnar if you need more direction in contributing a fix for this issue, please let me know.

**Comment by Glagnar** [comment] 2016-02-27 19:25
@wing328 I am impressed. Your suggested changes are exactly what the doctor ordered:
> with the use of {{baseName}} instead of {{paramName}}
Should I make two separate commits, or one with fixes to both issue 2084 and 2262 ?

**Comment by wing328** [comment] 2016-03-02 07:35
@bramley-turner-stride thanks to PR from @Glagnar, please pull the latest and let us know if you still experience the same issue.

**Closed by wing328** 2016-03-02 07:35 UTC
Labels: Bug, Client: Swift
