### ISSUE TITLE
[HTML Rendering] - ExternalDocs not rendered in HTML

### ISSUE THREAD

**Issue by Orkhidion** [swagger-api/swagger-codegen#4861] opened 2017-02-27 16:41 UTC
##### Description

The ExternalDocs is not rendered while generated HTML output.
Maybe I'm using it wrongly, but with the Online Editor it is working but not with swagger-codegen.

Do I need to do something special ?

##### Swagger-codegen version
Version : 2.2.1

##### Swagger declaration file content or url

swagger: '2.0'
info:
  version: 1.0.0
  title: Test API
  description: ''
host: your_instance
basePath: /services/apexrest
schemes:
  - https
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
consumes:
  - application/json
  - text/xml
produces:
  - application/json
  - text/xml
paths:
  /v2.0/testSummary:
    post:
      tags:
        - World
      summary: Test summary
      operationId: testSummary
      externalDocs:
        description: PLop
        url: http://google.com

##### Command line used for generation
java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate -i ../../../../Downloads/swagger.json -l html2 -o test-html

**Comment by aartinagdev** [comment] 2021-05-10 05:09
I am facing a similar issue. I am using openapi version 3.0.0 in YAML specification and tried to export server stubs in html format from Swagger Hub. Could not see External Docs hyperlink in generated html. 

Is there any update to the issue? Were you able to workaround this problem ?

**Comment by HugoMario** [comment] 2024-01-22 16:24
Going to close this issue since I have not been able to reproduce it, in case it's still present, please let me know and I'll work in a fix.

**Closed by HugoMario** 2024-01-22 16:24 UTC
