### ISSUE TITLE
Reserved word causes Java codegen to fail

### ISSUE THREAD

**Issue by hshorter** [swagger-api/swagger-codegen#305] opened 2014-10-09 16:18 UTC
JSON below causes the Java CodeGen to fail with the following exception because of the use of 'switch':

`
java.lang.Exception: reserved word "switch" not allowed
	at com.wordnik.swagger.codegen.BasicJavaGenerator.escapeReservedWord(BasicJavaGenerator.scala:240)
	at com.wordnik.swagger.codegen.language.CodegenConfig.toVarName(CodegenConfig.scala:116)
	at com.wordnik.swagger.codegen.BasicJavaGenerator.toVarName(BasicJavaGenerator.scala:112)
	at com.wordnik.swagger.codegen.Codegen$$anonfun$apiToMap$2.apply(Codegen.scala:166)
	at com.wordnik.swagger.codegen.Codegen$$anonfun$apiToMap$2.apply(Codegen.scala:115)
	at com.wordnik.swagger.codegen.Codegen.apiToMap(Codegen.scala:115)
	at com.wordnik.swagger.codegen.BasicGenerator$$anonfun$prepareApiBundle$2$$anonfun$apply$16.apply(BasicGenerator.scala:345)
	at com.wordnik.swagger.codegen.BasicGenerator$$anonfun$prepareApiBundle$2$$anonfun$apply$16.apply(BasicGenerator.scala:344)
	at scala.collection.TraversableLike$WithFilter$$anonfun$foreach$1.apply(TraversableLike.scala:772)
	at scala.collection.immutable.List.foreach(List.scala:318)
`

```json
{

    "apis": [
        {
            "description": "",
            "operations": [
                {
                    "consumes": [ ],
                    "items": { },
                    "method": "GET",
                    "nickname": "GET",
                    "parameters": [
                        {
                            "allowMultiple": false,
                            "description": "",
                            "name": "domain",
                            "paramType": "path",
                            "required": true,
                            "type": "string"
                        },
                        {
                            "allowMultiple": false,
                            "description": "",
                            "name": "svlan",
                            "paramType": "path",
                            "required": true,
                            "type": "string"
                        }
                    ],
                    "produces": [
                        "application/json",
                        "application/x-json-smile",
                        "application/xml",
                        "text/xml",
                        "application/x-yaml",
                        "text/x-yaml",
                        "text/csv",
                        "application/*+xml",
                        "application/xml",
                        "text/xml"
                    ],
                    "responseMessages": [ ],
                    "summary": "",
                    "type": "ErpsAuditResult"
                }
            ],
            "path": "/Erps/{domain}/{svlan}/Audit"
        },
        {
            "description": "",
            "operations": [
                {
                    "consumes": [ ],
                    "items": { },
                    "method": "GET",
                    "nickname": "GET",
                    "parameters": [
                        {
                            "allowMultiple": false,
                            "description": "",
                            "name": "domain",
                            "paramType": "path",
                            "required": true,
                            "type": "string"
                        },
                        {
                            "allowMultiple": false,
                            "description": "",
                            "name": "svlan",
                            "paramType": "path",
                            "required": true,
                            "type": "string"
                        },
                        {
                            "allowMultiple": false,
                            "description": "",
                            "name": "address",
                            "paramType": "path",
                            "required": true,
                            "type": "string"
                        },
                        {
                            "allowMultiple": false,
                            "description": "",
                            "name": "switch",
                            "paramType": "path",
                            "required": true,
                            "type": "string"
                        }
                    ],
                    "produces": [
                        "application/json",
                        "application/x-json-smile",
                        "application/xml",
                        "text/xml",
                        "application/x-yaml",
                        "text/x-yaml",
                        "text/csv",
                        "application/*+xml",
                        "application/xml",
                        "text/xml"
                    ],
                    "responseMessages": [ ],
                    "summary": "",
                    "type": "ErpsRepairVlanList"
                },
                {
                    "consumes": [
                        "application/json",
                        "application/x-json-smile",
                        "application/xml",
                        "text/xml",
                        "application/x-yaml",
                        "text/x-yaml",
                        "text/csv",
                        "*/*"
                    ],
                    "items": { },
                    "method": "PUT",
                    "nickname": "PUT",
                    "parameters": [
                        {
                            "allowMultiple": false,
                            "description": "",
                            "name": "domain",
                            "paramType": "path",
                            "required": true,
                            "type": "string"
                        },
                        {
                            "allowMultiple": false,
                            "description": "",
                            "name": "svlan",
                            "paramType": "path",
                            "required": true,
                            "type": "string"
                        },
                        {
                            "allowMultiple": false,
                            "description": "",
                            "name": "address",
                            "paramType": "path",
                            "required": true,
                            "type": "string"
                        },
                        {
                            "allowMultiple": false,
                            "description": "",
                            "name": "switch",
                            "paramType": "path",
                            "required": true,
                            "type": "string"
                        },
                        {
                            "allowMultiple": false,
                            "name": "parameter1",
                            "paramType": "body",
                            "required": true,
                            "type": "string"
                        }
                    ],
                    "produces": [ ],
                    "responseMessages": [ ],
                    "summary": "",
                    "type": "void"
                }
            ],
            "path": "/Erps/{domain}/{svlan}/Repair/{address}/{switch}"
        }
    ],
    "apiVersion": "1.0",
    "basePath": "url",
    "consumes": [ ],
    "info": { },
    "models": {
        "ErpsAuditResult": {
            "description": "",
            "id": "ErpsAuditResult",
            "properties": {
                "svlan": {
                    "type": "int",
                    "uniqueItems": false
                },
                "warnings": {
                    "items": {
                        "$ref": "ErpsAuditWarning"
                    },
                    "type": "array",
                    "uniqueItems": false
                },
                "managementDomainName": {
                    "type": "string",
                    "uniqueItems": false
                }
            },
            "required": [ ],
            "subTypes": [ ]
        },
        "ErpsAuditWarning": {
            "description": "",
            "id": "ErpsAuditWarning",
            "properties": {
                "warning": {
                    "type": "string",
                    "uniqueItems": false
                }
            },
            "required": [ ],
            "subTypes": [ ]
        },
        "ErpsRepairVlanList": {
            "description": "",
            "id": "ErpsRepairVlanList",
            "properties": {
                "switchIndex": {
                    "type": "int",
                    "uniqueItems": false
                },
                "svlan": {
                    "type": "int",
                    "uniqueItems": false
                },
                "address": {
                    "type": "string",
                    "uniqueItems": false
                },
                "vlans": {
                    "items": {
                        "type": "int"
                    },
                    "type": "array",
                    "uniqueItems": false
                },
                "managementDomainName": {
                    "type": "string",
                    "uniqueItems": false
                }
            },
            "required": [ ],
            "subTypes": [ ]
        }
    },
    "produces": [ ],
    "resourcePath": "/Erps",
    "swaggerVersion": "1.2"

}
```

**Comment by frodrigo** [comment] 2015-04-01 09:49
We are v2.1.2 and the problem is still here. Need change the target ?
I encountered the with void, it's not just a reserved keyword but also a special meaning as return value.

**Comment by fehguy** [comment] 2015-04-02 04:23
Please try 2.1.3-SNAPSHOT.  I believe it has been addressed there.

**Comment by wing328** [comment] 2015-04-02 11:05
Do you mind showing us what the auto-generated code looks like ?

**Comment by frodrigo** [comment] 2015-04-02 11:10
No generetad code.

$ java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate -i http://127.0.0.1:3000/api/swagger_doc.json -l java -o dir

[...]
java.lang.RuntimeException: void (reserved word) cannot be used as a model name
	at com.wordnik.swagger.codegen.languages.JavaClientCodegen.toModelName(JavaClientCodegen.java:120)
	at com.wordnik.swagger.codegen.languages.JavaClientCodegen.getSwaggerType(JavaClientCodegen.java:161)
	at com.wordnik.swagger.codegen.DefaultCodegen.fromProperty(DefaultCodegen.java:534)
	at com.wordnik.swagger.codegen.DefaultCodegen.fromResponse(DefaultCodegen.java:845)
	at com.wordnik.swagger.codegen.DefaultCodegen.fromOperation(DefaultCodegen.java:709)
	at com.wordnik.swagger.codegen.DefaultGenerator.processOperation(DefaultGenerator.java:305)
	at com.wordnik.swagger.codegen.DefaultGenerator.processPaths(DefaultGenerator.java:277)
	at com.wordnik.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:152)
	at com.wordnik.swagger.codegen.cmd.Generate.run(Generate.java:77)
	at com.wordnik.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:33)

**Comment by wing328** [comment] 2015-04-02 12:39
Agreed void is valid return type in swagger spec 1.2.

My guess is that there may be an issue converting the spec from 1.2 to 2.0 when generating the client

I would suggest you to try generating the client in Ruby or Python to see if there's a model named "Void". If yes, that means likely the conversion from 1.2 to 2.0 treats "void" as an object, not a data type indicating void return.

**Comment by frodrigo** [comment] 2015-04-02 16:14
Ruby is not the right place to look at, since there is no return type nor return.

In Python void is treated as type, but not no void entity are created.
        responseObject = self.apiClient.deserialize(response, 'void')
        return responseObject

In C#, same ugly thing:
               return (void) ApiInvoker.deserialize(response, typeof(void));

**Comment by wing328** [comment] 2015-04-03 01:07
CSharp petstore sample (using swagger spec 2.0) does not have the "void"
issue you found:

https://github.com/swagger-api/swagger-codegen/blob/master/samples/client/petstore/csharp/src/Com/Wordnik/Petstore/Api/PetApi.cs#L137

so my guess is that the issue has to do with conversion from swagger spec
1.2 to 2.0.

**Comment by xhh** [comment] 2015-04-03 07:55
Regarding the issue of treating "void" as model name, the following is what I guess where the problem is:

https://github.com/swagger-api/swagger-parser/blob/master/modules/swagger-compat-spec-parser/src/main/java/io/swagger/parser/SwaggerCompatConverter.java#L365
```java
// default response type
Property responseProperty = propertyFromTypedObject(operation);
if(responseProperty != null) {
  Response response = new Response()
    .description("success")
    .schema(responseProperty); // <===== here
  if(output.getResponses() == null)
    output.defaultResponse(response);
  else
    output.response(200, response);
}
```

https://github.com/swagger-api/swagger-parser/blob/master/modules/swagger-compat-spec-parser/src/main/java/io/swagger/parser/SwaggerCompatConverter.java#L322
```java
if(obj.getRef() != null)
  output = new RefProperty(obj.getRef());
else if(type != null) // <===== type is "void" here
  output = new RefProperty(type);
else
  output = new RefProperty("void");
```

**Comment by xhh** [comment] 2015-04-03 11:25
I've made it work via this PR: swagger-api/swagger-parser#34, please have a look.

**Comment by frodrigo** [comment] 2015-04-03 22:50
I have updated, rebuild all, (the dependency is now <swagger-parser-version>1.0.5-SNAPSHOT</swagger-parser-version>), but the problem is still the same:
java.lang.RuntimeException: void (reserved word) cannot be used as a model name

**Comment by xhh** [comment] 2015-04-04 02:17
the 1.0.5-SNAPSHOT version of swagger-parser does has the issue, it needs to publish a new version for swagger-parser and use that new version in swagger-codegen project

**Comment by fehguy** [comment] 2015-04-04 02:38
Hi, I've just pushed an updated 1.0.5-SNAPSHOT.  Please try again, and apologies for the delay.

**Comment by frodrigo** [comment] 2015-04-04 14:36
It's now OK for me. Thank you.

**Comment by wing328** [comment] 2015-04-23 03:29
@frodrigo do you mind closing this issue given that it's resolved ?

**Comment by webron** [comment] 2015-04-24 16:29
Looks like @frodrigo confirmed already. Closing.

**Closed by webron** 2015-04-24 16:29 UTC

**Comment by frodrigo** [comment] 2015-04-24 21:37
The reserved keyword "void" is now OK. But the others still cause exceptions as reported when this issue was opened.

**Comment by webron** [comment] 2015-04-26 10:09
Without a list it would be difficult to do much about it.

**Comment by frodrigo** [comment] 2015-04-27 13:14
https://docs.oracle.com/javase/tutorial/java/nutsandbolts/_keywords.html

**Comment by wing328** [comment] 2015-04-27 14:04
@frodrigo If I understand it correctly, you would like to use Java reserved keyword (e.g. return) as the model name. Do you mind telling us a bit more about the use case? Can the model be renamed as something else (e.g. ReturnObject) ?

Currently, in Java codegen, we check whether the model name is a reserved keyword and throw an exception if found. If we skip the check, Java codegen can generate the code but it won't compile since Java would complain about using "return" as the class name.

**Comment by frodrigo** [comment] 2015-04-27 14:07
It's not my issue initially. Have personally no more problem since void is OK. Just point you, you may not close this issue just because "void" is now OK.

**Comment by MarcinKwiatkowski1988** [comment] 2015-06-22 13:25
Can you please add also a fix for the return type "Byte" --> java.lang.RuntimeException: byte (reserved word) cannot be used as a model name

**Comment by wing328** [comment] 2015-06-22 14:36
@MarcinKwiatkowski1988 Do you mind sharing the spec with us ?

A model named "Byte" won't compile in Java

**Comment by MarcinKwiatkowski1988** [comment] 2015-06-22 16:02
{"apiVersion":"1.0.0","swaggerVersion":"1.2","basePath":"/pluto/api-docs","resourcePath":"/retrieveperson","apis":[{"path":"/retrieve/{id}","operations":[{"method":"GET","summary":"The API allows to retrieve a person's data","notes":"More notes about this method (rest2 two)","type":"Person","nickname":"retrievePerson","produces":["application/json","application/xml"],"authorizations":{},"parameters":[{"name":"id","description":"ID of Person to fetch","required":true,"type":"string","paramType":"path"}]}]}],"models":{"Person":{"id":"Person","description":"Person resource representation","properties":{"byteField":{"type":"array","description":"ByteField","items":{"type":"byte"}},"name":{"type":"string","description":"Name"},"surname":{"type":"string","description":"Surname"},"phoneNumbers":{"type":"array","description":"List of phone numbers","items":{"$ref":"PhoneNumber"}},"numbers":{"type":"array","items":{"$ref":"PhoneNumber"}}}},"PhoneNumber":{"id":"PhoneNumber","description":"PhoneNumber resource representation","properties":{"prefix":{"type":"string","description":"Country prefix"},"number":{"type":"string","description":"Phone number"}}}}}

**Comment by wing328** [comment] 2015-06-22 16:05
@MarcinKwiatkowski1988 may I know how you obtain the swagger spec file ?

`"type":"byte"` is not valid according to https://github.com/swagger-api/swagger-spec/blob/master/versions/1.2.md#431-primitives

**Comment by MarcinKwiatkowski1988** [comment] 2015-06-23 07:49
I obtained it using swagger's annotations - for the Byte part, using this piece of code:

@ApiModel(value = "Person", description = "Person resource representation")
public class Person {
	@ApiModelProperty(value = "ByteField", dataType = "java.lang.Byte[]")
	private Byte[] byteField;
//...

The whole projects works very well, I just need the codegen to works with reserved word "Byte" to create the client for java

**Comment by wing328** [comment] 2015-06-23 07:57
In your case you want to use `Byte[]` (array of byte) for a property but I'm afraid that's not supported by the spec at the moment. Please refer to https://github.com/swagger-api/swagger-spec/issues/50 for more information

**Comment by MarcinKwiatkowski1988** [comment] 2015-06-23 08:10
So I just need to wait till it will be supported, or I have to figure out how to change my project to not use Byte[] ?

**Comment by wing328** [comment] 2015-06-23 08:18
For `byte[]`, is that actually a file ?

**Comment by MarcinKwiatkowski1988** [comment] 2015-06-23 08:22
I have a java file (Person.java) that has a property of this type: Byte[]; what I'm supposed to do to make it work with codegen, to have a working client generated by swagger-codegen, instead of having the error of "reserved word"?

**Comment by wing328** [comment] 2015-06-23 08:59
What about skipping that property for the time being ? and you manually add it back after the code is generated.

**Comment by MarcinKwiatkowski1988** [comment] 2015-06-23 09:17
That's not an option, since the real project has multiple files with that kind of property; the spec I showed was from a small-simple sample.

**Comment by wing328** [comment] 2015-06-23 10:06
What about a temporary workaround to comment out the [line](https://github.com/swagger-api/swagger-codegen/blob/develop_2.0/modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/JavaClientCodegen.java#L178) that's throwing the exception so that you will still get the code generated (then you can remove the custom model "Byte" to avoid compile error) 

A permanent solution is to wait for the https://github.com/swagger-api/swagger-spec/issues/50 to be resolved.
