### ISSUE TITLE
[Android][Volley] Post requests with json body raise exception Invalid header

### ISSUE THREAD

**Issue by rasuldev** [swagger-api/swagger-codegen#5575] opened 2017-05-05 21:14 UTC
##### Description

Generated by swagger code for android for volley library incorrect handles post requests with json body. When I use api method with json body, I receive an error response with status = 400 and message "Invalid header". The problem is in this code fragment in ApiInvoker class:
```Java
request = new PostRequest(url, headers, contentType, new StringEntity(serialize(body), "UTF-8"), stringRequest, errorListener);
```
By default in my case code
```Java
 new StringEntity(serialize(body), "UTF-8")
```
creates an entity with text/plain content type. That is wrong because server expects application/json content type. 
##### Suggest a Fix
To fix it is sufficient to replace code
```Java
request = new PostRequest(url, headers, contentType, new StringEntity(serialize(body), "UTF-8"), stringRequest, errorListener);
```
 by
```Java
StringEntity entity = new StringEntity(serialize(body),"UTF-8");
entity.setContentType("application/json");
request = new PostRequest(url, headers, contentType, entity, stringRequest, errorListener);
```

**Comment by wing328** [comment] 2017-05-09 08:02
@rasuldev in your spec, have you set a proper `consumes` for the POST JSON body operation?

For Android, you can also use the Java API client: https://github.com/swagger-api/swagger-codegen/wiki/FAQ#how-can-i-generate-an-android-sdk

**Comment by rasuldev** [comment] 2017-05-09 15:49
@wing328 yes, I set application/json for `consumes`. 
![default](https://cloud.githubusercontent.com/assets/4163864/25859383/0c590b12-34e7-11e7-9b85-43b84cd9a57e.png)
Full json spec can be found [here](https://pastebin.com/et9mr2Ss). Mentioned in first post error raises in method `api/account/register`.

**Comment by wing328** [comment] 2017-05-09 16:20
@rasuldev thanks for providing more details. Can you try the Java (okhttp-gson or retrofit2) API client to see if it has similar issue?

**Comment by wing328** [comment] 2017-05-29 06:05
@rasuldev do you need help generating Java API client (okhttp-gson, retrofit2)?

**Comment by wing328** [comment] 2017-07-24 06:56
Closing this as there's no update.

**Closed by wing328** 2017-07-24 06:56 UTC
Labels: Admin: 2.2.3 backlog, Client: Android, Issue: Bug, Need community contribution

**Comment by kfirwolfson** [comment] 2018-01-26 10:11
Having the same issue.
A simple POST that swagger.yaml declares as consumes "application/json" is sent to server with two content types.
From WireShark "copy as plain text" of the http packet:
> POST /api/things HTTP/1.1
> Accept: application/json
> User-Agent: Swagger-Codegen/1.0.0/android
> Content-Type: application/json
> Content-Type: text/plain; charset=UTF-8
> ...

Debugging using Android studio, I see that for POST methods, `HurlStack.addBodyIfExists() `is called, and for POSTs with a body (which most POSTs have), it calls 
```java
connection.addRequestProperty(HEADER_CONTENT_TYPE, request.getBodyContentType());
```

`request.getBodyContentType()` takes the content type from the request's `org.apache.http.HttpEntity`. The instance of the `HttpEntity` is actually a `StringEntity`, which returns a `text/plain` content type by default.

the fix suggested by @rasuldev will possibly work with other servers, but does not work with swagger-generated "jaxrs" server. The reason is that there are 2 lines with `Content-Type: application/json` in the request.

> POST /api/things HTTP/1.1
> Accept: application/json
> User-Agent: Swagger-Codegen/1.0.0/android
> Content-Type: application/json
> Content-Type: application/json
> ...


Sounds like the correct fix is to change `io.swagger.client.request.PostRequest` to include only one content-type. It currently has two: one in field `contentType` and another in field `HttpEntity`.

For now, I locally changed `PostRequest` to return the content-type of contentType when asked for the body's content-type (could have used the suggestion from @rasuldev but had to also change the contentType sent to the PostRequest c'tor to null)

replaced 
```java
public String getBodyContentType() {
    if(entity == null) {
      return null;
    }
    return entity.getContentType().getValue();
  }
...
 public Map<String, String> getHeaders() throws AuthFailureError {
    Map<String, String> headers = super.getHeaders();
    if (headers == null || headers.equals(Collections.emptyMap())) {
        headers = new HashMap<String, String>();
    }
    if (apiHeaders != null && !apiHeaders.equals(Collections.emptyMap())) {
        headers.putAll(apiHeaders);
    }
    if(contentType != null) {
        headers.put("Content-Type", contentType);
    }

    return headers;
  }
```

with:
```java
public String getBodyContentType() {
    if (contentType != null) {
      return contentType;
    }
    if(entity == null) {
      return null;
    }
    return entity.getContentType().getValue();
  }
...
 public Map<String, String> getHeaders() throws AuthFailureError {
    Map<String, String> headers = super.getHeaders();
    if (headers == null || headers.equals(Collections.emptyMap())) {
        headers = new HashMap<String, String>();
    }
    if (apiHeaders != null && !apiHeaders.equals(Collections.emptyMap())) {
        headers.putAll(apiHeaders);
    }
    if((entity == null) && (contentType != null)) {
        headers.put("Content-Type", contentType);
    }

    return headers;
  }
```

and now it works :)

> POST /api/things HTTP/1.1
> Accept: application/json
> User-Agent: Swagger-Codegen/1.0.0/android
> Content-Type: application/json
> ...

and getting `HTTP 200`

**Comment by AliakseiT** [comment] 2018-03-02 13:38
@kfirwolfson description is precise. @wing328 can we re-open?

The problem is in [this `StringEntity` constructor](https://github.com/Jean-Emile/org.apache.httpclient/blob/master/src/main/java/org/apache/http/entity/StringEntity.java#L127), where for `request = new PostRequest(url, headers, contentType, new StringEntity(serialize(body), "UTF-8"), stringRequest, errorListener);` `ContentType.TEXT_PLAIN.getMimeType()` is enforced. And then HurlStack allows two `ContentType` headers to be present.

**Comment by willi1s** [comment] 2020-04-22 12:11
I have hit this same problem. I'm using an IIS server and having two `Content-Type` headers throws a failure.

It would be great if this issue could be reopened and the the generated code updated so I don't have to modify it after every codegen.
