### ISSUE TITLE
Invalid dotnet core code is generated for enums from Swaggerhub

### ISSUE THREAD

**Issue by meerdekens** [swagger-api/swagger-codegen#10218] opened 2020-04-30 14:49 UTC
#9786 ### Description

When defining an enum as a separate components/schemas/EnumType and exporting to dotnet core code, the enum is exported properly as a separate file and class in dotnet (which is fine), but apart from this, a second enum definition is added inline where it's used, which contains undefined variables (resulting in compilation errors)

 
Example: EWithdrawProvider enum used in type WithdrawLimitArguments
 

**EWithdrawProvider.cs:**

       [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum EWithdrawProvider
        {
            /// <summary>
            /// Enum BankAccountEnum for bankAccount
            /// </summary>
            [EnumMember(Value = "bankAccount")]
            BankAccountEnum = 0,
            /// <summary>
            /// Enum CasinoEnum for casino
            /// </summary>
            [EnumMember(Value = "casino")]
            CasinoEnum = 1,
            /// <summary>
            /// Enum SkrillEnum for skrill
            /// </summary>
            [EnumMember(Value = "skrill")]
            SkrillEnum = 2,
            /// <summary>
            /// Enum NetellerEnum for neteller
            /// </summary>
            [EnumMember(Value = "neteller")]
            NetellerEnum = 3,
            /// <summary>
            /// Enum PaypalEnum for paypal
            /// </summary>
            [EnumMember(Value = "paypal")]
            PaypalEnum = 4        }
}

**WithdrawLimitArguments.cs:**

    [DataContract]
    public partial class WithdrawLimitArguments : IEquatable<WithdrawLimitArguments>
    { 
        /// <summary>
        /// Gets or Sets Type
        /// </summary>
        
        public enum EWithdrawLimitType
        {
            /// <summary>
            /// Enum WithdrawalEnum for withdrawal
            /// </summary>
            
            WithdrawalEnum = withdrawal,
            /// <summary>
            /// Enum DepositEnum for deposit
            /// </summary>
            
            DepositEnum = deposit        }

        /// <summary>
        /// Gets or Sets Type
        /// </summary>
        [Required]
        [DataMember(Name="type")]
        public EWithdrawLimitType? Type { get; set; }

        /// <summary>
        /// Gets or Sets Provider
        /// </summary>
        
        public enum EWithdrawProvider
        {
            /// <summary>
            /// Enum BankAccountEnum for bankAccount
            /// </summary>
            
            BankAccountEnum = bankAccount,
            /// <summary>
            /// Enum CasinoEnum for casino
            /// </summary>
            
            CasinoEnum = casino,
            /// <summary>
            /// Enum SkrillEnum for skrill
            /// </summary>
            
            SkrillEnum = skrill,
            /// <summary>
            /// Enum NetellerEnum for neteller
            /// </summary>
            
            NetellerEnum = neteller,
            /// <summary>
            /// Enum PaypalEnum for paypal
            /// </summary>
            
            PaypalEnum = paypal        }

        /// <summary>
        /// Gets or Sets Provider
        /// </summary>
        [Required]
        [DataMember(Name="provider")]
        public EWithdrawProvider? Provider { get; set; }
...

##### Swagger-codegen version

3.0.19

##### Swagger declaration file content or url

```yaml
    WithdrawLimitArguments:
      required:
      - amount
      - provider
      - subtype
      - type
      type: object
      properties:
        type:
          $ref: '#/components/schemas/EWithdrawLimitType'
        provider:
          $ref: '#/components/schemas/EWithdrawProvider'
        subtype:
          $ref: '#/components/schemas/EWithdrawLimitSubtype'
        amount:
          type: number
    EWithdrawProvider:
      type: string
      enum:
      - bankAccount
      - casino
      - skrill
      - neteller
      - paypal
```

##### Command line used for generation

SwaggerHub Online...

##### Steps to reproduce

generate in aspnet core 3.1

##### Suggest a fix/enhancement

Remove the excessive enum definitions in the inline class file where they are used...

**Comment by Smootium** [comment] 2020-05-13 17:55
Hi, just wondering if  #10059 is related (fixed, closed by @HugoMario )?

**Comment by HugoMario** [comment] 2020-05-13 18:56
that's correct, this issue has been fixed by [swagger-codegen-generators#657](https://github.com/swagger-api/swagger-codegen-generators/pull/657)

I tested locally and i couldnt get the issue, changes can be got on next release.

**Comment by meerdekens** [comment] 2020-06-09 14:39
Hi @HugoMario,

Your fix on this was finally included in a new release of the hosted SwaggerHub service, so I was able to test it with our project, but it doesn't seem to be fixing my issue.

I know I have very little insight on the Codegen internals and I don't expect you to explain it in details, but when looking into the change you did for this (https://github.com/swagger-api/swagger-codegen-generators/pull/657/commits/71d21e35e7f00ea3f7b02100a57320b011a82aa0), I understand you prevented the execution of the partial enumClass in case the enum type property is a complexType.
But I'm wondering why you would want to include some (non-compiling) version of the enum definition inline in the model as they are being generated as separate types/files anyway.
Even more important, could you indicate when a property is considered a complex type so the changes you made fix the issue we're having.

Thanks a lot!!

Cheers, Maarten

Cheers, Maarten

**Comment by HugoMario** [comment] 2020-06-19 04:07
hey @meerdekens , sorry for delay response. `complexType` is just a non language type, such as custom class. Since enum is generated in its own file and as a type. It's identified as complex type.

**Comment by HugoMario** [comment] 2020-06-19 06:59
@meerdekens 

can you please share how you reproduce this issue please?
I'm trying to reproduce it using this definition:
```yaml
  schemas:
    WithdrawLimitArguments:
      required:
      - amount
      - provider
      - subtype
      - type
      type: object
      properties:
        provider:
          $ref: '#/components/schemas/EWithdrawProvider'
        subtype:
          $ref: '#/components/schemas/Manufacturer'
        amount:
          type: number
    EWithdrawProvider:
      type: string
      enum:
      - bankAccount
      - casino
      - skrill
      - neteller
      - paypal
    InventoryItem:
      type: array
      items:
        $ref: '#/components/schemas/Manufacturer'
        description: An inventory item
    Manufacturer:
      type: object
      required:
        - name
      properties:
        name:
          type: string

```

but i got not errors on it.

**Comment by meerdekens** [comment] 2020-07-17 09:26
Hi @HugoMario,
Thanks for looking into this and my apologies for this late reply. It seems, I'm missing out on some notifications...

As I might have mentioned above, we're not using codegen directly, but rather are using it indirectly via the SwaggerHub online service. Although their support service confirmed me they updated the version of codegen last month to 3.0.20, latest stable, I didn't see this fix make any difference. So to make sure, I ran the codegen locally myself today on the same swagger.json definition, which gives me a different (better) result compared to swaggerhub.
So, this is obviously something I need to take up again with them as it seems the version codegen they are running is not what they documented.

Thanks, Maarten

**Closed** 2020-07-17 09:57 UTC
