### ISSUE TITLE
Models with nested containers do not correctly generate for java clients.

### ISSUE THREAD

**Issue by Treydone** [swagger-api/swagger-codegen#453] opened 2015-02-25 10:39 UTC
Here is the thing. I have a json spec with a field "data" in the form of "map\<string, list\<Pet\>\>":
```js

                "data": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "array",
                        "items": {
                            "$ref": "#/definitions/Pet"
                        }
                    }
                }
```

But the generated Java model contains a property like:
private Map\<String, List\<Pet\>\> data = new HashMap\<String, List\>() ;

which doesn't compile because it has to be:
private Map\<String, List<Pet_>\> data = new HashMap\<String, List\<Pet\>\>() ;

I think in the method toDefaultValue in DefaultCodegen, you should use getTypeDeclaration instead of getSwaggerType.

**Comment by webron** [comment] 2015-02-25 10:51
@Treydone - looks like some of the information in your question got messed up. Can you please go over it again and check it?

**Comment by fehguy** [comment] 2015-02-25 15:03
Maps are tricky in the client but I think they're supported.  I do see that the return type for the `getInventory` operation in the petstore sample has the proper response.

Let's try to get a test to demonstrate this.

**Comment by fehguy** [comment] 2015-02-25 15:14
Looks like this property is well tested:

https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/test/scala/Java/JavaModelTest.scala#L99-L125

And the declaration looks right to me:
```
  private {{{datatype}}} {{name}} = {{{defaultValue}}};
```
So I'm not sure how this is happening.  Try to share some more of your code, and ensure you're on 2.1.2-M1 for codegen.

**Comment by fehguy** [comment] 2015-02-25 15:35
OK I've isolated this to "map of lists".  The previous test is not covering the list in the map--I've added a test to demostrate the issue.  Will address this in M2.

**Comment by Treydone** [comment] 2015-02-26 08:56
Ok thanks!

**Comment by komo81** [comment] 2015-03-06 10:22
Hi, maybe I have similar issue. 

In my api model I have:
`
@JsonProperty("repriceItems")
private List<RepriceItem> items;
`
swagger (I think correct):
`
"repriceItems":
               {
                   "items":
                   {
                       "type": "RepriceItem"
                   },
                   "required": false,
                   "type": "List"
               }
`

But when I run codegen for Java or Android, I get:
`private List repriceItems = null;`
instead of 
`private List<RepriceItem> repriceItems = null;`

I'm using codegen v 2.1.2-M1.

Is it a bug or do I something wrong?

**Comment by Richou** [comment] 2015-08-12 12:07
Hello,

I have the same issue, I use the following dependency :

```xml
<dependency>
    <groupId>io.swagger</groupId>
    <artifactId>swagger-codegen</artifactId>
    <version>2.1.2</version>
</dependency>
```

Is it normal ?

Thx.
Regards.

**Comment by fehguy** [comment] 2015-08-14 03:19
@Richou the most recent codegen version is `2.1.3-SNAPSHOT`.  Please do any of your testing against that version, which is currently in the `develop_2.0` branch.

**Comment by mach-kernel** [comment] 2015-08-24 16:37
+1, nested HashMap does not include parent abstract container's types.

**Comment by mach-kernel** [comment] 2015-08-24 17:00
This can be fixed, as above, by using `getTypeDeclaration()` instead as it will check if the type mappings contain a key or not. Modify the function as follows in `DefaultCodegen.java`:

```java
        } else if (p instanceof ArrayProperty) {
            ArrayProperty ap = (ArrayProperty) p;
            String inner = getTypeDeclaration(ap.getItems()); // change to getTypeDeclaration
            return "new ArrayList<" + inner + ">() ";
        } 
```

Build executes fine with `mvn clean && mvn package`

**Comment by samskiter** [comment] 2015-11-06 23:03
I'd like to add that maps don't generate well for this case either:

```
{
    "id": "sitesGETresponse.schema.json#",
    "$schema": "http://json-schema.org/draft-04/schema#",
    "title": "Site list",
    "description": "Response to site list request",
    "type": "object",
    "properties": {
        "title": {
            "type": "string"
        }
    }, 
    "additionalProperties": {
        "type": "object",
        "properties": {
            "title": {
                "type": "string"
            },
            "count": {
                "type": "integer"
            },
            "uuid": {
                "type": "string"
            }
        },
        "required": ["uuid"]
    }
}
```

I get out of that java looking like: 

```
/**
 * Response to site list request
 **/
@ApiModel(description = "Response to site list request")
public class Sites extends HashMap<String, Object> {
  
  @SerializedName("title")
  private String title = null;

  
  /**
   **/
  @ApiModelProperty(value = "")
  public String getTitle() {
    return title;
  }
  public void setTitle(String title) {
    this.title = title;
  }

  

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class Sites {\n");
    sb.append("  " + super.toString()).append("\n");
    sb.append("  title: ").append(title).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
```

The hashmap has been made but just holds objects

Should an inner class or something be made here?

Not sure if it's also worth mentioning here that I thinkg additionalProperties breaks on Objective-C too because the generated class inherits from NSMutableDictionary, and it needs to inherit from JSONModel (indirectly). So the class can no longer be user for deserialisation from JSON as far as I can tell. It might need to implement initWithDictionary to get away with this...

**Comment by samskiter** [comment] 2015-11-06 23:25
(might be a duplicate of https://github.com/swagger-api/swagger-codegen/issues/1470 ) But I think the ObjC bug might still stand

**Comment by mach-kernel** [comment] 2015-11-07 16:54
@samskiter try my fork, #1441, I was able to get stuff to work properly but it was a few weeks ago and I forgot what I did :cry:

**Comment by xhh** [comment] 2016-01-25 03:03
Just tested it with Java models and got this which compiles fine:

```java
private Map<String, List<Pet>> data = new HashMap<String, List<Pet>>();
```

So the issue has been addressed.

**Closed** 2016-01-25 03:06 UTC
Labels: Client: Java
