### ISSUE TITLE
RuntimeException: missing OpenApi input!

### ISSUE THREAD

**Issue by axelvuylsteke** [swagger-api/swagger-codegen#10157] opened 2020-04-06 13:16 UTC
Missing OpenApi input!
In version 3.0.18 this was still working. In 3.0.19 not anymore. I cannot give you the .yml file due to professional reasons. However I can give you the stacktrace.
Last line to write to file is:
[INFO] writing file /Users/axelixx/Documents/JohnsonAndJohnson/C4T2.0/public_apis_testing/swagger-utils/target/generated-sources/swagger/.swagger-codegen/VERSION

##### Swagger-codegen version

com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'openapi': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
 at [Source: (StringReader); line: 1, column: 8]
    at com.fasterxml.jackson.core.JsonParser._constructError (JsonParser.java:1840)
    at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError (ParserMinimalBase.java:722)
    at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._reportInvalidToken (ReaderBasedJsonParser.java:2867)
    at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddValue (ReaderBasedJsonParser.java:1913)
    at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken (ReaderBasedJsonParser.java:772)
    at com.fasterxml.jackson.databind.ObjectMapper._readTreeAndClose (ObjectMapper.java:4247)
    at com.fasterxml.jackson.databind.ObjectMapper.readTree (ObjectMapper.java:2720)
    at io.swagger.parser.SwaggerCompatConverter.readResourceListing (SwaggerCompatConverter.java:210)
    at io.swagger.parser.SwaggerCompatConverter.read (SwaggerCompatConverter.java:123)
    at io.swagger.parser.SwaggerCompatConverter.readWithInfo (SwaggerCompatConverter.java:94)
    at io.swagger.parser.SwaggerParser.readWithInfo (SwaggerParser.java:42)
    at io.swagger.v3.parser.converter.SwaggerConverter.readLocation (SwaggerConverter.java:89)
    at io.swagger.parser.OpenAPIParser.readLocation (OpenAPIParser.java:16)
    at io.swagger.codegen.v3.config.CodegenConfigurator.toClientOptInput (CodegenConfigurator.java:503)
    at io.swagger.codegen.v3.maven.plugin.CodeGenMojo.execute (CodeGenMojo.java:525)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:567)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
[ERROR] 
java.lang.RuntimeException: missing OpenAPI input!
    at io.swagger.codegen.v3.DefaultGenerator.generate (DefaultGenerator.java:768)
    at io.swagger.codegen.v3.maven.plugin.CodeGenMojo.execute (CodeGenMojo.java:547)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:567)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)

**Comment by frantuma** [comment] 2020-04-14 14:50
From what can be inferred from the logs, this can be possible caused by an invalid OpenApi 3.x spec, but it's hard to say without at least a test spec reproducing the error, and the plugin configuration

**Comment by radarsh** [comment] 2020-05-21 11:54
I'm getting the same error when trying to use one of your [example OpenAPI specs](https://swagger.io/docs/specification/basic-structure/).

```yml
openapi: 3.0.0
info:
  title: Sample API
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 0.1.9
servers:
  - url: http://api.example.com/v1
    description: Optional server description, e.g. Main (production) server
  - url: http://staging-api.example.com
    description: Optional server description, e.g. Internal staging server for testing
paths:
  /users:
    get:
      summary: Returns a list of users.
      description: Optional extended description in CommonMark or HTML.
      responses:
        '200':    # status code
          description: A JSON array of user names
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string
```

**Comment by radarsh** [comment] 2020-05-21 12:58
Actually ignore my previous comment. The reason for this is that previous version of codegen used to expect a file path in the `inputSpec` property of `CodegenConfigurator` whereas now it expects the contents of the file. After supplying the file contents, I am able to generate codegen without issues.

Perhaps OP faced the same problem.

**Comment by Grandolf49** [comment] 2020-08-01 15:40
Hi @axelvuylsteke  Even I am facing the exact same issue. My spec file uses OpenAPI version 3.0.3. Version 3.0.18 seems to work properly but I get the same error if I use 3.0.19, 3.0.20, 3.0.21 😢

Were you able to locate why it throws this error?

**Comment by omnibrain** [comment] 2020-09-02 09:32
+1 Facing the same issue. 3.0.18 works like a charm but any version after that doesn't work anymore ("missing OpenApi input!")

Here's the schema I used: https://gist.github.com/omnibrain/450f639f2475c7b01369d4d66383154c

The command I ran:

```bash
# works perfectly with swagger-codegen@3.0.18 but not with swagger-codegen@3.0.19 or later
swagger-codegen generate -i ./schema.json -l typescript-angular -o frontend/build/swagger/
```

**Comment by Grandolf49** [comment] 2020-09-02 09:37
> +1 Facing the same issue. 3.0.18 works like a charm but any version after that doesn't work anymore ("missing OpenApi input!")
> 
> Here's the schema I used: https://gist.github.com/omnibrain/450f639f2475c7b01369d4d66383154c
> 
> The command I ran:
> 
> ```shell
> # works perfectly with swagger-codegen@3.0.18 but not with swagger-codegen@3.0.19 or later
> swagger-codegen generate -i ./schema.json -l typescript-angular -o frontend/build/swagger/
> ```

Hey @omnibrain , I resolved my issue by generating a valid OpenAPI File.
I tested your API File with [Swagger Validator](https://validator.swagger.io/) and it's saying that it is invalid. Here is the response for your OpenAPI file
```
- "attribute paths.'/api/portfoliolistheaders/{pfListHdrLnr}/filtervalues'(get).parameters.[entities].schemas.default\
  \ is not of type `array`"
- "attribute info.version is missing"
- "attribute paths.'/api/userdata/{key}'. Declared path parameter key needs to be\
  \ defined as a path parameter in path or operation level"
```

Once you fix these issues with OpenAPI File, you'll be able to use this OpenAPI file with Swagger versions > `3.0.18`. In my case `3.0.21` is working great too

**Comment by omnibrain** [comment] 2020-09-02 11:14
@Grandolf49 Awesome, you are totally right! After fixing *some* of the errors it works perfectly. Looks like this error caused the exception:

```
"attribute paths.'/api/userdata/{key}'. Declared path parameter key needs to be\
  \ defined as a path parameter in path or operation level"
```

.. The other errors don't seem to break the code generation.

**Comment by Grandolf49** [comment] 2020-09-02 11:18
@omnibrain I'm glad the solution worked!

**Comment by pontello** [comment] 2020-11-27 15:47
`com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'openapi': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')`

It looks like this issue happens only if you use codegen on **Windows** starting from version **3.0.19**.

**Comment by dtoch** [comment] 2020-12-15 17:19
I just noticed I created an issue yesterday which #10823 which seems to be related or a duplicate of this one : I also had : 

com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'openapi': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')

when defining a servers url section in the OpenAPI 3.x YAML definition.

**Comment by srl295** [comment] 2021-02-10 16:55
the example .yml at https://github.com/swagger-api/swagger-codegen/issues/10521#issuecomment-776218357 passes the swagger validator, but still gives "Unrecognized token 'openapi'"

**Comment by srl295** [comment] 2021-02-10 17:32
Mac. 
- swagger-codegen@3.0.24 from homebrew works:

```shell
swagger-codegen generate -l python-flask -i ./modules/swagger-generator/target/swagger-ui-master/docs/samples/webpack-getting-started/src/swagger-config.yaml
```

however, running that same file from current HEAD fails with the above error:


```shell
$ mvn clean package #*
$ java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate -l python-flask -o /tmp/apitest/ -i ./modules/swagger-generator/target/swagger-ui-master/docs/samples/webpack-getting-started/src/swagger-config.yaml
[main] INFO io.swagger.parser.Swagger20Parser - reading from ./modules/swagger-generator/target/swagger-ui-master/docs/samples/webpack-getting-started/src/swagger-config.yaml
[main] INFO io.swagger.parser.Swagger20Parser - reading from ./modules/swagger-generator/target/swagger-ui-master/docs/samples/webpack-getting-started/src/swagger-config.yaml
[main] ERROR io.swagger.parser.SwaggerCompatConverter - failed to read resource listing
com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'openapi': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
 at [Source: (String)"openapi: "3.0.0"
```

*though I did get a test failure, will investigate.

**Comment by srl295** [comment] 2021-02-10 18:14
Workaround: I found that openapi-generator@5.0.1 works fine, so I've switched to that.

**Comment by mohan519** [comment] 2021-03-10 18:07
@srl295 you mean openapi-generator-maven-plugin (version 5.0.1) ?

**Comment by dragouf** [comment] 2021-09-02 13:16
for information. I had the same problem and after I added a complete url and not just a path to "servers" property in the json file I was able to make it works.

`{
  "openapi": "3.0.1",
  "info": {
    "title": "Great.Api",
    "version": "v1"
  },
  "servers": [
    {
      "url": "/GreatApi/"
    }
  ], ...`

to 

`{
  "openapi": "3.0.1",
  "info": {
    "title": "Great.Api",
    "version": "v1"
  },
  "servers": [
    {
      "url": "https://www.exemple.com/GreatApi/"
    }
  ], ...`

**Comment by muka** [comment] 2022-01-16 10:26
Fails with similar error on GH API `next` https://github.com/github/rest-api-description/tree/main/descriptions-next/ghes-3.3. Thanks

**Comment by HugoMario** [comment] 2022-03-11 15:50
This issue has been fixed by https://github.com/swagger-api/swagger-codegen/pull/10886 from `3.0.22` version

**Closed** 2022-03-12 18:56 UTC
