### ISSUE TITLE
[JAXRS-CXF] Generated interfaces ignore query params default value

### ISSUE THREAD

**Issue by MatanRubin** [swagger-api/swagger-codegen#4776] opened 2017-02-12 12:30 UTC
##### Description
Using JAXRS-CXF generator with latest master 2.2.2-SNAPSHOT.
If a query param has a defined default value in the swagger definition file, the generated interface should respect that, i.e. add a `@DefaultValue(...)` annotation to the method signature. 
Currently, it does not respect the default value.

For example, using the following swagger definition:

```yaml
---                                                                             
swagger: "2.0"                                                                  
info:                                                                           
  version: "1.0"                                                                
host: "localhost:8080"                                                          
basePath: "/"                                                                   
tags:                                                                           
- name: "Example"                                                               
schemes:                                                                        
- "http"                                                                        
paths:                                                                          
  /example:                                                                     
    get:                                                                        
      tags:                                                                     
      - "Example"                                                               
      summary: "Example"                                                        
      description: ""                                                           
      operationId: "getExample"                                                 
      produces:                                                                 
      - "application/json"                                                      
      parameters:                                                               
      - name: "season"                                                          
        in: "query"                                                             
        required: false                                                         
        type: "string"                                                          
        default: "spring"                                                       
        enum:                                                                   
        - "spring"                                                              
        - "autumn"                                                              
        - "winter"                                                              
        - "summer"                                                              
      responses:                                                                
        200:                                                                    
          description: "successful operation"   
```

The generated interface would look like this:

```yaml
@GET
@Path("/example")
@Produces({ "application/json" })
@ApiOperation(value = "Example", tags={ "Example" })
public void getExample(@QueryParam("season") String season);
```

When the expected result should be:

```yaml
@GET
@Path("/example")
@Produces({ "application/json" })
@ApiOperation(value = "Example", tags={ "Example" })
public void getExample(@QueryParam("season") @DefaultValue("spring") String season);
```

##### Related issues
This is a similar issue, in node.js: https://github.com/swagger-api/swagger-codegen/issues/1892

##### Suggest a Fix
I'll try fixing this myself and submit a PR. Opening this issue for posterity.

**Comment by jfiala** [comment] 2017-03-05 20:19
Please see also #4927, the problem seems to be caused by another component outside swagger-codegen.

**Comment by wing328** [comment] 2017-05-29 05:38
Closed via https://github.com/swagger-api/swagger-codegen/issues/4778

**Closed by wing328** 2017-05-29 05:38 UTC
Labels: Enhancement: General, Server: Java
