### ISSUE TITLE
Generating servercode from http://editor.swagger.io differs from http://generator.swagger.io

### ISSUE THREAD

**Issue by albert-visser** [swagger-api/swagger-codegen#5315] opened 2017-04-04 09:06 UTC
##### Description

I'm getting different generated servercode from http://editor.swagger.io and http://generator.swagger.io
The first will generate classes that inherit when using allOf, http://generator.swagger.io won't.

##### Swagger-codegen version

2.2.2

##### Swagger declaration file content or url

https://gist.github.com/albert-visser/498345f062b64026941d0c7c3d81d7ac

##### Steps to reproduce

**Using http://editor.swagger.io**
1) Goto http://editor.swagger.io
2) File --> import json --> content of [gist](https://gist.githubusercontent.com/albert-visser/e3340fa6f03a929441b6d65f424924c7/raw/dc6a0443aa9f453088f2c69365a3ad60b1681dd7/swagger)
3) Generate server -> aspnetcore or spring

Result: zip file with an event class 
Spring: `public class Event extends EventPost  {`
Aspnetcore: `public partial class Event : EventPost,  IEquatable<Event>`

**Using http://generator.swagger.io**
1) Goto http://generator.swagger.io
2) Server --> Post --> aspnetcore or spring with following 
```
{
  "spec": {},
  "options": {},
  "swaggerUrl": "https://gist.githubusercontent.com/albert-visser/e3340fa6f03a929441b6d65f424924c7/raw/dc6a0443aa9f453088f2c69365a3ad60b1681dd7/swagger"
}
```
3) Download zipfile
Result: zip file with an event class 
Spring: `public class Event   {`
Aspnetcore: `public partial class Event :  IEquatable<Event>`

This is wrong, classes from http://generator.swagger.io should inherit EventPost.

**Using swagger-codegen-cli-2.2.2**
1) Using the cli the result is same as http://generator.swagger.io
`java -jar swagger-codegen-cli-2.2.2.jar generate -i https://gist.githubusercontent.com/albert-visser/e3340fa6f03a929441b6d65f424924c7/raw/dc6a0443aa9f453088f2c69365a3ad60b1681dd7/swagger -l aspnetcore -o .\output`

Result: Same as http://generator.swagger.io

##### Related issues

https://github.com/swagger-api/swagger-codegen/issues/2096
https://github.com/swagger-api/swagger-codegen/issues/3544

##### Suggest a Fix

I've checked what http://editor.swagger.io is doing different, it is actually using http://generator.swagger.io for generation. But instead of [posting a link](https://gist.github.com/albert-visser/a2d894fd55865b73f0382b8d53a3ad08) it will [include swagger in the body](https://gist.github.com/albert-visser/50c449e8adb9b87ba62e50454341af43).

**Comment by wing328** [comment] 2017-04-05 09:53
@albert-visser they should be the same as you've pointed out https://editor.swagger.io is using https://generator.swagger.io behind the scene. I've no clue at the moment why the issue is happening.

**Comment by wing328** [comment] 2017-06-05 18:04
@albert-visser you may want to run your own local generator.swagger.io as it's a sub-module in the swagger codegen project: https://github.com/swagger-api/swagger-codegen/tree/master/modules/swagger-generator so that you've complete control of which version of Swagger generator to use.

**Comment by wing328** [comment] 2017-06-05 18:05
Closing this for the time being. If you want this issue to be reopened, please let me know.

**Closed by wing328** 2017-06-05 18:05 UTC
Labels: General: Question, Swagger-Generator

**Comment by minchao** [comment] 2017-08-23 14:16
There are same problem with the generated client code, but I think this is the editor's problem.

**Comment by wing328** [comment] 2017-08-24 02:47
@minchao you may want to use the SNAPSHOT version to enjoy the enhancements, bug fixes from the latest master: https://github.com/swagger-api/swagger-codegen#compatibility

**Comment by minchao** [comment] 2017-09-12 01:57
@wing328 This issue has been fixed by https://github.com/swagger-api/swagger-editor/issues/1472

**Comment by wing328** [comment] 2017-09-12 03:22
@minchao thanks for the update 👍
