### ISSUE TITLE
Build fails after commit d172de2

### ISSUE THREAD

**Issue by artem-dudarev** [swagger-api/swagger-codegen#3047] opened 2016-06-04 17:15 UTC
I cannot build the codegen package with current source code (34fed26).
The **mvn clean package** command fails while running the TestSuite:
```
Tests run: 501, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 15.279 sec <<< FAILURE! - in TestSuite
evaluate(io.swagger.codegen.ignore.CodegenIgnoreProcessorTest)  Time elapsed: 0.012 sec  <<< FAILURE!
java.lang.AssertionError: A file when non-matching should allow. expected [true] but found [false]
        at io.swagger.codegen.ignore.CodegenIgnoreProcessorTest.evaluate(CodegenIgnoreProcessorTest.java:91)
```
Using the **git bisect** I discovered the first failing commit: d172de2. Before this commit the **mvn clean package** command completes successfully.

```
mvn --version
Apache Maven 3.3.3 (7994120775791599e205a5524ec3e0dfe41d4a06; 2015-04-22T13:57:37+02:00)
Maven home: C:\Tools\apache-maven-3.3.3\bin\..
Java version: 1.8.0_60, vendor: Oracle Corporation
Java home: C:\Program Files\Java\jdk1.8.0_60\jre
Default locale: en_US, platform encoding: Cp1251
OS name: "windows 10", version: "10.0", arch: "amd64", family: "dos"

```

**Comment by wing328** [comment] 2016-06-05 04:03
@artem-dudarev please use `mvn clean package -DskipTests` while we look into this issue in the Windows platform.

**Comment by LightySnake** [comment] 2016-06-06 14:30
Maybe is related to the same issues https://github.com/swagger-api/swagger-codegen/issues/3026

**Comment by wing328** [comment] 2016-06-06 14:42
Closing this one as it's duplicated with #3026

**Comment by wing328** [comment] 2016-06-06 14:44
@jimschubert I wonder if you can take a look when you've time. The issue seems to be platform (Windows) specified.

**Comment by jimschubert** [comment] 2016-06-06 14:49
I can take a look later today. I don't have access to Windows 10, but I have a Windows 8.1 VM. It's weird that only that test is failing and only on Windows.

**Comment by ePaul** [comment] 2016-06-06 18:17
This is the test line which breaks (from the output):

                new CodegenIgnoreProcessorTest("Build.sh", "build.sh", "A file when non-matching should allow.").allowed(),

I.e. the file `Build.sh` is created (upper-case `B`), and the ignore-file says to ignore `build.sh` (in lower case).

Windows by default has a case-insensitive file system (or at least this was the case several years ago), which makes it harder to write code to actually distinguish between Build.sh and build.sh.

I would guess that a PathMatcher from `"glob:build.sh"` (in FileRule.java) will also match `Build.sh` on Windows. (I also don't have a Windows on hand. I have one at home, but it is on a partition I never used, and has no development environment installed.)

Depending on what is wanted here, I guess one could either use a custom matcher (which matches case-insensitively on all systems – with some implementation work or using another library) or remove that test (or ignore it on Windows).

**Comment by jimschubert** [comment] 2016-06-06 18:55
I think ignore on Windows would be best. If have to look into the pattern API to see if it supports case sensitivity.

**Comment by jimschubert** [comment] 2016-06-07 01:29
I opted to skip the test on Windows. If someone has access to a Windows 10 machine, would you mind testing the change?

**Comment by wing328** [comment] 2016-06-07 06:39
@artem-dudarev I've merged the PR by @jimschubert into master. Please pull the latest to give it a try.

**Comment by LightySnake** [comment] 2016-06-07 07:02
On my home PC:
`Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T17:41:47+01:00)
Maven home: C:\Program Files\Maven\bin\..
Java version: 1.8.0_92, vendor: Oracle Corporation
Java home: C:\Program Files\Java\jdk1.8.0_92\jre
Default locale: it_IT, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "dos"`

With commit 127bac4 i get this error:

`Tests run: 502, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 9.872 sec <<< FAILURE! - in TestSuite
testSkipOverwrite(io.swagger.codegen.DefaultGeneratorTest)  Time elapsed: 0.479 sec  <<< FAILURE!
java.lang.RuntimeException: Could not generate supporting file 'SupportingFile:
        templateFile: gradle-wrapper.jar
        folder: gradle\wrapper
        destinationFilename: gradle-wrapper.jar
'
        at java.io.FileOutputStream.open0(Native Method)
        at java.io.FileOutputStream.open(FileOutputStream.java:270)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
        at io.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:576)
        at io.swagger.codegen.DefaultGeneratorTest.testSkipOverwrite(DefaultGeneratorTest.java:179)`

**Comment by wing328** [comment] 2016-06-07 07:05
@LightySnake thanks for performing the test.

I tested with Java1.7 on Windows and didn't encounter any issue with `mvn clean package`

Do you mind cloning `https://github.com/swagger-api/swagger-codegen.git` into a new directory to see if you still encounter the issue?

**Comment by LightySnake** [comment] 2016-06-07 07:25
@wing328 Yes, fresh clone and then mvn clean package.

On my office PC:
`Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T17:41:47+01:00)
Maven home: C:\Program Files\Maven\bin\..
Java version: 1.8.0_91, vendor: Oracle Corporation
Java home: C:\Program Files\Java\jdk1.8.0_91\jre
Default locale: it_IT, platform encoding: Cp1252
OS name: "windows 7", version: "6.1", arch: "amd64", family: "dos"`

Same commit, no errors.

**Comment by wing328** [comment] 2016-06-07 07:29
so the issue only happens on Windows 10 but not 7?

**Comment by LightySnake** [comment] 2016-06-07 07:32
In my case yes, if you need other tests on my home PC i will do it when i exit from work.

**Comment by artem-dudarev** [comment] 2016-06-07 08:23
I've pulled the latest version and it builds successfully on Windows 10 Enterprise x64.

**Comment by jimschubert** [comment] 2016-06-07 13:30
The error @LightySnake is getting is unrelated to my commit. `DefaultGeneratorTest` is a totally different test, and the failure is on gradle-wrapper.jar (not a file generated by tests I wrote). I think the temp folder in those tests are created by a junit helper, while mine aren't.

The problem could be with a virus scanner. When I did development on Windows, I've had Avast and Kaspersky lock temp files if there were many created at once.

**Comment by LightySnake** [comment] 2016-06-08 05:21
@jimschubert @wing328 I've retried with my pc at home (windows 10 x64) with the same commit and everithing does fine. Maybe there was some dirty file.

**Comment by jimschubert** [comment] 2016-06-08 15:17
@wing328 do you know if the folder.create() from `org.junit.rules.TemporaryFolder` accepted a folder prefix? I'm wondering if it's trying to create a random folder name that already exists for some other app, then trying to use it.

**Comment by wing328** [comment] 2016-06-08 15:45
Not familiar with that function. Need to look into it to find out more.

Given that @LightySnake has confirmed it's more a machine-specified issue. I would treat this with low priority.

**Comment by wing328** [comment] 2016-10-02 16:53
If it's still an issue, please reply to let us know.

**Closed by wing328** 2016-10-02 16:53 UTC
Labels: Issue: Bug, Issue: Workaround available
