### ISSUE TITLE
Stackoverflow for circular references

### ISSUE THREAD

**Issue by bastuc** [swagger-api/swagger-codegen#741] opened 2015-05-13 13:18 UTC
Hey guys,

It seems that the code generators cannot handle data contracts with circular references (for example a Track having an Album object that has Tracks itself).

Here is my json description:
{"swagger":"2.0","info":{"version":"v1","title":"Swagger Awesome Demo","description":"This is going to be an awesome demo"},"host":"localhost:34858","schemes":["http"],"paths":{"/api/catalog/track":{"get":{"tags":["Catalog"],"summary":"Lookup a track along with its album and artist details","description":"Lookup a track by its id","operationId":"Catalog_LookupTrack","consumes":[],"produces":["application/json","text/json","application/xml","text/xml"],"parameters":[{"name":"id","in":"query","description":"Id of the track to lookup","required":true,"type":"string"}],"responses":{"200":{"description":"Track","schema":{"$ref":"#/definitions/Track"}},"404":{"description":"Not found"}},"deprecated":false}},"/api/catalog/album":{"get":{"tags":["Catalog"],"summary":"Lookup an album along with its tracks and artist details","operationId":"Catalog_LookupAlbum","consumes":[],"produces":["application/json","text/json","application/xml","text/xml"],"parameters":[{"name":"id","in":"query","description":"Id of the album to lookup","required":true,"type":"string"}],"responses":{"200":{"description":"Album","schema":{"$ref":"#/definitions/Album"}},"404":{"description":"Not found"}},"deprecated":false}},"/api/catalog/artist":{"get":{"tags":["Catalog"],"summary":"Lookup an artist along with its top tracks and albums","operationId":"Catalog_LookupArtist","consumes":[],"produces":["application/json","text/json","application/xml","text/xml"],"parameters":[{"name":"id","in":"query","description":"Id of the artist to lookup","required":true,"type":"string"}],"responses":{"200":{"description":"Artist","schema":{"$ref":"#/definitions/Artist"}},"404":{"description":"Not found"}},"deprecated":false}},"/api/catalog/tracks":{"get":{"tags":["Catalog"],"summary":"Get a list of tracks","operationId":"Catalog_ListTracks","consumes":[],"produces":["application/json","text/json","application/xml","text/xml"],"responses":{"200":{"description":"Track list","schema":{"type":"array","items":{"$ref":"#/definitions/Track"}}},"404":{"description":"Not found"}},"deprecated":false}},"/api/catalog/albums":{"get":{"tags":["Catalog"],"summary":"Get a list of albums","operationId":"Catalog_ListAlbums","consumes":[],"produces":["application/json","text/json","application/xml","text/xml"],"responses":{"200":{"description":"Album list","schema":{"type":"array","items":{"$ref":"#/definitions/Album"}}},"404":{"description":"Not found"}},"deprecated":false}},"/api/catalog/artists":{"get":{"tags":["Catalog"],"summary":"Get a list of artists","operationId":"Catalog_ListArtists","consumes":[],"produces":["application/json","text/json","application/xml","text/xml"],"responses":{"200":{"description":"Artist list","schema":{"type":"array","items":{"$ref":"#/definitions/Artist"}}},"404":{"description":"Not found"}},"deprecated":false}}},"definitions":{"Track":{"description":"Track object","type":"object","properties":{"Title":{"description":"Track title","type":"string"},"Album":{"$ref":"#/definitions/Album","description":"Album containing the track"},"Artist":{"$ref":"#/definitions/Artist","description":"Artist of the track"},"Duration":{"format":"int32","description":"Track duration in seconds","type":"integer"},"Id":{"description":"Content Id for lookup","type":"string"}}},"Album":{"description":"Album object","type":"object","properties":{"Title":{"description":"Album title","type":"string"},"Artist":{"$ref":"#/definitions/Artist","description":"Album artist"},"ReleaseDate":{"format":"date-time","description":"Album release date","type":"string"},"TracksCount":{"format":"int32","description":"Number of tracks in the album","type":"integer"},"Tracks":{"description":"Album tracks","type":"array","items":{"$ref":"#/definitions/Track"}},"Id":{"description":"Content Id for lookup","type":"string"}}},"Artist":{"description":"Artist object","type":"object","properties":{"Name":{"description":"Artist name","type":"string"},"Albums":{"description":"Artist's published albums","type":"array","items":{"$ref":"#/definitions/Album"}},"TopTracks":{"description":"Artist's most popular tracks","type":"array","items":{"$ref":"#/definitions/Track"}},"Id":{"description":"Content Id for lookup","type":"string"}}}}}

I tried to run code generation on those with the following command (and I tried for all languages with the same result):
*java -jar .\modules\swagger-codegen-cli\target\swagger-codegen-cli.jar generate -i .\resources\demon.json -l python -o .\samples\client\demo\python*

And gets the following result:
*reading from .\resources\demo.json
writing file {...}\swagger-codegen\.\samples\client\demo\python/client\models\Track.py
writing file {...}\swagger-codegen\.\samples\client\demo\python/client\models\Album.py
writing file {...}\swagger-codegen\.\samples\client\demo\python/client\models\Artist.py
Exception in thread "main" java.lang.StackOverflowError
    at com.wordnik.swagger.codegen.examples.XmlExampleGenerator.modelImplToXml(XmlExampleGenerator.java:59)
    at com.wordnik.swagger.codegen.examples.XmlExampleGenerator.toXml(XmlExampleGenerator.java:38)
    at com.wordnik.swagger.codegen.examples.XmlExampleGenerator.toXml(XmlExampleGenerator.java:119)
    at com.wordnik.swagger.codegen.examples.XmlExampleGenerator.modelImplToXml(XmlExampleGenerator.java:76)
    at com.wordnik.swagger.codegen.examples.XmlExampleGenerator.modelImplToXml(XmlExampleGenerator.java:59)
    at com.wordnik.swagger.codegen.examples.XmlExampleGenerator.toXml(XmlExampleGenerator.java:38)
    at com.wordnik.swagger.codegen.examples.XmlExampleGenerator.toXml(XmlExampleGenerator.java:119)
    at com.wordnik.swagger.codegen.examples.XmlExampleGenerator.modelImplToXml(XmlExampleGenerator.java:76)*
.
.
.
those four lines repeated a lof of times.

I suspect that the code gets lost trying to generate an example and circling through the circular references, would that make sense? I feel this is quite a common use case in data contracts, so I was a bit surprised to see that I couldn't find anyone raising this issue before. Maybe I'm doing something wrong?

Cheers and thanks for the good work!

**Comment by webron** [comment] 2015-05-13 13:20
I believe this is a duplicate of #728.

**Closed by webron** 2015-05-13 13:20 UTC

**Comment by bastuc** [comment] 2015-05-13 13:21
Yes that might be the case, #728 just didn't provide a lot of information about the error raised. If that's so then we're all good, I'll be waiting for that fix.

Thanks for the quick response!

**Comment by webron** [comment] 2015-05-13 13:22
Feel free to add the information there :)
