### ISSUE TITLE
[typescript-angular2] Error occurs while build generated typescript-angular2 from master branch

### ISSUE THREAD

**Issue by inska** [swagger-api/swagger-codegen#2906] opened 2016-05-19 07:59 UTC
##### Description
Can't run 'npm run build' command on generated typescript-angular2 directory. 

```
api/ProfileApi.ts(154,82): error TS2305: Module '"/workspace/angular/model/models"' has no exported member 'any'.
api/ProjectApi.ts(470,145): error TS2305: Module '"/workspace/angular/model/models"' has no exported member 'any'.
model/FileEntity.ts(21,19): error TS2305: Module '"/workspace/angular/model/models"' has no exported member 'any'.
model/Job.ts(27,19): error TS2305: Module '"/workspace/angular/model/models"' has no exported member 'any'.
model/ProjectEntity.ts(19,19): error TS2305: Module '"/workspace/angular/model/models"' has no exported member 'any'.

npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
npm ERR! node v6.0.0
npm ERR! npm  v3.8.6
npm ERR! code ELIFECYCLE
npm ERR! @cupix/einstein@0.1.0-SNAPSHOT.201605191652 build: `typings install && tsc`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the @cupix/einstein@0.1.0-SNAPSHOT.201605191652 build script 'typings install && tsc'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the @cupix/einstein package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     typings install && tsc
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs @cupix/einstein
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls @cupix/einstein
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
```

##### Swagger-codegen version
swagger-api version is 2.1.6, and master branch with codegen

##### Swagger declaration file content or url
http://einstein-stage.cupix.com/api.json

##### Command line used for generation

java -jar ~/swagger/swagger-codegen/modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate -i public/swagger/api.yaml -l typescript-angular2 -c bin/typescript-angular2.json -o ./angular

##### Steps to reproduce

npm install
npm run build

on the angular directory

**Comment by wing328** [comment] 2016-05-19 08:16
@inska I'm able to repeat the error with petstore.
```
$ npm run build

> @swagger/angular2-typescript-petstore@0.0.1-SNAPSHOT.201605120027 build /Users/williamcheng/Code/swagger-api/swagger-codegen/samples/client/petstore/typescript-angular2/npm
> typings install && tsc


└── core-js (ambient)

api/PetApi.ts(76,46): error TS2305: Module '"/Users/williamcheng/Code/swagger-api/swagger-codegen/samples/client/petstore/typescript-angular2/npm/model/models"' has no exported member 'Array'.
api/PetApi.ts(100,42): error TS2305: Module '"/Users/williamcheng/Code/swagger-api/swagger-codegen/samples/client/petstore/typescript-angular2/npm/model/models"' has no exported member 'Array'.
api/PetApi.ts(208,82): error TS2305: Module '"/Users/williamcheng/Code/swagger-api/swagger-codegen/samples/client/petstore/typescript-angular2/npm/model/models"' has no exported member 'any'.
api/UserApi.ts(48,53): error TS2305: Module '"/Users/williamcheng/Code/swagger-api/swagger-codegen/samples/client/petstore/typescript-angular2/npm/model/models"' has no exported member 'Array'.
api/UserApi.ts(69,52): error TS2305: Module '"/Users/williamcheng/Code/swagger-api/swagger-codegen/samples/client/petstore/typescript-angular2/npm/model/models"' has no exported member 'Array'.

npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/Cellar/node/5.0.0/bin/node" "/Users/williamcheng/.node/bin/npm" "run" "build"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.10
npm ERR! code ELIFECYCLE
npm ERR! @swagger/angular2-typescript-petstore@0.0.1-SNAPSHOT.201605120027 build: `typings install && tsc`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the @swagger/angular2-typescript-petstore@0.0.1-SNAPSHOT.201605120027 build script 'typings install && tsc'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the @swagger/angular2-typescript-petstore package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     typings install && tsc
npm ERR! You can get their info via:
npm ERR!     npm owner ls @swagger/angular2-typescript-petstore
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/williamcheng/Code/swagger-api/swagger-codegen/samples/client/petstore/typescript-angular2/npm/npm-debug.log
npm|master⚡ ⇒ 
```

**Comment by wing328** [comment] 2016-05-19 08:17
cc @taxpon to see if he's any clue.

**Comment by inska** [comment] 2016-05-19 08:22
Thank you @wing328.

**Comment by wing328** [comment] 2016-05-19 08:26
I confirmed the issue has nothing to do with @taxpon PR (https://github.com/swagger-api/swagger-codegen/pull/2771) as the commit before has the same issue.

We will need to add better CI tests to catch the issue moving forward.

**Comment by wing328** [comment] 2016-05-19 11:30
UPDATE: I've filed https://github.com/swagger-api/swagger-codegen/pull/2910 to add better integration tests for Typescript API clients.

**Comment by taxpon** [comment] 2016-05-19 15:22
This is because execution of `tsc` command failed.

For example @inska 's case, there are some errors as follows.
```
api/ProfileApi.ts(154,82): error TS2305: Module '"/workspace/angular/model/models"' has no exported member 'any'.
api/ProjectApi.ts(470,145): error TS2305: Module '"/workspace/angular/model/models"' has no exported member 'any'.
model/FileEntity.ts(21,19): error TS2305: Module '"/workspace/angular/model/models"' has no exported member 'any'.
model/Job.ts(27,19): error TS2305: Module '"/workspace/angular/model/models"' has no exported member 'any'.
model/ProjectEntity.ts(19,19): error TS2305: Module '"/workspace/angular/model/models"' has no exported member 'any'.
```
If you want to avoid npm's error simply, you can update your npm script as follows (but it's no meaning):
```
"build": "typings install && echo $(tsc)"
```
At any rate, typescript-angular2 code-gen code should be fixed so that it handles `any` and `Array` type correctly.

**Comment by wing328** [comment] 2016-05-19 16:15
@taxpon thanks for the details on the issue. I agree with you that we should not simply avoid/ignore the errors.

**Comment by wing328** [comment] 2016-05-19 16:22
cc @Vrolijkx

**Comment by Vrolijkx** [comment] 2016-05-19 18:01
io/swagger/codegen/languages/TypeScriptAngular2ClientCodegen.java:128 normaly makes sure their isn't need of the models prefix with typescript primitives. But I need to investigated this problem a bit further.

**Closed** 2016-05-21 09:42 UTC
Labels: Bug, Client: TypeScript

**Comment by grEvenX** [comment] 2017-07-11 09:37
I'm getting this same issue (but now for `Array` instead of `any`) on swagger-codegen version 2.2.3. Should this one be reopened or should I create a new issue for that @wing328 ?

```
angular-client git:(master) ✗ npm install

> myworkout-api-client@2.0.0-SNAPSHOT.201707110822 postinstall /Users/even/myworkout/api-v2/angular-client
> npm run build


> myworkout-api-client@2.0.0-SNAPSHOT.201707110822 build /Users/even/myworkout/api-v2/angular-client
> typings install && tsc --outDir dist/

typings WARN deprecated 9/14/2016: "registry:dt/core-js#0.0.0+20160725163759" is deprecated (updated, replaced or removed)

└── core-js (global)

model/TrainerCollectionResponse.ts(15,59): error TS2305: Module '"/Users/even/myworkout/api-v2/angular-client/model/models"' has no exported member 'Array'.
model/VideoCategoryCollectionResponse.ts(15,65): error TS2305: Module '"/Users/even/myworkout/api-v2/angular-client/model/models"' has no exported member 'Array'.
```

**Comment by wing328** [comment] 2017-07-11 10:37
@grEvenX have you tried the latest 2.3.0 branch, which contains breaking changes?

In 2.3.0 branch, we've already setup CI (travis) to cover TS Angular 2.x and 4.x clients.

**Comment by grEvenX** [comment] 2017-07-11 10:38
@wing328 Haven't tried the 2.3.0 branch, I will give that a try

**Comment by grEvenX** [comment] 2017-07-11 12:10
@wing328 that one compiles nicely, is there any documentation somewhere that is up to date on how to use the services etc. exposed from the generated client? The `README.md` generated seems out of date with the updated code and I don't understand how to invoke a service based on it.

**Comment by wing328** [comment] 2017-07-11 14:00
cc @Vrolijkx @taxpon @sebastianhaas @kenisteward to see if they've any tips/suggestions on consuming the TS Angular2 API client.

**Comment by sebastianhaas** [comment] 2017-07-11 14:22
@grEvenX you could take a look at https://github.com/swagger-api/swagger-codegen/issues/3221, I've described usage scenarios there.

Agree that we need to improve on documentation in the 2.3.0 branch.

**Comment by grEvenX** [comment] 2017-07-12 11:53
@sebastianhaas Thanks, I was able to get the services working based on the discussion there
