### ISSUE TITLE
[typescript-node] Error generating model of type array

### ISSUE THREAD

**Issue by bvwells** [swagger-api/swagger-codegen#7827] opened 2018-03-12 20:57 UTC
##### Description

The typescript-node generator generates invalid code when a swagger spec contains a model of type array. For example: 

```
  SomeCollection:
    type: array
    items:
      $ref: '#/definitions/Some'
  Some:
    description: Some object
    properties:
      name:
        type: string
        description: Name of some
```

The code generated for SomeCollection model is:

```
export class SomeCollection extends Array<Some> {

    static discriminator = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
    ];

    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(SomeCollection.attributeTypeMap);
    }
}
```

which is invalid as the function getAttributeTypeMap does not exist on type array. The transpilation error is:

typescript-node/api.ts(667,22): error TS2339: Property 'getAttributeTypeMap' does not exist on type 'ArrayConstructor'.

##### Swagger-codegen version
2.4.0-SNAPSHOT

##### Swagger declaration file content or url

Add above models (SomeCollection and Some) to petstore.yaml.

##### Command line used for generation
```
swagger-codegen generate -i modules/swagger-codegen/src/test/resources/2_0/petstore.yaml -l typescript-node -o samples/client/petstore/typescript-node/default"
```

##### Steps to reproduce

1. Add SomeCollection and Some defined above to modules/swagger-codegen/src/test/resources/2_0/petstore.yaml
2. Generate typescript-node client with above command like.

##### Related issues/PRs

N/A

**Comment by macjohnny** [comment] 2018-03-13 06:55
@bvwells thanks for reporting. could you try to implement a fix for this?

**Comment by bvwells** [comment] 2018-03-14 21:15
Hi @macjohnny, 
I've submitted PR #7842 to try to address the issue. Let me know if you have any feedback on the fix. 
I thought it would be good to add an model of type array to one of the test swagger definitions. Any suggestion as to the best place to add it?
Thanks
Ben

**Comment by bvwells** [comment] 2018-03-17 09:43
Had some issues with my author info. Will have to close and open a new PR. Sorry about this.

**Comment by bvwells** [comment] 2018-03-30 08:59
Happy for this to now be closed. Many thanks @wing328 and @macjohnny!

**Closed** 2018-03-30 08:59 UTC

**Comment by brunoric** [comment] 2019-04-25 09:33
Hi bumping this issue again. I think the fix was applied only to typescript-node generation since I have the same issue but to generate typescript-fetch. 

````
/**
 * 
 * @export
 * @interface Array
 */
export interface Array {
    /**
     * 
     * @type {ERRORUNKNOWN}
     * @memberof Array
     */
    type?: ERRORUNKNOWN;
}
````
Anyone having the same issue?

Thanks!

**Comment by wing328** [comment] 2019-05-02 10:00
@brunoric I would suggest open a new issue with a minimal spec to reproduce this issue and reference this ticket/issue.

**Comment by bvwells** [comment] 2019-05-07 13:36
Hi @brunoric ,
This issue reported an issue in the typescript-node generator and hence the fix was only for typescript-node. It is probably best if you submit a separate issue if there is an issue in the typescript-fetch generator.
Hope this helps,
Ben

**Comment by p-fedyukovich** [comment] 2019-12-26 03:25
Hi @bvwells.
Seems like it did not solve the issue. Once you removed `getAttributeTypeMap` now it crashes with runtime error
```
TypeError: typeMap[type].getAttributeTypeMap is not a function
```
here https://github.com/swagger-api/swagger-codegen/blob/dfca58cc5c9301c2cc2149bf76fced2062a13677/modules/swagger-codegen/src/main/resources/typescript-node/api.mustache#L120
