### ISSUE TITLE
AllOf $ref causes model to generate 'Object'

### ISSUE THREAD

**Issue by jafferton91** [swagger-api/swagger-codegen#10055] opened 2020-02-23 11:26 UTC
"allOf": [
            {
              "$ref": "#/definitions/MyModel"
            }

Becomes "Object" in Java client library. 

I have replicated this with most versions available.

**Comment by soynerdito** [comment] 2020-02-27 15:01
I am having exactly the same issue.
This happens when the model that is represented in the Json is a complex model that has a property of some model. When the property is an array it works ok. Seems that when missing the "type" property is fails to recognize the type of variable.

"noworkproperty": {
          "description": "",
          "allOf": [
            {
              "$ref": "#/definitions/MyModel"
            }
          ]
        }
When the member property is an array it parses it correctly
"workingprop": {
   "type": "array",
   "items": {
      "$ref": "#/definitions/MyModel"
   }
}

**Comment by HugoMario** [comment] 2020-02-27 20:38
hello, what codegen version are you working on?

**Comment by soynerdito** [comment] 2020-03-02 13:57
In my case I am using the swagger-codegen from master.
I did clone it though because I wanted a particular code generated for the dotnet core.
To discard it was a particular situation with my version, I also tried https://editor.swagger.io/ to generate the code and it do the type as Object.
What I am not sure if this is a an issue creating the json or is this a codegen issue. I am not familiar with the spec on the format.
I tried to "correct" this on my code base, and to be honest. Don't understand much of the code and do not know how to debug it. So after banging my head through the code put it to rest for a bit.
Please note, the code I use to generate the json spec file is via swashbukle on c#. Prior versions of swashbukle generated the json differently and used to work like a charm.

**Comment by HugoMario** [comment] 2020-11-07 08:30
hey guys, i've been trying to reproduce this, but i'm not getting any "Object" type in output, i guess it was fixed in recent releases, going to close this for now, but if some one gets the issue again, please let me know and i work on it.

**Closed by HugoMario** 2020-11-07 08:30 UTC

**Comment by Treverix** [comment] 2023-03-30 12:31
I was blocked by the same issue, using 3.0.21 and also 3.0.41. If generated an invalid import of `my.package.Object` on the model POJO.

But I found a workaround. import mapping does the trick (if you can accept an unused import on the generated file)

In your `pom.xml` in the configuration section of the plugin (plugin>executions>execution>configuration), do a

```xml
<importMappings>
  <importMapping>Object=java.lang.Object</importMapping>
<importMappings>
```

Replace the `Object` on the left side only with `ObjectMySuffix` if you have a `<modelNameSuffix>MySuffix</modelNameSuffix>` on the configuration.

**Comment by HugoMario** [comment] 2023-04-02 04:40
Hey @Treverix 
can you please share an example of a definition you are using that makes this wrong behave?
