### ISSUE TITLE
Swift 5 support

### ISSUE THREAD

**Issue by vialyx** [swagger-api/swagger-codegen#9386] opened 2019-04-18 10:58 UTC

**Comment by pieperu** [comment] 2019-06-18 07:39
Is there any update on when we should expect this fantastic piece of kit to support swift 5?

**Comment by silviokuehn** [comment] 2019-07-01 13:45
> Is there any update on when we should expect this fantastic piece of kit to support swift 5?

Same question here. We are interested in generating swagger clients on swift 5.

**Comment by vialyx** [comment] 2019-07-01 13:54
My teammate developed .jar with swift 5 support.
Download here -> https://www.dropbox.com/s/rsg5kwp1j0438ir/swagger-codegen-cli.jar.zip?dl=0

**Comment by b0g3r** [comment] 2019-09-07 10:36
@vialyx 
Any possibilities to create PR with swift5 support for 3.x swagger-codegen version? I think it's a very good candidate for merging to master branch 🌚

**Comment by HugoMario** [comment] 2019-09-07 10:59
that's great, please ping me if you need help to merge a PR

**Comment by plam4u** [comment] 2019-09-25 12:27
I've submitted a PR with Swift 5. Who should review it? @HugoMario?
https://github.com/swagger-api/swagger-codegen/pull/9731

**Comment by HugoMario** [comment] 2019-09-25 21:08
Hi @plam4u , i'm not familiar with swift 5, but if you are confident of your changes i'll merge them.

**Comment by plam4u** [comment] 2019-09-26 07:59
> Hi @plam4u , i'm not familiar with swift 5, but if you are confident of your changes i'll merge them.

It works for me using the PetStore sample project provided by the swagger-codegen. Ideally, someone with swift background should at least try it and confirm that everything works fine.

I'll try to do extensive testing in our app migrating 11 APIs to Swift 5 and if nobody responds soon, we can do what you suggest and merge it.

Keep in mind that I did not touch the RxSwift or Objective-C code. These are copied as-is from the swift4 folder. Not sure if this is a problem.

**Comment by 4brunu** [comment] 2019-09-26 10:09
Hi @plam4u, thanks for your contribution :)

I have tested your branch, but the generated code has two build errors.

`Protocol type 'Any' cannot conform to 'Encodable' because only concrete types can conform to protocols `
`Protocol type 'Any' cannot conform to 'Decodable' because only concrete types can conform to protocols`

Here is an example of the generated code and the errors are in comments.
Not sure if it helps.

<details>
  <summary>Generated code</summary>
import Foundation

public struct ProblemDetails: Codable {

    public var type: String?
    public var title: String?
    public var status: Int?
    public var detail: String?
    public var instance: String?

    public init(type: String?, title: String?, status: Int?, detail: String?, instance: String?) {
        self.type = type
        self.title = title
        self.status = status
        self.detail = detail
        self.instance = instance
    }
    public var additionalProperties: [String:Any] = [:]

    public subscript(key: String) -> Any? {
        get {
            if let value = additionalProperties[key] {
                return value
            }
            return nil
        }

        set {
            additionalProperties[key] = newValue
        }
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encodeIfPresent(type, forKey: "type")
        try container.encodeIfPresent(title, forKey: "title")
        try container.encodeIfPresent(status, forKey: "status")
        try container.encodeIfPresent(detail, forKey: "detail")
        try container.encodeIfPresent(instance, forKey: "instance")
        try container.encodeMap(additionalProperties) // build error here. `Protocol type 'Any' cannot conform to 'Encodable' because only concrete types can conform to protocols `
    }

    // Decodable protocol methods

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        type = try container.decodeIfPresent(String.self, forKey: "type")
        title = try container.decodeIfPresent(String.self, forKey: "title")
        status = try container.decodeIfPresent(Int.self, forKey: "status")
        detail = try container.decodeIfPresent(String.self, forKey: "detail")
        instance = try container.decodeIfPresent(String.self, forKey: "instance")
        var nonAdditionalPropertyKeys = Set<String>()
        nonAdditionalPropertyKeys.insert("type")
        nonAdditionalPropertyKeys.insert("title")
        nonAdditionalPropertyKeys.insert("status")
        nonAdditionalPropertyKeys.insert("detail")
        nonAdditionalPropertyKeys.insert("instance")
        additionalProperties = try container.decodeMap(Any.self, excludedKeys: nonAdditionalPropertyKeys) // build error here. `Protocol type 'Any' cannot conform to 'Decodable' because only concrete types can conform to protocols`
    }

}
</details>

**Comment by plam4u** [comment] 2019-09-26 13:00
Thanks for the feedback @4brunu!
I'll check the code you provided, try to reproduce the issue and fix it.

**Comment by 4brunu** [comment] 2019-09-26 16:29
@plam4u another issue that I found is that the version of Alomofire included in podspec doesn't compile with Xcode 11 and Swift 5.1.

I needed to upgrade from `s.dependency 'Alamofire', '~> 4.9.0'` to `s.dependency 'Alamofire', '~> 4.9.0'`.

Can you also update the podspec please?

If you need help with anything, please let me know.

Thanks

**Comment by plam4u** [comment] 2019-10-01 08:08
> Hi @plam4u, thanks for your contribution :)
> 
> I have tested your branch, but the generated code has two build errors.
> 
> `Protocol type 'Any' cannot conform to 'Encodable' because only concrete types can conform to protocols `
> `Protocol type 'Any' cannot conform to 'Decodable' because only concrete types can conform to protocols`
> 
> Here is an example of the generated code and the errors are in comments.
> Not sure if it helps.
> 
> Generated code

I was able to reproduce the issue. I'm working on it but it will happen slower since I don't have much time these days.

**Comment by 4brunu** [comment] 2019-10-01 09:14
Thanks, take your time :)

**Comment by andreashaese** [comment] 2019-10-01 15:17
This is excellent, thanks a lot for your efforts – my team and I are looking forward to using this in our projects!

Just one thing: The generated functions yield tuples, one element representing the nullable success data type, the other one a nullable error. Is there any chance to use Swift's [Result](https://developer.apple.com/documentation/swift/result) type instead? In my opinion that would make call sites easier to write, and less error prone.

**Comment by plam4u** [comment] 2019-10-24 13:53
Guys, the PR has been updated. Could you check if it works for you now? @4brunu @HugoMario

**Comment by markfinlabs** [comment] 2019-10-26 16:21
Hi @plam4u , does your update fix this issue?

https://github.com/swagger-api/swagger-codegen/issues/9020

This is really annoying and wondering if just requires a simple fix?

BR,
Mark

**Comment by Tovkal** [comment] 2019-10-28 08:05
The PR was merged.

**Comment by shoshins** [comment] 2019-11-23 09:48
Hi, guys. Could you please add Swift 5 support to the swagger-codegen v.3 too. Thanks.

**Comment by shoshins** [comment] 2019-11-23 11:27
Just added one more thing that will be better to fix: responseAs PromiseKit configuration throws compilation errors inside Pods/ library. It will be great if someone can update it to the latest v6 by their guidelines.

**Comment by ludovicoloreti** [comment] 2019-11-27 14:32
up, is it possible to have the support of swift5 also in beta?

**Comment by HugoMario** [comment] 2019-12-08 21:31
swift 5 is now supported, so going to close this. 

Also, these changes were applied to codegen version 3. So @shoshins , @ludovicoloreti , @4brunu @plam4u 

can you please check swift5 in codegen v3 when you have a chance?

going to close this btw.

**Closed by HugoMario** 2019-12-08 21:31 UTC

**Comment by silviokuehn** [comment] 2019-12-09 08:25
In v2.4.10 Swift 5 is available. In 3.0.14 it is still missing.
https://mvnrepository.com/artifact/io.swagger/swagger-codegen-cli/2.4.10
https://mvnrepository.com/artifact/io.swagger.codegen.v3/swagger-codegen-cli/3.0.14

**Comment by HugoMario** [comment] 2019-12-09 16:37
hi @silviokuehn , right. it's not in release yet for v3 but you can check it from [here](https://oss.sonatype.org/content/repositories/snapshots/io/swagger/codegen/v3/swagger-codegen-cli/3.0.15-SNAPSHOT/swagger-codegen-cli-3.0.15-20191208.220836-15.jar)
