### ISSUE TITLE
Python generator generates invalid Python3

### ISSUE THREAD

**Issue by AmandaCameron** [swagger-api/swagger-codegen#1279] opened 2015-09-22 20:42 UTC
https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/python/api_client.mustache#L191 is the offending line, sys is never imported into the namespace.

This was probably introduced in [This commit](https://github.com/swagger-api/swagger-codegen/commit/65f86dbb0f3549821c357171f44c86325bdbeb5b)
I can fork and make a simple PR for this, if you'd like.

**Comment by wing328** [comment] 2015-09-22 23:23
@AmandaCameron thanks for reporting the issue. I run the unit testing again and the result is good:
```
-----------------------------------------------------------------
TOTAL                                1241    470    62%   
----------------------------------------------------------------------
Ran 28 tests in 20.817s

OK
_____________________________________________ summary ______________________________________________
  py27: commands succeeded
  py34: commands succeeded
  congratulations :)
```

Can you share with us the error message you got and code snippet to reproduce the error?

**Comment by wing328** [comment] 2015-09-23 10:42
@AmandaCameron it turns out that my test is not accurate as the Python sample code has not been updated. After generating the latest Python Petstore sample, unit testing reports error.

@geekerzp has submitted #1281 to address the issue.

**Comment by wing328** [comment] 2015-09-24 08:34
@AmandaCameron  #1289 merged into master. Please reopen this if you still encounter issue. Thanks again for reporting the issue.

**Closed by wing328** 2015-09-24 08:34 UTC
Labels: Bug, Client: Python, P2
