### ISSUE TITLE
[JAVA][3.0.0-rc0] NullPointerException - processOperation, because default tag is created

### ISSUE THREAD

**Issue by dewijant** [swagger-api/swagger-codegen#7524] opened 2018-01-29 14:58 UTC
##### Description

I get NPE in processOperation() in class DefaultGenerator
line848:
```java
 CodegenOperation codegenOperation = this.config.fromOperation(resourcePath, httpMethod, operation, this.openAPI.getComponents().getSchemas(), this.openAPI);
```
##### Swagger-codegen version

swagger 3.0.0-rc0

##### Swagger declaration file content or url

```json
{
  "openapi": "3.0.0",
  "info": {
    "title": "Ness study OpenAPI",
    "description": "Nejaky popis",
    "version": "1.0b"
  },
  "servers": [
    {
      "url":"http://localhost:8080/openapi",
      "description":"Develpment local machine"
    }
  ],
  "paths": {
     "/test/{marek}": {
         "get": {
            "description": "This is only test",
            "operationId": "getTestRestGET",
            "responses": {
                "200": {
                    "description": "Return test text only",
                    "content": {
                        "application/json": {
                            "example": {
                                "name": "Homer",
                                "surname": "Simpson"
                            }
                        }
                    }
                }
            }
         }

     }
  }
}
```

For generate i use maven plugin, here is
```xml
<plugin>
                <groupId>io.swagger</groupId>
                <artifactId>swagger-codegen-maven-plugin</artifactId>
                <version>3.0.0-rc0</version>
                <configuration>
                    <inputSpec>${project.basedir}/src/main/resources/swagger/study.openapi.json</inputSpec>
                    <language>java</language>
                    <verbose>true</verbose>
                    <generateModels>false</generateModels>
                </configuration>
                <executions>
                    <execution>
                        <phase>compile</phase>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
```
##### Steps to reproduce

run maven compile

I think it causes calling:  this.openAPI.getComponents().getSchemas on line 848 described above, because component is null.
This NPE is catched in loop on line 846 for (Tag tag : tags), but I have no one tag specified in my openapi spec. DefaultGenerator make default tag and then step into loop ... NPE will happen

```java
for (Tag tag : tags)
      try {
        CodegenOperation codegenOperation = this.config.fromOperation(resourcePath, httpMethod, operation, this.openAPI.getComponents().getSchemas(), this.openAPI);
        codegenOperation.tags = new ArrayList(tags);
...
```
In addition i turn off generate models in maven plugin 
```xml
<generateModels>false</generateModels>
```

**Comment by HugoMario** [comment] 2018-02-01 19:08
@dewijant this was fixed on this [PR](https://github.com/swagger-api/swagger-codegen/pull/7552), can you please check it when you have a chance?

**Comment by dewijant** [comment] 2018-02-06 11:29
Hello @HugoMario fix about adding dependency to swagger-codegen-maven-plugin/pom.xml does not work.
Still same error Exception in thread "main" java.util.ServiceConfigurationError: io.swagger.codegen.CodegenConfig: Provider io.swagger.codegen.languages.java.JavaClientCodegen not found.

Next, I have not checked fix for NPE in DefaultGenerator.class yet.

**Comment by HugoMario** [comment] 2018-02-10 20:39
Hello @dewijant have you tried recently?
we added dependency on `swagger-codegen-maven-plugin` that must fix that error.

**Comment by HugoMario** [comment] 2018-02-13 06:43
let's close this for now, please let me know if the issue is still present.

**Closed by HugoMario** 2018-02-13 06:43 UTC
