### ISSUE TITLE
Formatting not getting reflected when converting yaml file to HTML in swagger online editor

### ISSUE THREAD

**Issue by webron** [swagger-api/swagger-codegen#3436] opened 2016-07-21 23:54 UTC
_From @Rasika3091 on July 21, 2016 14:46_
- Version: Swagger editor online
- Browser/OS:  Chrome, Windows 10

Hello,

I am converting my yaml file to HMTL through the swagger editor online. But the formatting applied in the descriptions are not getting applied. Its not looking proper as seen in the editor. I have provided on example. Please open it in Online swagger editor and covert it to HTML and take a look at all the description parts.

`````` yaml
swagger: "2.0"
info:
  version: "0.0.1"
  title: Hello World App
  description: |
               Description for test :

               ###### Types :

               ```
                  1) Standard Fields
                  2) Custom Fields
                  3) Old Fields
               ```

               ###### JSON structure :

               ```
               {"standardFields":
                   [
                     {"id":Provide field Id,
                      "value":Provide value for that standard field}
                  ]
               }
               ```

# during dev, should point to your local machine
host: localhost:10010
# basePath prefixes all resource paths 
basePath: /
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /hello:
      # binds a127 app logic to a route
      x-swagger-router-controller: hello_world
      get:
        description: |
                     Returns 'Hello' to the caller

                     ###### Access

                     - New user
                     - Updated User
        operationId: hello
        parameters:
          - name: name
            in: query
            description: The name of the person to whom to say hello
            required: false
            type: string
          - name: id
            in: query
            description: Id required
            required: true
            type: string
        responses:
          "200":
            description: Success
            schema:
              # a pointer to a definition
              $ref: "#/definitions/HelloWorldResponse"
          # responses may fall through to errors
          default:
            description: Error
            schema:
              $ref: "#/definitions/ErrorResponse"
  /swagger:
    x-swagger-pipe: swagger_raw
  /getName:
     get:
       description: |
                    Get name

                    ###### Access

                     - New user
                     - Updated User
       parameters:
          - name: name
            in: query
            description: The name of the person to whom to say hello
            required: false
            type: string
          - name: id
            in: query
            description: Id required
            required: true
            type: string
       responses:
          "200":
            description: Success
            schema:
              # a pointer to a definition
              $ref: "#/definitions/HelloWorldResponse"
          # responses may fall through to errors
          default:
            description: Error
            schema:
              $ref: "#/definitions/ErrorResponse"
  /getDescription:
     get:
       description: |
                    Get description

                    ###### Access

                     - New user
                     - Updated User
       parameters:
          - name: name
            in: query
            description: The name of the person to whom to say hello
            required: false
            type: string
          - name: id
            in: query
            description: Id required
            required: true
            type: string
       responses:
          "200":
            description: Success
            schema:
              # a pointer to a definition
              $ref: "#/definitions/HelloWorldResponse"
          # responses may fall through to errors
          default:
            description: Error
            schema:
              $ref: "#/definitions/ErrorResponse"            

# complex objects have schema definitions
definitions:
  HelloWorldResponse:
    required:
      - message
    properties:
      message:
        type: string
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string

``````

There is no formatting in the HTML file for description. How can I make this work ?

I am attaching the html document . Please take a look. Its urgent. I have to convert my documentation to HTML.

[Html.zip](https://github.com/swagger-api/swagger-editor/files/376290/Html.zip)

_Copied from original issue: swagger-api/swagger-editor#1016_

**Comment by Rasika3091** [comment] 2016-07-22 05:44
Hello, 
     Thanks for shifting the issue. But can you tell me whats the status of the issue ?

**Comment by wing328** [comment] 2016-07-22 08:07
I think the issue you're referring to is to convert markdown in the description to HTML properly

Currently, the HTML documentation generator does not support that. You can customize the generator to convert entries (in markdown syntax) in the YAML spec to HTML properly.

**Comment by Rasika3091** [comment] 2016-07-22 14:36
Ok.. Then right now you cannot make changes for it ?

**Comment by wing328** [comment] 2016-07-22 14:46
Well everyone can contribute an enhancement for that. If you've cycle, I can show you a good starting point.

**Comment by Herst** [comment] 2016-08-27 16:00
Duplicate of #479.

**Comment by DavidBiesack** [comment] 2016-09-26 13:47
one option: https://github.com/atlassian/commonmark-java

**Comment by DavidBiesack** [comment] 2017-02-03 17:41
I'm working on a PR for this.... 
I'm doing the transformations in the various `postProcess*` and `preprocessSwagger` methods  which gets the job done but is not robust (many subclasses may not call super()).

However, Mustache was still escaping the text. When I add to `get` operation:
```
  summary: a summary of the `/thing` resource
  description: a description of the `/thing` resource ...
```
the text is converted from markdown to YAML as
```
a summary of the <code>/thing</code> resource
a description of the <code>/thing</code> resource
```
but then when the template with {{summary}} and {{unescapedDescription}} is applied,
the result has HTML escaping:

```
a summary of the &lt;code&gt;/thing&lt;/code&gt; resource
a description of the &lt;code&gt;/thing&lt;/code&gt; resource
```
I found that Mustache then takes the values and runs them through

```
write(out, _escaper.escape(_formatter.format(value)));
```
and Mustache appears to use the default escaper `Escapers.simple()` which
replace `<` with `&lt;` etc.

Thus, I think the config needs to have an escaper that can override this.

I'm considering adding 
```
    Escaper escaper(); // default escaper escapes HTML markup
```
to CodegenConfig and add 
```
    public Escaper escaper() {
        return Escapers.simple();
    }
```
tot `DefaultCodegen`. Then the html codegen can override this and return `Escapers.NONE`. DefaultCodegen then passes the escaper to the Template compiler
```
 .withEscaper(config.escaper())
```
(in two places).

Please comment on this approach.

**Comment by DavidBiesack** [comment] 2017-03-23 13:44
Note that a pull request (#5144) was merged which will fix this issue in `swagger-codegen generate -l html` output - it may take some time before that is deployed on editor.swagger.io. Also, I was able to resolve the Mustache HTML escaping without having to employ [the proposed changes listed above](https://github.com/swagger-api/swagger-codegen/issues/3436#issuecomment-277312649). We can probably close this issue as fixed (but I'll let the maintainers do that.)

**Comment by wing328** [comment] 2017-03-23 14:01
@DavidBiesack thanks for the fix 👍

**Closed** 2017-03-23 14:00 UTC
Labels: Client: HTML, Enhancement: Feature, Need community contribution

**Comment by Valrravn** [comment] 2024-04-10 11:56
@DavidBiesack sorry for the necroposting, but I've recently been assigned to a REST API doc team that uses a custom converter based on the default swagger tool, and I'm stuck on escaping.

My output are `.md` files generated via the `java -jar <codegen jar file> generate -l <project name> -i <json file location> -o <output folder>` command. The JSON file is generated from a Java backend that looks like the following:

```
@XmlAttribute
@ApiModelProperty(
     value = "Returns whether a build has finished successfully (or is expected to finish so, if still running). Possible values: \n\n" +
     "* `null` for queued builds. \n" +
     "* `SUCCESS` for builds that have successfully finished or still running without errors. \n" +
     "* <code>FAILURE</code> for builds that failed to start or failed during their run. \n" +
      "* *UNKNOWN* for canceled builds.",
     example = "SUCCESS")
public String getStatus() {
     // ....
}
```

using {{unescapedDescription}} helped with "\n", but both "`" backticks and "<code>" tags (tried both Markdown and standard HTML options here) are still escaped, so the generated .md looks like the following:

```
Returns whether a build has finished successfully (or is expected to finish so, if still running). Possible values: 

* &#x60;null&#x60; for queued builds. 
* &#x60;SUCCESS&#x60; for builds that have successfully finished or still running without errors. 
* &lt;code&gt;FAILURE&lt;/code&gt; for builds that failed to start or failed during their run. 
* &lt;code&gt;UNKNOWN&lt;/code&gt; for canceled builds.
```

You've mentioned that you managed to resolve this issue without adding escapers, can you please share the details? Much appreciated.
