### ISSUE TITLE
[C#] Return type InlineResponse200 and compilation error instead of object

### ISSUE THREAD

**Issue by artem-dudarev** [swagger-api/swagger-codegen#1639] opened 2015-11-30 13:36 UTC
If API return type is object then generated method returns InlineResponse200, but not object.
This InlineResponse200 also has an invalid Equals() implementation which produces the following compilation error:
error CS0126: An object of a type convertible to 'bool' is required

Swagger spec:
```json
{
    "swagger": "2.0",
    "paths": {
        "/api/test": {
            "get": {
                "operationId": "Test",
                "responses": {
                    "200": {
                        "schema": { "type": "object" }
                    }
                }
            }
        }
    }
}
```
Generated code:
```c#
public interface IDefaultApi
{
    InlineResponse200 Test ();
}

public class InlineResponse200 : IEquatable<InlineResponse200>
{
    public bool Equals(InlineResponse200 other)
    {
        if (other == null)
            return false;
        return ;
    }
}
```
Expected:
```c#
public interface IDefaultApi
{
    object Test();
}
```

**Comment by wing328** [comment] 2015-11-30 15:12
`"schema": { "type": "object" }` (a model without any properties) is not identical to Object in C#. Can you give an example of what the response (payload) looks like?

For the return statement without any boolean value, that's caused by a model without any properties. I'll submit a PR to improve that later.

**Comment by artem-dudarev** [comment] 2015-12-01 12:36
We have the following API resource:
/settings/{name}/value

It returns the value for the requested variable. Since variables have different value types we have declared the response type as object.

Here are some value types and API responses (type: response):
boolean: true
decimal: 13.00
integer: 30
string: "checkout/terms"

**Comment by wing328** [comment] 2015-12-01 14:23
What about modelling the response as "string" (instead of "object") and then you can cast the response into different type?

**Comment by wing328** [comment] 2016-01-23 07:56
@artem-dudarev closing the issue for now. Please pull the latest and let us know if it's still an issue.

**Closed by wing328** 2016-01-23 07:56 UTC
Labels: Client: C-Sharp
