### ISSUE TITLE
"-" and "_" got removed when generating nodejs server code

### ISSUE THREAD

**Issue by DaFrik** [swagger-api/swagger-codegen#2409] opened 2016-03-18 10:51 UTC
Hi,

Thanks for creating swagger and the server codegen.

while i was trying to generate node js server code from a swagger file, i found that all the "-" and "_" in my swagger file got removed in the generated node js server code, I have to manually change the code to make it work. 

May I know is it intended behavior or there is limitation on the sets of characters allowed in a swagger file?

Look forward to hearing from you.

Best Regards,
D

**Comment by wing328** [comment] 2016-03-18 11:57
@DaFrik  Can you please share the spec so that we can reproduce the issue?

**Comment by DaFrik** [comment] 2016-03-21 04:40
@wing328 , thanks for quick reply. I have attached the trim downed swagger that you can reproduce the problem. (github didnt support uploading *.yaml file, thus please rename the .txt file name to .yaml).

From the swagger yaml file you can see that "operationId" is "listUsingGET_5" ,  and "x-swagger-router-controller" is "Hrv-controller". 

After using the swagger codegen to generate nodejs code, what i got is a "Hrvcontroller.js" and "HrvcontrollerService.js" and within which there are some functions with name "listUsingGET5", I got no problem bring up the node.js server, but when i start querying the endpoint I got error message "Cannot resolve the configured swagger-router handler: Hrv-controller_listUsingGET_5". 

I can make the code work but going back to my swagger file and change the "operationId" to  "listUsingGET5" and changing "x-swagger-router-controller" to "Hrvcontroller". 

[swagger.txt](https://github.com/swagger-api/swagger-codegen/files/181684/swagger.txt)

**Comment by wing328** [comment] 2016-03-29 14:58
@DaFrik thanks for the details. I think this issue is similar to https://github.com/swagger-api/swagger-codegen/issues/2302

I've filed https://github.com/swagger-api/swagger-codegen/pull/2466 to fix the operationId issue. I wonder if you can perform a test to see if the PR fixes the issue for you.

**Comment by wing328** [comment] 2016-03-30 06:30
@DaFrik here are some more update.

@nickform confirmed that the fix works for him.

For the controller naming issue (Hrv-controller), what should the JS code looks like that would work for "Hrv-controller" ?

If you can show me a working version for "Hrv-controller", it should not be hard for me to plot it back to the mustache template.

**Comment by DaFrik** [comment] 2016-04-08 02:03
Dear @wing328

Thanks for your update. I was trying to find the branch of your commit
"https://github.com/swagger-api/swagger-codegen/pull/2466" to test it
, but I cannot find it from the repo of

swagger-api/swagger-codegen

I am new to the github admin / operation thing, could show me how i
can get your committed code so I can do a test ?

Thanks,

**Comment by wing328** [comment] 2016-04-08 03:51
You can find it under my folk of swagger-codegen: https://github.com/wing328/swagger-codegen.git

**Comment by DaFrik** [comment] 2016-04-08 11:10
@wing328  
checkout your branch and did some testing locally, the problem is still there, you can get my branch

https://github.com/DaFrik/swagger-codegen-buggy

I have write the gen script at ./bin/nodejs-hrv-server.sh 

after i the code being generated and I start node

i tested the api from http://localhost:8080/docs/

I typed in some random value in the required param and then I submit.

and the result is

> Error: Cannot resolve the configured swagger-router handler: Hrv-controller_listUsingGET_5<br>

**Comment by wing328** [comment] 2016-04-08 11:16
@DaFrik I think the PR only addresses one of the issues you mentioned.

For the controller naming issue (Hrv-controller), what should the JS code looks like that would work for "Hrv-controller" ?

If you can show me a working version for "Hrv-controller", it should not be hard for me to plot it back to the mustache template.

**Comment by wing328** [comment] 2016-04-09 10:55
FYI. #2466 merged into master.

**Comment by DaFrik** [comment] 2016-04-11 02:56
@wing328 

I find a fundamental limitation in javascript to my problem. As Javascript dont allow "-" as variable name, therefore, there shouldn't been any "-" in the "x-swagger-router-controller", as in my current swagger.yaml , i used 

> x-swagger-router-controller: "Hrv-controller"

 , i need to change that into sth without "-"

Howover, for 

> operationId: "listUsingGET_5"

 , the "_" is a valid js variable name characters, but it still got striped off, could you fix that problem?

**Comment by wing328** [comment] 2016-04-21 15:55
#2655 merged into master. Not sure if that fixes the issue but would recommend you to pull the latest and give it a try.

**Comment by wing328** [comment] 2016-07-07 08:11
@DaFrik closing this as there's no update. Please let us know if you still need help on this with the latest master version of swagger codegen.

**Closed by wing328** 2016-07-07 08:11 UTC
Labels: Bug, Server: Nodejs
