### ISSUE TITLE
volley android client does not compile because of Responses.BooleanResponse

### ISSUE THREAD

**Issue by kungfoo** [swagger-api/swagger-codegen#1901] opened 2016-01-15 15:42 UTC
It seems there is an interface that is not generated in `Responses`:

````java
public void isRunning (final Responses.BooleanResponse responseListener,
  final Response.ErrorListener errorListener) {}
````

This code is generated into one of the API classes, yet `Responses.BooleanResponse` does not exist. I think it is missing from the generator.

**Comment by wing328** [comment] 2016-01-16 04:59
@Shyri I wonder if you can take a look when you've time.

**Comment by Shyri** [comment] 2016-01-16 23:03
@kungfoo This should've been fixed in #1839 . I removed Reponses class and now it should generate methods using volley response listener, `Response.Listener<Boolean>` in this case. 

Please make sure you have those changes in your local copy. If so, ¿could you please write an example of your json file specification for that method?

**Comment by kungfoo** [comment] 2016-01-18 07:16
I used 2.1.5 from maven central. I can check if the problem persists if I
build from the master branch.

**Comment by kungfoo** [comment] 2016-01-18 09:35
Hmm, I can't seem  to build from source using `mv package` as quoted in the docs. I get the following error on swagger-codegen (core):

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.18.1:test (default-test) on project swagger-codegen: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.18.1:test failed: There was an error in the forked process
[ERROR] java.lang.NoClassDefFoundError: org/scalatest/Matchers
[ERROR] at java.lang.ClassLoader.defineClass1(Native Method)
[ERROR] at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
[ERROR] at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
[ERROR] at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
[ERROR] at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
[ERROR] at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
[ERROR] at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
[ERROR] at java.security.AccessController.doPrivileged(Native Method)
[ERROR] at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
[ERROR] at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[ERROR] at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
[ERROR] at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[ERROR] at org.apache.maven.surefire.util.DefaultScanResult.loadClass(DefaultScanResult.java:131)
[ERROR] at org.apache.maven.surefire.util.DefaultScanResult.applyFilter(DefaultScanResult.java:95)
[ERROR] at org.apache.maven.surefire.junit4.JUnit4Provider.scanClassPath(JUnit4Provider.java:222)
[ERROR] at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:107)
[ERROR] at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
[ERROR] at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
[ERROR] at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
[ERROR] Caused by: java.lang.ClassNotFoundException: org.scalatest.Matchers
[ERROR] at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
[ERROR] at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[ERROR] at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
[ERROR] at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
```

**Comment by wing328** [comment] 2016-01-19 07:36
@kungfoo can you try `mvn clean install -U` to see if the error goes away?

**Comment by kungfoo** [comment] 2016-01-19 07:42
The error actually went away after cleaning every thing. So far so good.
2.1.6-snapshot also work in the way that the Response interface is no
longer generated.

**Comment by wing328** [comment] 2016-01-19 07:47
OK. Glad to hear the problem is resolved.

Issue closed.

**Closed by wing328** 2016-01-19 07:47 UTC
Labels: Bug, Client: Android
