### ISSUE TITLE
--template-dir completely ignored by nodejs-server generator.

### ISSUE THREAD

**Issue by enbits** [swagger-api/swagger-codegen#9941] opened 2019-12-19 03:14 UTC
##### Description

Can not use custom templates on nodejs-server code generation. 
##### Swagger-codegen version

3.0.14

##### Swagger declaration file content or url
Tested with the default petstore and several other with the same result. 

##### Command line used for generation

- `swagger-codegen generate -i petstore.json -l nodejs-server -t ./templates --template-engine mustache`
##### Steps to reproduce
Run the following commands
- `wget http://petstore.swagger.io/v2/swagger.json`
- `mkdir templates`
- `swagger-codegen generate -i swagger.json -l nodejs-server -t ./templates --template-engine mustache`

Expected Result: 
- Should return error because no templates files are found

Actual Result:
- Code is generated, completely ignoring the templates folder. If any template file is included inside the folder (e.g. service.mustache), it is also ignored.

A test with another language to verify that other languages work:

Run the following command:
- `swagger-codegen generate -i swagger.json -l javascript -t ./templates --template-engine mustache`

Result:
`ERROR io.swagger.codegen.v3.templates.MustacheTemplateEngine - javascript/model.mustache (No such file or directory)`

**That is the expected result** because there is no model.mustache inside the templates. 

##### Suggest a fix/enhancement

It caught my attention that in the resources folder there is a `nodejs` folder but not a `nodejs-server` folder; not sure if that's the issue, but there's definitely something fishy going on:

[https://github.com/swagger-api/swagger-codegen/tree/master/modules/swagger-codegen/src/main/resources/nodejs](https://github.com/swagger-api/swagger-codegen/tree/master/modules/swagger-codegen/src/main/resources/nodejs
)

**Comment by alarm9k** [comment] 2020-02-12 13:36
This also applies to typescript-fetch.

**Comment by philippelacoste** [comment] 2020-02-27 14:56
Should be solved fixing NodeJSServerCodegen as done in AbstractCSharpCodegen 
>  l.293 : 
 embeddedTemplateDir = templateDir = getTemplateDir();
>should be change to ;
if (StringUtils.isBlank(templateDir)) {
            embeddedTemplateDir = templateDir = getTemplateDir();
}

>Then generation with specific template dir should then be fully functionnal

**Comment by hkosova** [comment] 2020-03-30 17:55
Duplicate of #8904

**Comment by HugoMario** [comment] 2020-08-14 04:44
this has been fixed by [swagger-codegen-generators#710](https://github.com/swagger-api/swagger-codegen-generators/pull/710) for codegen v3

**Closed by HugoMario** 2020-08-14 04:44 UTC
