### ISSUE TITLE
Exclude model tests?

### ISSUE THREAD

**Issue by webron** [swagger-api/swagger-codegen#2506] opened 2016-04-06 15:09 UTC
_From @langdonx on April 6, 2016 15:8_

The new test generation stuff in 2.1.6 is nice (using `csharp`).  Is there a way to exclude the generation of model tests though?  I'm only wanting tests generated for the Api classes.

_Copied from original issue: swagger-api/swagger.io#95_

**Comment by langdonx** [comment] 2016-04-06 15:12
Sorry, not sure how I filed it under swagger.io.

**Comment by wing328** [comment] 2016-04-07 02:22
@langdonx Is it correct to say that the test for models are working fine (passed without issue)?

**Comment by langdonx** [comment] 2016-04-07 12:03
They should pass (I've not actually tried them), however since all the models are just auto-implemented properties, the tests are effectively useless.

Perhaps some folks are going into the generated code and changing it, but to me, that defeats the purpose of being able to generate (and re-generate) as the REST service grows and changes over time.  Obviously you'll generate the tests once and start building it, but this suggested change might improve that.

Rather than exclude them with an argument, if they were organized by namespace, it would be easier to manage.  As it is now, I end up with 155 files in a directory and have to copy out all `*ApiTests.cs` files.

Also, it's interesting to note that the files get created inside of a directory called `..Test`.  The double dot makes the directory completely hidden from Visual Studio even if you show hidden files in Solution Explorer.

**Comment by wing328** [comment] 2016-04-10 15:50
I'll try to reproduce the issue you mentioned in Windows.

My view on the test cases is that we should just leave it there to cover the model test so as to allow owners to add more test cases if needed (since the model class is partial, which means it can be extended easily)

**Comment by wing328** [comment] 2016-04-13 08:51
@langdonx I did a test on Windows and the test files are generated in a separate folder.

Let's say my output folder is set to e:\Petstore. The test files are created in the folder e:\Petstore.Test\

Are you using the latest version? Please do a `mvn clean package` to recompile the jar.

**Comment by langdonx** [comment] 2016-04-13 11:44
Sorry, I should have included more information from the start.  I made a batch file and can reproduce it as simple as:

    wget http://repo1.maven.org/maven2/io/swagger/swagger-codegen-cli/2.1.6/swagger-codegen-cli-2.1.6.jar -O swagger-codegen-cli.jar
    java -jar swagger-codegen-cli.jar generate -i http://petstore.swagger.io/v2/swagger.json -l csharp

GIF:

![swagger-codegen](https://cloud.githubusercontent.com/assets/441982/14492158/757f1238-014b-11e6-8739-8631073667a1.gif)

**Comment by wing328** [comment] 2016-04-13 12:27
@langdonx thanks for the gif, which is very useful in understanding the issue. Can you try using the `-o` to specify the output folder?
e.g. `-o c:\tmp\swagger_client\"

**Comment by langdonx** [comment] 2016-04-13 12:55
I used `-o .\XXX` and that gave me `XXX.Test`. :)

**Comment by wing328** [comment] 2016-04-13 13:01
Please use that as a workaround for the time being. We'll fix that to put the test files in a proper location even though `-o output_folder` is not provided.

**Comment by langdonx** [comment] 2016-04-13 13:21
Realizing this is not a priority, you also get `..Test` if you use `-o .\`.

**Comment by jimschubert** [comment] 2016-05-14 01:16
@langdonx any way you could test this against master? I restructured the csharp client, and I believe I fixed this issue with that change. I'm looking at allowing a parameter to be passed via CLI to disable generation of model/api tests and documentation. But I'll have some thorough testing to do since this would have an effect on all generators.

**Comment by wing328** [comment] 2016-05-16 15:12
@langdonx the PR from @jimschubert has been merged into master. Please pull the latest master and give it a try.

**Closed by wing328** 2016-05-16 15:12 UTC
Labels: Bug, Client: C-Sharp, Enhancement

**Comment by langdonx** [comment] 2016-05-23 17:55
@wing328 @jimschubert looks good, much cleaner.

**Comment by jimschubert** [comment] 2016-05-23 18:28
@langdonx I also added support for an ignore file in #2899. If you find other files that need to be excluded to prevent overwrite, that should allow for everything.
