### ISSUE TITLE
[CodeGen] boolean values from JSON are treated as strings

### ISSUE THREAD

**Issue by yohanakh** [swagger-api/swagger-codegen#4228] opened 2016-11-21 11:57 UTC
##### Description

Boolean values from JSON are treated as string. I believe this happens in every language as it is in the generator code.

This applies to dynamicProperties and additionalProperties.

##### Swagger-codegen version

I am using the latest code in master branch with commit 1968bead432aac0adbf3cc576758947bf0803e11 (21/11/2016).

##### Swagger declaration file content or url

```json
{
        ...
	"java8": false
}
```

##### Command line used for generation

swagger-codegen generate -l spring -i api-v1.yaml -o rest -c config.json

##### Steps to reproduce

1. Run the generate command with the JSON above.
2. Open the generated rest/pom.xml file and note that the java.version property is 1.8 instead of 1.7

##### Related issues

#3318

##### Suggest a Fix

1. Change the value types in additionalProperties and dynamicProperties to Object instead of String.
2. Change methods that insert values to these maps to receive Object as the type of the value instead of String. 

I already have a fix and updated the existing tests to cover it.
https://github.com/yohanakh/swagger-codegen/tree/issue-4228

And created a pull request: 
https://github.com/swagger-api/swagger-codegen/pull/4229

**Comment by wing328** [comment] 2016-12-06 17:28
@yohanakh thanks for the PR. Are you referring to those boolean value in the config.json not being parsed correctly?

**Comment by yohanakh** [comment] 2016-12-06 17:58
@wing328 yes, the boolean values in config.json

**Comment by wing328** [comment] 2016-12-16 04:00
PR merged into master. Please pull the latest.

Thanks for your contribution.

**Comment by yohanakh** [comment] 2016-12-18 09:48
Thank you!
When are you planning to release v2.2.2 ?

**Comment by wing328** [comment] 2016-12-18 10:20
We're targeting Jan/Feb 2017

**Comment by yohanakh** [comment] 2016-12-18 10:44
That's great! Thanks.
Should I close this issue ?

**Comment by wing328** [comment] 2016-12-18 12:09
Yes please ( I thought I did )

**Closed** 2016-12-18 13:17 UTC
Labels: Issue: Bug

**Comment by frol** [comment] 2017-03-07 21:47
I cannot follow the logic behind the fix because I am not a Java dev, but it seems that it broke the native boolean types in JSON config:

Having this config for Javascript client:

```json
{
  "usePromises": true
}
```

and running Swagger Codegen like this:

```
$ java -jar /opt/swagger-codegen/modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate --input-spec ./swagger.json --lang javascript --output ./dist --config ./config.json
```

I receive a bunch of odd errors. It starts with this one:

```
[main] INFO io.swagger.parser.Swagger20Parser - reading from ./swagger.json
[main] WARN io.swagger.codegen.ignore.CodegenIgnoreProcessor - Directory does not exist, or is inaccessible. No file will be evaluated.
Exception in thread "main" java.lang.ClassCastException: java.lang.Boolean cannot be cast to java.lang.String
        at io.swagger.codegen.languages.JavascriptClientCodegen.processOpts(JavascriptClientCodegen.java:231)
        at io.swagger.codegen.DefaultGenerator.configureGeneratorProperties(DefaultGenerator.java:127)
        at io.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:653)
        at io.swagger.codegen.cmd.Generate.run(Generate.java:234)
        at io.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:41)
```

OK, I created the `./dist` folder (though it wasn't required before, and as turned out, it is still not required; it is just a side effect). So I run Swagger Codegen again (with no changes in the arguments), and here is the new error:

```
[main] INFO io.swagger.parser.Swagger20Parser - reading from ./swagger.json
[main] INFO io.swagger.codegen.ignore.CodegenIgnoreProcessor - No .swagger-codegen-ignore file found.
Exception in thread "main" java.lang.ClassCastException: java.lang.Boolean cannot be cast to java.lang.String
        at io.swagger.codegen.languages.JavascriptClientCodegen.processOpts(JavascriptClientCodegen.java:231)
        at io.swagger.codegen.DefaultGenerator.configureGeneratorProperties(DefaultGenerator.java:127)
        at io.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:653)
        at io.swagger.codegen.cmd.Generate.run(Generate.java:234)
        at io.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:41)
```

O_O, OK, I created an empty `.swagger-codegen-ignore` and run Swagger Codegen the third time, and here is now the root cause:

```
[main] INFO io.swagger.parser.Swagger20Parser - reading from ./swagger.json
Exception in thread "main" java.lang.ClassCastException: java.lang.Boolean cannot be cast to java.lang.String
        at io.swagger.codegen.languages.JavascriptClientCodegen.processOpts(JavascriptClientCodegen.java:231)
        at io.swagger.codegen.DefaultGenerator.configureGeneratorProperties(DefaultGenerator.java:127)
        at io.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:653)
        at io.swagger.codegen.cmd.Generate.run(Generate.java:234)
        at io.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:41)
```

If change the `config.json` wrapping `true` into string, the client is generated just fine! Thus, here is my working config:

```json
{
  "usePromises": "true"
}
```

**Comment by wing328** [comment] 2017-03-08 07:46
I'll look into this today. Let's use https://github.com/swagger-api/swagger-codegen/issues/4960 for tracking.

**Comment by wing328** [comment] 2017-03-08 09:25
FYI. #4960 has been fixed.
