### ISSUE TITLE
[JAVA] Undocumented custom template behaviour change when migrating from 2.x -> 3.x

### ISSUE THREAD

**Issue by dgibson-microfocus** [swagger-api/swagger-codegen#9893] opened 2019-11-26 10:12 UTC
##### Description

When using 2.x the okhttp-gson generator and specifying a custom template directory it would fallback to the bundled defaults if not found. 

In 3.x this no longer happens and you must provide all templates in the custom directory.

##### Swagger-codegen version

2.2.3 -> 3.0.14

##### Steps to reproduce

Specify a template directory with just one override mustache file (e.g. ApiClient.mustache), a FileNotFoundException will be thrown for /{customDir}/model.mustache.

**Comment by hkosova** [comment] 2020-03-30 17:54
Duplicate of #8904

**Comment by HugoMario** [comment] 2020-08-14 04:44
this has been fixed by [swagger-codegen-generators#710](https://github.com/swagger-api/swagger-codegen-generators/pull/710) for codegen v3

**Closed by HugoMario** 2020-08-14 04:44 UTC
