### ISSUE TITLE
[csharp] Illegal constructor generated by latest version from head

### ISSUE THREAD

**Issue by bluemmc** [swagger-api/swagger-codegen#2481] opened 2016-04-01 10:47 UTC
I have retrived and build the latest version from main branch. When generating java code it works, but when generating c# code, some constructors of domain classes are wrong as an extra comma "," is added after last parameter to the constructor which results in illegal, uncompileable, code. F.x. I get a constructor signature like this "public Employee(EmployeeId Id = null, )" in c#. It only happens for some domain objects however and I have not been able to pinpoint why/when it happens.

**Comment by wing328** [comment] 2016-04-01 11:37
@bluemmc thanks for reporting the issue. Do you mind sharing the spec with me to easily reproduce the issue?

**Comment by bluemmc** [comment] 2016-04-01 12:04
[swagger.txt](https://github.com/swagger-api/swagger-codegen/files/199552/swagger.txt)

Here is a swagger.json file. Look in the generated Employee domain class for the error.

**Comment by wing328** [comment] 2016-04-01 12:21
Thanks for the spec. I could repeat the issue.

```
  Employee:
    required:
      - id
    type: object
    properties:
      id:
        $ref: '#/definitions/EmployeeId'
        readOnly: true
      name:
        maxLength: 10
        minLength: 0
        type: string
        readOnly: true
      lastUpdated:
        format: date-time
        type: string
        readOnly: true
```
Given that all attributes are `readOnly`, the constructor should take no argument. Is that what you expected?

**Comment by adam-smoulder** [comment] 2016-04-01 12:27
I actually came across this same bug but with a DateTime default being set in a constructor to null (which can't compile; I just manually switched out null with default(DateTIme) for the moment). Do you want me to get the part of my spec that would have this also?

**Comment by wing328** [comment] 2016-04-01 12:30
Yes please

**Comment by adam-smoulder** [comment] 2016-04-01 12:39
[cSharpDateTimeNull-swagger-spec.txt](https://github.com/swagger-api/swagger-codegen/files/199605/cSharpDateTimeNull-swagger-spec.txt)

BirthDate and SetupDate are fields in the Patient object definition in the API. Within the generated Patient.cs (in models) this has the following constructor signature:

public Patient(string PatientId = null, string OrgId = null, DateTime BirthDate = **null**, string FirstName = null, string LastName = null, GenderEnum? Gender = null, DateTime SetupDate = **null,** PatientContact Contact = null, PatientLocation Location = null, List<PolicyInfo> Policies = null, List<PatientClinicianUser> Clinicians = null)

^that should be line 60 or so

Let me know if you need any more info or anything

**Comment by wing328** [comment] 2016-04-01 12:55
@adam-smoulder using the latest master, I didn't get any compile error. Are you using the latest master to generate the API client?

**Comment by wing328** [comment] 2016-04-01 12:59
@bluemmc a property should not be both 'required' and `readyOnly`:
```
Relevant only for Schema "properties" definitions. Declares the property as "read only". This means that it MAY be sent as part of a response but MUST NOT be sent as part of the request. Properties marked as readOnly being true SHOULD NOT be in the required list of the defined schema. Default value is false.
```
Ref: https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#fixed-fields-13

so the property `id` in the spec (for model `Employee`) needs to be updated in the spec.

**Comment by bluemmc** [comment] 2016-04-01 13:30
@wing328 Thanks for the tip. I was not aware of the special meaning of required/readonly for swagger. The spec is generated from immutable c# classes where all data is set in the constructor and properties are readonly. I am off to vacation and can't experiment right now but hopefully I can configure swashbuckle/ahoy to set the properties correctly for my immutable server side classes. 

In any case, I think that  swagger-codegen should not omit the extra ",". Maybe the generated constructor by swagger-codegen should provide all the arguments even if the properties are readonly (like for my server side objects) but I need to look more at the details of readonly/required/etc when I am back at the office.

**Comment by wing328** [comment] 2016-04-01 13:32
For the extra ",", it's definitely an issue and I'm working on it.

Please enjoy your vacation and let's sync up on this issue when you're back.

**Comment by adam-smoulder** [comment] 2016-04-01 13:39
I just got the latest master and tried again; it seems the issue is resolved (the DateTimes are nullable now). Sorry for the trouble and thanks for your help!

**Comment by wing328** [comment] 2016-04-01 13:46
@adam-smoulder no problem. Stable release v2.1.6 will be released soon.

**Comment by wing328** [comment] 2016-04-01 14:45
@bluemmc FYI. I've submitted #2484 to address the issue.

**Closed** 2016-04-09 13:14 UTC
Labels: Bug, Client: C-Sharp

**Comment by wing328** [comment] 2016-04-11 07:19
@bluemmc  PR merged into master. Please pull the latest and let us know if you still face the same issue.
