### ISSUE TITLE
JavaScript: Errornous generation of content type values containing "="

### ISSUE THREAD

**Issue by arikon** [swagger-api/swagger-codegen#2919] opened 2016-05-20 08:10 UTC
##### Description

swagger-codegen produces such a code in API call methods:

```js
      var contentTypes = ['application/json; charset&#x3D;utf-8'];
      var accepts = ['application/json; charset&#x3D;utf-8'];
```

The expected code is:

```js
      var contentTypes = ['application/json; charset=utf-8'];
      var accepts = ['application/json; charset=utf-8'];
```

The part of spec source is:

```yaml
consumes:
  - "application/json; charset=utf-8"

produces:
  - "application/json; charset=utf-8"
```

##### Swagger-codegen version

Latest master. Not sure if it is a regression.

##### Swagger declaration file content or url

https://gist.github.com/arikon/2f078fcf15aae07984c7e1d35def90bf

##### Command line used for generation

```sh
SWAGGER_JSON=swagger-new.json
SWAGGER_OUTPUT=sandbox-json-api

export JAVA_HOME=$(/usr/libexec/java_home -v 1.7)
export PATH=${JAVA_HOME}/bin:$PATH

java -jar swagger-codegen/modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate \
    -i ${SWAGGER_JSON} \
    -l javascript \
    -o ${SWAGGER_OUTPUT} \
    --additional-properties usePromises=true
```

**Comment by wing328** [comment] 2016-05-20 09:33
@arikon thanks for reporting the issue, which will be addressed by #2920

**Comment by wing328** [comment] 2016-05-20 10:13
@arikon fix merged into master. Please pull the latest and give it a try.

**Comment by arikon** [comment] 2016-05-20 13:51
@wing328 It doesn't help =(

**Comment by arikon** [comment] 2016-05-20 13:54
@wing328 It should be fixed here also https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/Javascript/api.mustache#L77-L78

**Comment by wing328** [comment] 2016-05-20 13:56
@arikon you're right. I missed that due to the fact that it's not using the typical {{mediaType}} mustache tag. Another PR on the way to address it.

**Comment by arikon** [comment] 2016-05-20 13:59
@wing328 Is it on purpose (different syntax)?

**Comment by wing328** [comment] 2016-05-20 14:01
If the language itself uses a lot of {{ or }}, then mustache allows you to map {{ and }} to something else to avoid confusion.

I did a check and found only Javascript and Clojure map <, > with {{, }} respectively.

**Comment by arikon** [comment] 2016-05-20 14:39
@wing328 As I know, JS does not use a lot of `{{` and `}}`. It uses `{` and `}`, but Java also does and does not switch to alternative syntax.

I tried to look into `Javascript/api.mustache` to fix some bugs. But found it very confusing because of non-standard syntax. And editors (e.g. IntelliJ IDEA and WebStorm) do not support it.

**Comment by wing328** [comment] 2016-05-20 14:49
@arikon if switching the delimiter (<) back to `{{` makes your life easier in terms of contributing bug fixes, we can definitely do that.

cc other JS contributors: @xhh @demonfiddler @delenius

**Comment by wing328** [comment] 2016-05-20 14:49
Btw, I opened ask a question on how to use `{{{.}}}` (unescape value) after switching the delimiter: https://github.com/samskivert/jmustache/issues/78

**Comment by wing328** [comment] 2016-05-21 08:22
@arikon I filed #2930 to fix the mediaType. I did some tests and confirmed the fix.

**Comment by arikon** [comment] 2016-05-23 09:53
@wing328 It worked for me too. Thank you!

**Closed** 2016-05-23 09:53 UTC
Labels: Bug, Client: Javascript
