### ISSUE TITLE
[Client: typescript-angular] Array with OneOff generates Array<ModelObject>, but ModelObject is not defined.

### ISSUE THREAD

**Issue by Frakes** [swagger-api/swagger-codegen#10384] opened 2020-07-13 14:55 UTC
Hallo @HugoMario!

You wanted a new issue. Here it comes:

V3.0.20 still generating unneeded import
`import { ModelObject } from '../model/modelObject';`
  build error TS2307: Cannot find module '../model/modelObject'.

Can you please fix this?

Many thanks, Mark

_Originally posted by @kanguran in https://github.com/swagger-api/swagger-codegen/issues/8372#issuecomment-585444518_

**Comment by asdftu** [comment] 2020-07-23 02:34
[client: Javascript] also has this issue

**Comment by HugoMario** [comment] 2020-07-23 06:56
thanks for reporting it @Frakes .

jus tassigned to myself

**Comment by JasonFreeberg** [comment] 2020-08-12 23:44
I am having the same problem with the JavaScript client. There is an `import ModelObject from './ModelObject';` on some model definitions, but it is actually never used.

**Comment by yacineblr** [comment] 2020-10-08 09:15
any update ?

**Comment by chinkan** [comment] 2021-05-14 02:24
any updates?

**Comment by AlexanderKlement** [comment] 2021-06-08 11:21
I experienced the same issue and was also not able to find a solution.
The issue still persists to 3.0.26. I even tried the latest snapshot 3.0.27-20210606.140618-8

an update would really be appreciated

**Comment by HugoMario** [comment] 2021-06-27 05:32
Hey @AlexanderKlement 
Can you please share what oas3 definition you use to reproduce the issue?

I tried with this one https://gist.github.com/codessentials/7122ab4a8e37a8621f9c4546d9d382a4
But it worked fine

**Comment by AlexanderKlement** [comment] 2021-06-27 08:28
Hey @HugoMario 

yes of course: [openapi.json](https://gist.github.com/AlexanderKlement/274b9d1e62717db31ca67f96eaa7906a)

I was not 100% sure my json is correct, but a conversion on https://editor.swagger.io/ does not produce an error. Therefore i assume it is correct. Using this [npm package](https://www.npmjs.com/package/openapi-typescript-angular-generator) i was able to generate a working api. So i am thinking the problem is on my end.

I started a new project from scratch, carefully following the instructions, to see where i could have messed up:
On calling `npm install` i was unable to resolve the dependency tree: I am using angular 12, therefore i am required a typescriptversion >= 4.2.3 < 4.3.0. 
Las week, i may raised the typescript version manually. Could this be the reason I am getting this error?

**Comment by HugoMario** [comment] 2021-06-30 15:06
hey guys,

this was fixed on recent releases. Please try with [latest version](https://repo1.maven.org/maven2/io/swagger/codegen/v3/swagger-codegen-cli/3.0.27/swagger-codegen-cli-3.0.27.jar)

Going to close this issue, but in case you still got this issue or a similar one, please let me know and i'll reopen it to work on it.

**Closed by HugoMario** 2021-06-30 15:06 UTC

**Comment by louiealmeda** [comment] 2021-07-25 15:10
Hello @HugoMario,

I've tried generating with the latest version (3.0.27) and it is still generating and using
`import { ModelObject } from '../model/modelObject';` but the `/model/modelObject` does not exist.

Thank you.

**Comment by olemarius** [comment] 2022-05-09 16:42
I'm getting this on `swagger-codegen-cli generate -l typescript-axios ...` 

version:
`"swagger-nodegen-cli": "^3.0.34",`

```
18:39:02.932 [Thread-1] WARN  i.s.c.v.g.DefaultCodegenConfig - String to be sanitized is null. Default to Object
18:39:02.934 [Thread-1] WARN  i.s.c.v.g.t.AbstractTypeScriptClientCodegen - Object (model name matches existing language type) cannot be used as a model name. Renamed to ModelObject
... 
```
