### ISSUE TITLE
JavaClient: Array of Enums generated as List<String>

### ISSUE THREAD

**Issue by bedag-moo** [swagger-api/swagger-codegen#1283] opened 2015-09-23 16:39 UTC
If a model contains an array of enums, the java client code generator emits a property of type `List<String>` rather than `List<TheEnum>` 

**Testcase**

The model

    "Issue" : {
      "id" : "Issue",
      "properties" : {
        "id" : {
          "type" : "string"
        },
        "version" : {
          "type" : "integer",
          "format" : "int64"
        },
        "subject" : {
          "type" : "string"
        },
        "status" : {
          "type" : "string",
          "enum" : [ "open", "inProgress", "resolved", "closed" ]
        },
        "availableTransitions" : {
          "type" : "array",
          "items" : {
            "type" : "string",
            "enum" : [ "startProgress", "stopProgress", "resolve", "reopen", "close" ]
          }
        }
      }
    },

causes the following code to be generated:

    /**
     **/
    @ApiModelProperty(value = "")
    @JsonProperty("status")
    public StatusEnum getStatus() {
      return status;
    }
    public void setStatus(StatusEnum status) {
      this.status = status;
    }
 
    /**
     **/
    @ApiModelProperty(value = "")
    @JsonProperty("availableTransitions")
    public List<String> getAvailableTransitions() {
      return availableTransitions;
    }
    public void setAvailableTransitions(List<String> availableTransitions) {
      this.availableTransitions = availableTransitions;
    }

As you can see, the code generator recognizes the enum for the property `status`, but not for `availableTransitions`.

**Comment by cbornet** [comment] 2015-09-24 07:00
Duplicate of #1222 ? Can you try with the master branch ?

**Comment by bedag-moo** [comment] 2015-09-24 13:26
My issue occurred with yesterday's master branch, so it has not been resolved by the fix to 1222.

**Comment by xhh** [comment] 2015-09-25 07:32
Hey, I just tried it in master and it worked for me, generating the following Java class:

```java
package io.swagger.client.model;

import io.swagger.client.StringUtil;
import java.util.*;



import io.swagger.annotations.*;
import com.fasterxml.jackson.annotation.JsonProperty;


@ApiModel(description = "")
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2015-09-25T15:22:34.945+08:00")
public class Issue   {
  
  private String id = null;
  private Long version = null;
  private String subject = null;

public enum StatusEnum {
  OPEN("open"),
  INPROGRESS("inProgress"),
  RESOLVED("resolved"),
  CLOSED("closed");

  private String value;

  StatusEnum(String value) {
    this.value = value;
  }

  @Override
  public String toString() {
    return value;
  }
}

  private StatusEnum status = null;

public enum AvailableTransitionsEnum {
  STARTPROGRESS("startProgress"),
  STOPPROGRESS("stopProgress"),
  RESOLVE("resolve"),
  REOPEN("reopen"),
  CLOSE("close");

  private String value;

  AvailableTransitionsEnum(String value) {
    this.value = value;
  }

  @Override
  public String toString() {
    return value;
  }
}

  private List<AvailableTransitionsEnum> availableTransitions = new ArrayList<AvailableTransitionsEnum>();

  
  /**
   **/
  @ApiModelProperty(value = "")
  @JsonProperty("id")
  public String getId() {
    return id;
  }
  public void setId(String id) {
    this.id = id;
  }

  
  /**
   **/
  @ApiModelProperty(value = "")
  @JsonProperty("version")
  public Long getVersion() {
    return version;
  }
  public void setVersion(Long version) {
    this.version = version;
  }

  
  /**
   **/
  @ApiModelProperty(value = "")
  @JsonProperty("subject")
  public String getSubject() {
    return subject;
  }
  public void setSubject(String subject) {
    this.subject = subject;
  }

  
  /**
   **/
  @ApiModelProperty(value = "")
  @JsonProperty("status")
  public StatusEnum getStatus() {
    return status;
  }
  public void setStatus(StatusEnum status) {
    this.status = status;
  }

  
  /**
   **/
  @ApiModelProperty(value = "")
  @JsonProperty("availableTransitions")
  public List<AvailableTransitionsEnum> getAvailableTransitions() {
    return availableTransitions;
  }
  public void setAvailableTransitions(List<AvailableTransitionsEnum> availableTransitions) {
    this.availableTransitions = availableTransitions;
  }

  

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class Issue {\n");
    
    sb.append("    id: ").append(StringUtil.toIndentedString(id)).append("\n");
    sb.append("    version: ").append(StringUtil.toIndentedString(version)).append("\n");
    sb.append("    subject: ").append(StringUtil.toIndentedString(subject)).append("\n");
    sb.append("    status: ").append(StringUtil.toIndentedString(status)).append("\n");
    sb.append("    availableTransitions: ").append(StringUtil.toIndentedString(availableTransitions)).append("\n");
    sb.append("}");
    return sb.toString();
  }
}
```

Could you try it again by first running `mvn clean package` at the root directory of swagger-codegen to get the latest build?

**Comment by bedag-moo** [comment] 2015-09-25 18:18
I just did, same result as before. Very weird.

Perhaps this is related to swagger 1.2 compatibility? Here is the exact swagger spec I am feeding the generator:

service.json:

    {
      "swaggerVersion" : "1.2",
      "apiVersion" : "1",
      "basePath" : "/apidocs",
      "apis" : [{
        "path" : "/issue.{format}"
      } ]
    }

issue.json:

    {
      "apiVersion" : "1",
      "swaggerVersion" : "1.2",
      "basePath" : "/api",
      "resourcePath" : "/issue",
      "apis" : [ {
        "path" : "/issue",
        "operations" : [ {
          "method" : "POST",
          "nickname" : "createIssue",
          "type" : "Issue",
          "parameters" : [ {
            "type" : "IssueEditCommand",
            "paramType" : "body",
            "name" : "issue",
            "required" : true
          } ],
          "summary" : "Creates a new issue, and returns it."
        } ]
      }, {
        "path" : "/issue/assignedToMe",
        "operations" : [ {
          "method" : "GET",
          "nickname" : "getAssignedToMe",
          "type" : "array",
          "items" : {
            "$ref" : "Issue"
          },
          "summary" : "Returns a list of issues assigned to the current user."
        } ]
      }, {
        "path" : "/issue/reportedByMe",
        "operations" : [ {
          "method" : "GET",
          "nickname" : "getReportedByMe",
          "type" : "array",
          "items" : {
            "$ref" : "Issue"
          },
          "summary" : "Returns a list of issues reported by the current user."
        } ]
      }, {
        "path" : "/issue/{id}",
        "operations" : [ {
          "method" : "POST",
          "nickname" : "updateIssue",
          "type" : "Issue",
          "parameters" : [ {
            "type" : "string",
            "paramType" : "path",
            "name" : "id",
            "required" : true
          }, {
            "type" : "IssueEditCommand",
            "paramType" : "body",
            "name" : "issue",
            "required" : true
          } ],
          "summary" : "Updates an existing issue."
        } ]
      }, {
        "path" : "/issue/{id}/status",
        "operations" : [ {
          "method" : "POST",
          "nickname" : "perform",
          "type" : "Issue",
          "parameters" : [ {
            "type" : "string",
            "paramType" : "path",
            "name" : "id",
            "required" : true
          }, {
            "type" : "IssueTransitionCommand",
            "paramType" : "body",
            "name" : "cmd",
            "required" : true
          } ],
          "summary" : "Performs the given transition."
        } ]
      } ],
      "models" : {
        "Ref" : {
          "id" : "Ref",
          "properties" : {
            "id" : {
              "type" : "string"
            }
          }
        },
        "IssueTransitionCommand" : {
          "id" : "IssueTransitionCommand",
          "properties" : {
            "issueId" : {
              "type" : "string"
            },
            "transition" : {
              "type" : "string",
              "enum" : [ "startProgress", "stopProgress", "resolve", "reopen", "close" ]
            }
          }
        },
        "Issue" : {
          "id" : "Issue",
          "properties" : {
            "id" : {
              "type" : "string"
            },
            "version" : {
              "type" : "integer",
              "format" : "int64"
            },
            "reporter" : {
              "type" : "User"
            },
            "assignee" : {
              "type" : "User"
            },
            "subject" : {
              "type" : "string"
            },
            "description" : {
              "type" : "string"
            },
            "status" : {
              "type" : "string",
              "enum" : [ "open", "inProgress", "resolved", "closed" ]
            },
            "availableTransitions" : {
              "type" : "array",
              "items" : {
                "type" : "string",
                "enum" : [ "startProgress", "stopProgress", "resolve", "reopen", "close" ]
              }
            }
          }
        },
        "User" : {
          "id" : "User",
          "properties" : {
            "id" : {
              "type" : "string"
            },
            "version" : {
              "type" : "integer",
              "format" : "int64"
            },
            "openId" : {
              "type" : "string"
            },
            "fullName" : {
              "type" : "string"
            },
            "role" : {
              "type" : "string",
              "enum" : [ "system", "admin", "developer", "user" ]
            }
          },
          "required" : [ "openId", "fullName", "role" ]
        },
        "IssueEditCommand" : {
          "id" : "IssueEditCommand",
          "properties" : {
            "id" : {
              "type" : "string"
            },
            "version" : {
              "type" : "integer",
              "format" : "int64"
            },
            "subject" : {
              "type" : "string"
            },
            "description" : {
              "type" : "string"
            },
            "assignee" : {
              "type" : "Ref"
            }
          }
        }
      }
    }

**Comment by xhh** [comment] 2015-09-26 12:23
I tried it with swagger 1.2 and could reproduce the issue.
It should be related to SwaggerCompatConverter that converts swagger spec of 1.2 to 2.0

**Comment by cbornet** [comment] 2015-09-26 12:43
I have a solution : don't use swagger 1.2 ;-)

**Comment by bedag-moo** [comment] 2015-09-28 13:05
@cbornet: That is not easy: the spec is generated by https://github.com/teamcarma/swagger-jaxrs-doclet, which does not yet support Swagger 2.0 ...

**Comment by fehguy** [comment] 2015-09-28 14:23
Can you please open an issue in the [swagger-parser](https://github.com/swagger-api/swagger-parser) project?  This should be supported, and the codegen uses this project to convert 1.2 specs.

**Closed by fehguy** 2015-09-28 14:23 UTC
