### ISSUE TITLE
Referencing .yml files fails

### ISSUE THREAD

**Issue by PumpMagic** [swagger-api/swagger-codegen#3305] opened 2016-07-06 01:05 UTC
##### Description

Attempting to reference .yml files fails, at least when using references as path item objects.

##### Swagger-codegen version

2.1.6

##### Swagger declaration file content or url

(Assuming `./paths/endpointanalysis-url.yml` contains a path item object, though its contents may not matter):

```yaml
swagger: '2.0'
host: 'api.example.com'
basePath: '/v1'
consumes:
  - application/json
produces:
  - application/json

info:
  version: "1.0.0"
  title: Example API

paths:
  /endpointAnalysis/url:
    $ref: './paths/endpointanalysis-url.yml'
```

##### Command line used for generation

`swagger-codegen generate -i test.yml -l swift -o gen/swift`

##### Steps to reproduce

1. Reference a path item object with a .yml extension
1. Run swagger-codegen
1. Watch swagger-codegen crash with the following error:

```
[main] INFO io.swagger.parser.Swagger20Parser - reading from test.yml
Exception in thread "main" java.lang.RuntimeException: An exception was thrown while trying to deserialize the contents of ./paths/endpointanalysis-url.yml into type class io.swagger.models.Path
	at io.swagger.parser.util.DeserializationUtils.deserialize(DeserializationUtils.java:54)
	at io.swagger.parser.ResolverCache.loadRef(ResolverCache.java:102)
	at io.swagger.parser.processors.PathsProcessor.processPaths(PathsProcessor.java:55)
	at io.swagger.parser.SwaggerResolver.resolve(SwaggerResolver.java:40)
	at io.swagger.parser.SwaggerParser.read(SwaggerParser.java:66)
	at io.swagger.codegen.config.CodegenConfigurator.toClientOptInput(CodegenConfigurator.java:383)
	at io.swagger.codegen.cmd.Generate.run(Generate.java:221)
	at io.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:36)
Caused by: com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'post': was expecting ('true', 'false' or 'null')
 at [Source: post: (snip)
```

#### Other

@ron from #swagger suggested that files with any extension should be supprted:
`@ron
pumpmagic: and you should totally open a ticket on the codegen asking to support pretty much anything (because the file extension is meaningless)`

**Comment by pradeepkumarreddyk** [comment] 2016-07-06 10:41
I too have the same problem.  my swagger files are as follows :
1)  swagger.yml
swagger: '2.0'
info:
  title: Krayon API
  description: Krayon Server API
  version: 1.0.0
host: '192.168.1.5:8080'
schemes:
  - http
basePath: /krayon/api/v1/framework
produces:
  - application/json
paths:
  /module:
    get:
      summary: module types
      description: krayon server module
      parameters:
        - name: args
          in: query
          description: Name of module unit.
          required: true
          type: string
          format: string
      tags:
        - module
      responses:
        '200':
          description: ResponseTO object
          schema:
            $ref: '#/definitions/lxlresponse'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
definitions:
  lxlresponse:
    type: object
    properties:
      errorCode:
        type: integer
        description: errorCode to identify the type of the error.
      response:
        type: array
        items:
          $ref: 'module.yml'
      requestId:
        type: integer
        description: id of request
      toClassName:
        type: string
        description: absolute path of class ModuleItemTO
      operationType:
        type: string
        description: type of operation
      search:
        type: string
        description: search false or true
      validateSession:
        type: string
        description: validateSession true or false
  Error:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      fields:
        type: string
  module:
    $ref: './module.yml'

2) module.yml
 type: object
 properties:
    moduleUnitName:
        type: string
        description: name of module unit
    moduleUnits:
        type: integer
        description: number of module units
    isModule:
        type: string
        description: isModule true or false
    moduleItem:
        $ref: './moduleItem.yml'

3)moduleItem.yml

 type: object
 properties:
   moduleItemName:
     type: string
     description: module item name
   moduleItemUnits:
     type: integer
     description: number of module item units


$ java -jar swagger-codegen-cli.jar generate -i swagger.yml -l android --library=volley  -o  generated_source_code                    


[main] INFO io.swagger.parser.Swagger20Parser - reading from swagger.yml
Exception in thread "main" java.lang.RuntimeException: An exception was thrown while trying to deserialize the contents of ./module.yml into type interface io.swagger.models.Model
        at io.swagger.parser.util.DeserializationUtils.deserialize(DeserializationUtils.java:54)
        at io.swagger.parser.ResolverCache.loadRef(ResolverCache.java:102)
        at io.swagger.parser.processors.ExternalRefProcessor.processRefToExternalDefinition(ExternalRefProcessor.java:26)
        at io.swagger.parser.processors.ModelProcessor.processRefModel(ModelProcessor.java:92)
        at io.swagger.parser.processors.ModelProcessor.processModel(ModelProcessor.java:33)
        at io.swagger.parser.processors.DefinitionsProcessor.processDefinitions(DefinitionsProcessor.java:40)
        at io.swagger.parser.SwaggerResolver.resolve(SwaggerResolver.java:41)
        at io.swagger.parser.SwaggerParser.read(SwaggerParser.java:66)
        at io.swagger.codegen.config.CodegenConfigurator.toClientOptInput(CodegenConfigurator.java:383)
        at io.swagger.codegen.cmd.Generate.run(Generate.java:221)
        at io.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:36)
Caused by: com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'type': was expecting 'null', 'true', 'false' or NaN
 at [Source:  type: object
 properties:
    moduleUnitName:
        type: string
        description: name of module unit
    moduleUnits:
        type: integer
        description: number of module units
    isModule:
        type: string
        description: isModule true or false
    moduleItem:
        $ref: './moduleItem.yml'; line: 1, column: 6]
        at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1419)
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:508)
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._reportInvalidToken(ReaderBasedJsonParser.java:2300)
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._reportInvalidToken(ReaderBasedJsonParser.java:2277)
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._matchToken(ReaderBasedJsonParser.java:2129)
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._matchTrue(ReaderBasedJsonParser.java:2080)
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:651)
        at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:3105)
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3051)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2161)
        at io.swagger.parser.util.DeserializationUtils.deserialize(DeserializationUtils.java:48)
        ... 10 more

**Comment by pradeepkumarreddyk** [comment] 2016-07-06 11:11
i too have the same issue. I have three swagger spec files : swagger.yml, module.yml, moduleItem.yml

contents of swagger.yml are as follows:-
--------------------------------------------------------
`swagger: '2.0'
info:
  title: Krayon API
  description: Krayon Server API
  version: 1.0.0
host: '192.168.1.5:8080'
schemes:
  - http
basePath: /krayon/api/v1/framework
produces:
  - application/json
paths:
  /module:
    get:
      summary: module types
      description: krayon server module
      parameters:
        - name: args
          in: query
          description: Name of module unit.
          required: true
          type: string
          format: string
      tags:
        - module
      responses:
        '200':
          description: ResponseTO object
          schema:
            $ref: '#/definitions/lxlresponse'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
definitions:
  lxlresponse:
    type: object
    properties:
      errorCode:
        type: integer
        description: errorCode to identify the type of the error.
      response:
        type: array
        items:
          $ref: '#/definitions/module'
      requestId:
        type: integer
        description: id of request
      toClassName:
        type: string
        description: absolute path of class ModuleItemTO
      operationType:
        type: string
        description: type of operation
      search:
        type: string
        description: search false or true
      validateSession:
        type: string
        description: validateSession true or false
  Error:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      fields:
        type: string
  module:
    $ref: './module.yml'`


contents of module.yml are as follows:-
-----------------------------------------------------
` type: object
 properties:
    moduleUnitName:
        type: string
        description: name of module unit
    moduleUnits:
        type: integer
        description: number of module units
    isModule:
        type: string
        description: isModule true or false
    moduleItem:
        $ref: './moduleItem.yml'`


contents of moduleItem.yml are as follows:-
----------------------------------------------------------
` type: object
 properties:
   moduleItemName:
     type: string
     description: module item name
   moduleItemUnits:
     type: integer
     description: number of module item units`


Output of swagger-codegen is as follows:-
---------------------------------------------------------

$ java -jar swagger-codegen-cli.jar generate -i swagger.yml -l android --library=volley  -o  generated_source_code

[main] INFO io.swagger.parser.Swagger20Parser - reading from swagger.yml
Exception in thread "main" java.lang.RuntimeException: An exception was thrown while trying to deserialize the contents of ./module.yml into type interface io.swagger.models.Model
        at io.swagger.parser.util.DeserializationUtils.deserialize(DeserializationUtils.java:54)
        at io.swagger.parser.ResolverCache.loadRef(ResolverCache.java:102)
        at io.swagger.parser.processors.ExternalRefProcessor.processRefToExternalDefinition(ExternalRefProcessor.java:26)
        at io.swagger.parser.processors.ModelProcessor.processRefModel(ModelProcessor.java:92)
        at io.swagger.parser.processors.ModelProcessor.processModel(ModelProcessor.java:33)
        at io.swagger.parser.processors.DefinitionsProcessor.processDefinitions(DefinitionsProcessor.java:40)
        at io.swagger.parser.SwaggerResolver.resolve(SwaggerResolver.java:41)
        at io.swagger.parser.SwaggerParser.read(SwaggerParser.java:66)
        at io.swagger.codegen.config.CodegenConfigurator.toClientOptInput(CodegenConfigurator.java:383)
        at io.swagger.codegen.cmd.Generate.run(Generate.java:221)
        at io.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:36)
Caused by: com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'type': was expecting 'null', 'true', 'false' or NaN
 at [Source:  type: object
 properties:
    moduleUnitName:
        type: string
        description: name of module unit
    moduleUnits:
        type: integer
        description: number of module units
    isModule:
        type: string
        description: isModule true or false
    moduleItem:
        $ref: './moduleItem.yml'; line: 1, column: 6]
        at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1419)
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:508)
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._reportInvalidToken(ReaderBasedJsonParser.java:2300)
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._reportInvalidToken(ReaderBasedJsonParser.java:2277)
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._matchToken(ReaderBasedJsonParser.java:2129)
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._matchTrue(ReaderBasedJsonParser.java:2080)
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:651)
        at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:3105)
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3051)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2161)
        at io.swagger.parser.util.DeserializationUtils.deserialize(DeserializationUtils.java:48)
        ... 10 more

**Comment by wing328** [comment] 2016-07-07 07:41
@PumpMagic I don't think that's supported by Swagger Parser at the moment.

Please define the `paths` in the spec itself instead of using `$ref`

**Comment by PumpMagic** [comment] 2016-07-08 02:29
Thanks for the quick response, @wing328 . Would you like me to file this as an issue over there?

**Comment by tomekc** [comment] 2016-07-29 22:42
Let me chime in, and confirm that is a regression. I have personal fork based on repository state from mid-April 2016 and referenced YAML were supported and worked like charm.

Now I switched to master to see what's new and while I get no errors,
my model classes are empty, i.e. have no fields.

Example fragment of spec:

```
paths:
  /oauth/token:
    $ref: ./endpoints/oauth_token.yaml
```

and referenced YML contains what's usually under path key.

Unfortunately I have no clue where to look at.

**Comment by fehguy** [comment] 2016-07-29 22:48
Agreed.  The parser regressed to be picky around the extension--`.yml` does not currently work but `.yaml` does.  Please follow https://github.com/swagger-api/swagger-parser/issues/276 for details.

**Comment by tomekc** [comment] 2016-07-29 22:58
But, well, I actually have all files with `.yaml` extension. All endpoints and models are externalized to files.

Endpoint code is correct, model classes are created, and example YAML file is

```
properties:
  addressLine:
    type: string
  zip:
    type: string
  city:
    type: string
  state:
    type: string
  country:
    type: string
  location:
    type: string
```

Which is referenced like:

```
definitions:
  Address:
    $ref: ./definitions/Address.yaml
```

It worked great in code from ~3 months ago.
Maybe I missed something that changed?

**Comment by fehguy** [comment] 2016-07-29 23:11
OK that is something different then.  Can you try really quick without the `./`?  It should work with it but I do know that we have relative links working fine in the parser.

**Comment by tomekc** [comment] 2016-07-29 23:52
No difference. I also experimentally changed filename to non-existent one with... same result. No error nor warning.

I got codegen under debugger and found one interesting thing, when enabled `debugSwagger` property:

```json
"definitions" : {
    "OAuthTokens" : {
      "$ref" : "#/definitions/definitions/OAuthTokens.yaml"
    },
    "PingResponse" : {
      "$ref" : "#/definitions/definitions/PingResponsezzzz.yaml"
    },
    "Address" : {
      "$ref" : "#/definitions/Address"
    },
```

Those with doubled `definitions` component are ones with `./` removed.

**Comment by fehguy** [comment] 2016-07-30 00:09
OK thanks for trying.  Please follow the parser issue, I'm going to try to get to that tonight or over the weekend.

**Comment by tomekc** [comment] 2016-07-30 00:16
Thanks! I have a couple of contributions wishing to submit, but first I need to get this straight:)

Meanwhile, I found interesting snippet at 
io/swagger/codegen/DefaultCodegen.java:1181

```java
        } else if (model instanceof RefModel) {
            // TODO
        } else if (model instanceof ComposedModel) {
```

May this be a hint? :-]

**Comment by tomekc** [comment] 2016-07-30 21:18
I solved the issue by reverting swagger-parser to 1.0.19 (as used in previous release). @fehguy @wing328  Build is passing; do you mind doing it (or me submitting a PR :))?

**Comment by fehguy** [comment] 2016-10-27 21:15
This should be fixed by https://github.com/swagger-api/swagger-codegen/pull/4094/commits/92af2cf8211a61291547eee137fdddaf862495e1

**Closed by fehguy** 2016-10-27 21:15 UTC
Labels: Issue: Bug, Swagger-Parser

**Comment by AlskiOnTheWeb** [comment] 2017-02-08 11:49
Even in 2.2.2-SNAPSHOT of the code generator I'm seeing this fail. How did it get closed?

**Comment by ifreecarve** [comment] 2017-04-25 02:00
I also have the problem where swagger `2.2.2` (installed via homebrew) tries to use a JSON parser for a yaml file.


```
$ swagger-codegen version
2.2.2
$ swagger-codegen generate -i swagger.yaml -l ruby
[main] INFO io.swagger.parser.Swagger20Parser - reading from swagger.yaml
[main] INFO io.swagger.parser.Swagger20Parser - reading from swagger.yaml
[main] ERROR io.swagger.parser.SwaggerCompatConverter - failed to read resource listing
com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'swagger': was expecting ('true', 'false' or 'null')
 at [Source: swagger.yaml; line: 1, column: 9]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1702)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:558)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._reportInvalidToken(UTF8StreamJsonParser.java:3524)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._handleUnexpectedValue(UTF8StreamJsonParser.java:2686)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._nextTokenNotInObject(UTF8StreamJsonParser.java:878)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.nextToken(UTF8StreamJsonParser.java:772)
	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:3834)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3783)
	at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:2431)
	at io.swagger.parser.SwaggerCompatConverter.readResourceListing(SwaggerCompatConverter.java:189)
	at io.swagger.parser.SwaggerCompatConverter.read(SwaggerCompatConverter.java:116)
	at io.swagger.parser.SwaggerParser.read(SwaggerParser.java:74)
	at io.swagger.codegen.config.CodegenConfigurator.toClientOptInput(CodegenConfigurator.java:419)
	at io.swagger.codegen.cmd.Generate.run(Generate.java:232)
	at io.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:41)
[main] INFO io.swagger.codegen.ignore.CodegenIgnoreProcessor - No .swagger-codegen-ignore file found.
Exception in thread "main" java.lang.RuntimeException: missing swagger input or config!
	at io.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:651)
	at io.swagger.codegen.cmd.Generate.run(Generate.java:234)
	at io.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:41)
```

`swagger.yaml` first 2 lines:
```yaml
swagger: '2.0'
info:
```

All my `$ref`s are in the form

```yaml 
   $ref: '#/definitions/Error'
```

**Comment by ginere** [comment] 2017-09-13 11:42
+1

**Comment by ifreecarve** [comment] 2017-09-13 12:55
My error turned out to be related to an errant tab in a string (not indentation) within my YAML file.  `yaml2json` does not choke in this way, and swagger-codegen should not be failing YAML parsing silently.

Reported as https://github.com/swagger-api/swagger-codegen/issues/6490
