### ISSUE TITLE
[JAVA] Bug generating equals method for a child class with no additional field

### ISSUE THREAD

**Issue by loictro** [swagger-api/swagger-codegen#7355] opened 2018-01-10 10:44 UTC
##### Description
The generated equals method for a class that has no additional field and that inherits from another does not call the equals method of the parent class.
Such a class can be weird but it is used for semantic purpose.

##### Swagger-codegen version
2.3.0

##### Swagger declaration file content

```yaml
Video:
    type: object
    description: Video information (Abstract class)
    properties:
          channelId:
            type: string
            description: The Live channel identifier which broadcasted the video
          duration:
            type: integer
            format: int64
            description: Duration in seconds  
Movie:
    description: Movie information
    allOf:
      - $ref: '#/definitions/Video'
Episode:
    description: Episode information
    allOf:
      - $ref: '#/definitions/Video'
      - properties:
          episodeNumber:
            type: integer
            format: int64
            description: The episode number in the season
```

The generated equals method of the Movie class is 
```java
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    return true;
  }
```
##### Command line used for generation

swagger-codegen generate -i swagger.yaml -l spring

##### Steps to reproduce

It can be reproduced using the provided swagger model.

##### Suggest a fix/enhancement

It can be fixed by modifying the pojo.mustache template file.

**Comment by cbornet** [comment] 2018-01-19 23:33
Movie and Episode don’t have a parent class (since you don’t have a discriminator). They should have their own fields copied from Video and compare them in the equals() method.

**Comment by rj90** [comment] 2019-05-23 18:16
I created pull request for that.
https://github.com/swagger-api/swagger-codegen/pull/9462

**Comment by roman-sinyakov** [comment] 2020-03-10 10:05
Another simple use case  with array type and no properties causes this issue to be reproduced:
**API definition**
```yaml
Characteristics:
  type: array
  items:
    $ref: "#/definitions/Characteristic"
```

**Java class** with "equals()" method generated without "super":
```java
public class Characteristics extends ArrayList<Characteristic> {
    ....
    public boolean equals(Object var1) {
        if (this == var1) {
            return true;
        } else {
            return var1 != null && this.getClass() == var1.getClass();
        }
    }
    ...
}
```

**Comment by Luharkk** [comment] 2021-03-29 17:15
I am also facing this issue which @loictro mentioned.
I am using the below plugin dependency in my pom.xml
`<build>
        <plugins>
            <plugin>
                <groupId>org.openapitools</groupId>
                <artifactId>openapi-generator-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </build>`
Any idea when this issue will be fixed??

**Comment by khocef** [comment] 2021-08-23 11:03
I have the same issue with subclass with only a list

**Closed** 2022-01-14 17:48 UTC
