### ISSUE TITLE
shouldn't the fact a property of a schema object is required reflect in the model object itself?

### ISSUE THREAD

**Issue by altmky** [swagger-api/swagger-codegen#2116] opened 2016-02-11 20:26 UTC
For example in the Java binding, we do have the annotation that indicates the property is required, but if I'm not mistaken you can still not set it and call the API without the model object warning you you have not provided a required property?

For swift binding the property could be a regular one instead of being a swift optional property to force the user of the API to provide it?

**Comment by wing328** [comment] 2016-02-15 06:38
Can you please elaborate on the issue by giving an example?

**Comment by altmky** [comment] 2016-02-16 17:36
Sorry for not being clear. I meant that with petstore, despite Pet `name` being "required", I can do:

```java
        Pet pet = new Pet();
        pet.setId(newPetId);
        // name commented out
        // pet.setName("profiler");
        pet.setStatus(Pet.StatusEnum.AVAILABLE);
        pet.setPhotoUrls(Arrays.asList("http://profiler.com"));

        PetApi.add(pet);
```
without the client-side API complaining about me creating an incomplete (wrt Swagger spec) model object (no `name`).

I guess there are several ways to deal with that, one being to force required parameters in the model object constructor? (and in Swift you could use mandatory field for that, instead of optional one as you use now for everything?)

I hope this is clearer.

**Comment by wing328** [comment] 2016-02-21 03:29
@altmky thanks for the details. Currently, [`name`](https://github.com/swagger-api/swagger-codegen/blob/master/samples/client/petstore/swift/PetstoreClient/Classes/Swaggers/Models/Pet.swift#L21) in Pet is defined as
``
    public var name: String?
```
How would you modify it to make it mandatory in Swift?

**Comment by Edubits** [comment] 2016-02-21 09:59
In most situations it would be great if the model uses required properties where possible, it will save you quite some Optional unwrapping when using it. However a potential concern with making properties required in the generated API model is update API calls. These regularly work by just sending the properties which should change (and being merged on the server side), this situation wouldn't be possible if properties are required on the client side.

**Comment by wing328** [comment] 2016-02-21 13:31
I think we need to update the following [lines](https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/swift/model.mustache#L20-L21):
```
    {{#vars}}{{#isEnum}}{{#description}}/** {{description}} */
    {{/description}}public var {{name}}: {{{datatypeWithEnum}}}{{^unwrapRequired}}?{{/unwrapRequired}}{{#unwrapRequired}}{{^required}}?{{/required}}{{#required}}!{{/required}}{{/unwrapRequired}}{{#defaultValue}} = {{{defaultValue}}}{{/defaultValue}}{{/isEnum}}{{^isEnum}}{{#description}}/** {{description}} */
    {{/description}}public var {{name}}: {{{datatype}}}{{^unwrapRequired}}?{{/unwrapRequired}}{{#unwrapRequired}}{{^required}}?{{/required}}{{#required}}!{{/required}}{{/unwrapRequired}}{{#defaultValue}} = {{{defaultValue}}}{{/defaultValue}}{{/isEnum}}
    {{/vars}}
```
as I couldn't find any mustache tab/variable for `unwrapRequired` (and that's why there's always `?` for all model properties)

Let's say we remove `?` from the [`name`](https://github.com/swagger-api/swagger-codegen/blob/master/samples/client/petstore/swift/PetstoreClient/Classes/Swaggers/Models/Pet.swift#L21) property in the Pet model. I think we also need to update the default constructor as well

Anyone has a clue how the default constructor should be updated (using the `Pet` model as an example)?

**Comment by larslockefeer** [comment] 2016-02-24 09:21
In that case `name` should be provided as a parameter to the constructor and assigned to the `name` property, otherwise the class won't compile. Hence:

```
init(name: String) {
  self.name = name
}
```

Such a parameter would have to be added for each non-optional property of the model.

**Comment by wing328** [comment] 2016-02-24 09:51
@larslockefeer thanks for suggesting the change. May I know if you've cycle to contribute a fix?

Ref: https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md

**Comment by bobrosoft** [comment] 2016-03-03 14:19
Try this patch out [patch.txt](https://github.com/swagger-api/swagger-codegen/files/156889/patch.txt) I done Unit Tests with newly generated models on my project -- all passed and models looks correct, no explicit initialization needed in `init` method.

Possibly patch is not full, I deleted some `{{unwrapRequired}}` stuff but it's still there below in `encodeToJSON` method. Speaking truly, I dunno where `{{unwrapRequired}}` defined (if at all) and what it doing. Also, recommend to mark `encodeToJSON` method as `public` — need that in some places where need to prepare JSON payloads manually (patched our company fork for it) to pass them as strings.

**Comment by wing328** [comment] 2016-03-03 15:19
@bobrosoft thanks! Do you mind submitting a PR for the change? just want to make sure the credit goes back to your github account.

Ref: https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md

**Comment by bobrosoft** [comment] 2016-03-03 16:14
@wing328 can do tomorrow. Btw, do you know somebody who knows about `{{unwrapRequired}}` to properly check PR? Maybe it been needed for something important there.

**Comment by wing328** [comment] 2016-03-03 16:16
I think it can be removed as I don't see any other reference to it. Please feel free to remove it.

**Comment by wing328** [comment] 2016-03-03 16:40
Sorry I was wrong. `unwrapRequired` can be specified in the config:
```
	unwrapRequired
	    Treat 'required' properties in response as non-optional (which would crash the app if api returns null as opposed to required option specified in json schema
```
(java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar config-help -l swift)

**Comment by bobrosoft** [comment] 2016-03-03 16:50
Oh, ok, makes sense now, then that patch not needed and that can be controlled through config. Issue can be closed.

For others: when `generate` there's possibility to specify JSON config file with `-c` option. To make models use "required" properties, you can set `unwrapRequired` property to true, as `{"unwrapRequired": true, ....<your other options>}` in config file for swift generator. To list all available options use:
`java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar config-help -l swift`

**Comment by altmky** [comment] 2016-03-09 10:07
@bobrosoft not exactly I think. If you use unwrapRequired, you will get an implicitly unwrapped optional type (! postfix) not a required type (no postfix)? And yes it will crash the app if the value has not been provided (on the contrary of the optional type), but this won't force it at compilation time like a true required field would?

Also my issue was broader than that. All languages might be subject to this, even when  they don't have native required types (you can "fake" that by forcing the value to passed in a ctor for example).

I guess @Edubits said this is not possible to do, because in some cases people rely on the fact the required value is not here on the client-side for updates. But this seems to contradict a bit the Swagger spec.

**Comment by harryblam** [comment] 2016-04-12 14:46
has there been any progress on this? I have been looking into it, and have got up to the point of propergating non-optional Swift properties, but am having trouble creating a custom init method with more than one property. For example

`    public init(prop1: String, prop2: String) {
        self.prop1 = prop1
        self.prop2 = prop2
    }`

Would be:
`     public init({{#vars}}{{#isEnum}}{{#required}}{{name}}: {{{datatypeWithEnum}}},{{/required}}{{/isEnum}}{{^isEnum}}{{#required}}{{name}}: {{{datatype}}},{{/required}}{{/isEnum}}{{/vars}}) {
        
        {{#vars}}{{#required}}self.{{name}} = {{name}}{{/required}}{{/vars}}
     }
`

The problem is with the trailing commas in the parameter list! Any thoughts?

**Comment by cjolif** [comment] 2016-04-12 16:36
that one is tricky. I think the mustache engine that swagger-codegen is using has extensions that allows you to deal with that. See: https://github.com/samskivert/jmustache#-first-and--last

**Comment by harryblam** [comment] 2016-04-13 15:54
That worked nicely thanks @cjolif . Now just having problems further up the chain...

**Comment by fabdslv** [comment] 2016-04-18 15:01
I just made a PR for this issue, the attributes will be required only when using 'unwrapRequired' mode.

**Closed** 2016-04-27 05:32 UTC
Labels: Client: Swift
