### ISSUE TITLE
Cannot generate more than one specified file

### ISSUE THREAD

**Issue by mythofcode** [swagger-api/swagger-codegen#2846] opened 2016-05-12 15:13 UTC
**Issue**:

* If either -Dmodels or -DsupportingFiles is used, only the last specification is generated.
* In addition, if -Dmodels is the last, then only the first specified model class is generated.

**Expected**:

Any combination of -Dmodels, -Dapi and -DsupportingFiles should be supported in one execution. All specified model classes should be generated.

**Comment by mythofcode** [comment] 2016-05-14 21:05
This feature is currently documented, so in principle, it is a bug.

**Comment by jimschubert** [comment] 2016-06-18 15:43
@mythofcode The documentation states:

> The default is generate everything supported by the specific library. Once you enable a feature, it will restrict the contents generated

The generator in current master follows this logic:

```
// The default is generate everything supported by the specific library
if all three options are null, default them to true
// Once you enable a feature, it will restrict the contents generated
else default any null options them to false
```

I've checked and [`generateModels`](https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultGenerator.java#L217), [`generateApis`](https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultGenerator.java#L366), and [`generateSupportingFiles`](https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultGenerator.java#L517) are all separate conditional statements.

It's possible that this bug existed in 2.1.6 and was fixed. Can you test against master? If you continue to have issues, can you provide the command line including the switches you've used?

Heres an example command against master, which generates supportingFiles and apis:
```
java -DsupportingFiles -Dapis \
    -jar ./modules/swagger-codegen-cli/target/swagger-codegen-cli.jar  \
    generate -i modules/swagger-codegen/src/test/resources/2_0/petstore-with-fake-endpoints-models-for-testing.yaml \
    -l csharp \
    -o ~/issues/swagger-codegen/2846
```
Verify with `ls -las ~/issues/swagger-codegen/2846/` and `ls -las ~/issues/swagger-codegen/2846/src/IO.Swagger/`

I'm unable to reproduce your issue.

Note, however, that `supportingFiles`, `apis`, and `models` all support passing a CSV of items to generate. If you inadvertently provide true, e.g. `-Dapis=true`, you're saying to generate an api named 'true'. We may want to have a check on this string option before splitting for apis, models, or files to generate.

Can you test the above and verify?

**Comment by wing328** [comment] 2016-07-13 10:26
@mythofcode closing this as there's no update. Please test as suggested by @jimschubert above and let us know if you still experience issues.

**Closed by wing328** 2016-07-13 10:26 UTC
Labels: Enhancement
