### ISSUE TITLE
nodejs generator : /docs doesnt show all operations

### ISSUE THREAD

**Issue by mohsen1** [swagger-api/swagger-codegen#652] opened 2015-04-16 17:07 UTC
Hi all and thanks for this great job !,
I know that embeded generators are in alpha stage but I have just noticed the following behavior : 
with nodejs generated code, UI (with /docs) shows only the last operation for each path.

for exemple : 
```
- /pet 
  - GET 
  - PUT 
```

the unique operation shown will be the PUT
Thx !

**Comment by Cooker-Monster** [comment] 2015-04-21 09:46
hi all,
I still can't figure out what's going on with /docs : even with Petstore sample, the behaviour is strange.
Does anyone can confirm please (very straigthforward to test) ? 
IE, only DELETE verbe is visible on UI with /users/{username} though GET/PUT are defined ...
there is a __deep impact__ on the service side behavior too : the __getUserByName__ funtion __is not routed__ : 
"Error: Route defined in Swagger specification (/users/{username}) but there is no defined get operation."
I'm wondering if it's a swagger-tools issue ?
Any help is warm welcomed !
![missing](https://cloud.githubusercontent.com/assets/3295362/7249604/cfb86230-e81b-11e4-9523-0b9c1155ae8e.png)

**Comment by webron** [comment] 2015-05-04 07:56
@Cooker-Monster - how do you run the sample? Notice it says at the top that you need to use `special-key` as the API key, so some of the operations may be hidden.

**Comment by Cooker-Monster** [comment] 2015-05-04 13:07
@webron  : thx for the answer
I followed this process : 
- 1: take petstore sample (petstore_full.yaml) into editor (editor.swagger.io)
- 2 : generate the code (node.js)
- 3: run the code (localhost).
There is no security set on /users/{username} path+methods so, I don't think this is a special-key matter.

**Comment by webron** [comment] 2015-05-04 13:15
So basically this is a duplicate of #667?

**Comment by Cooker-Monster** [comment] 2015-05-04 13:27
maybe or maybe not ! 
I could be the same origin but not the same destination : 
- the first one is an explorer view issue
- the second one is a generation code issue

**Comment by webron** [comment] 2015-05-04 13:30
But do you see those operations generated? Because if not, it's no wonder they are not visible.

**Comment by Cooker-Monster** [comment] 2015-05-04 13:47
Yes, they are generated ... it's just the link between function and path this is not done ...

**Comment by webron** [comment] 2015-05-04 13:49
Can you share the output of `/api-docs/user` or `/api-docs/User` from the generated application?

**Comment by Cooker-Monster** [comment] 2015-05-04 14:03
I don't catch it, sorry : ther is no /api-docs available (only /docs) !

**Comment by webron** [comment] 2015-05-04 14:05
Looking at your screenshot, it says `http://localhost:8080/api-docs`.

**Comment by Cooker-Monster** [comment] 2015-05-04 14:11
yes but this is not relevant. anyway, api-docs/user or User gives "Cant' read swagger JSON from http://localhost:8080/api-docs/User" 
I have just check it now with a new generation of the petstore api ... sorry !

**Comment by Cooker-Monster** [comment] 2015-05-04 18:55
Going further, I have set debug to see what's going on (hope it will help !). 

Let's focus on User Paths &  Controler (for practical reason) :
- path /users/{username} is found
- controler User.js have among its methods : "getUserByName" and "deleteUser"

This is the middleware init steps full log : 
<<
  swagger-tools:middleware:metadata Initializing swagger-metadata middleware +0ms
  swagger-tools:middleware:metadata   Identified Swagger version: 2.0 +3ms
  swagger-tools:middleware:metadata   Found Path: /users +6ms
  swagger-tools:middleware:metadata   Found Path: /users/createWithArray +1ms
  swagger-tools:middleware:metadata   Found Path: /users/createWithList +0ms
  swagger-tools:middleware:metadata   Found Path: /users/login +0ms
  swagger-tools:middleware:metadata   Found Path: /users/logout +1ms
  swagger-tools:middleware:metadata   Found Path: /users/{username} +0ms
  swagger-tools:middleware:metadata   Found Path: /stores/order +0ms
  swagger-tools:middleware:metadata   Found Path: /stores/order/{orderId} +0ms
  swagger-tools:middleware:metadata   Found Path: /pets +0ms
  swagger-tools:middleware:metadata   Found Path: /pets/findByStatus +1ms
  swagger-tools:middleware:metadata   Found Path: /pets/findByTags +0ms
  swagger-tools:middleware:metadata   Found Path: /pets/{petId} +0ms
  swagger-tools:middleware:validator Initializing swagger-validator middleware +0ms
  swagger-tools:middleware:validator   Response validation: disabled +1ms
  swagger-tools:middleware:router Initializing swagger-metadata middleware +0ms
  swagger-tools:middleware:router   Mock mode: disabled +1ms
  swagger-tools:middleware:router   Controllers: +1ms
  swagger-tools:middleware:router     /somewhere/Sandbox/nodejs-server/controllers/Pet.js: +2ms
  swagger-tools:middleware:router       Pet_updatePet +0ms
  swagger-tools:middleware:router       Pet_addPet +0ms
  swagger-tools:middleware:router       Pet_findPetsByStatus +1ms
  swagger-tools:middleware:router       Pet_findPetsByTags +0ms
  swagger-tools:middleware:router       Pet_getPetById +0ms
  swagger-tools:middleware:router       Pet_updatePetWithForm +0ms
  swagger-tools:middleware:router       Pet_deletePet +0ms
  swagger-tools:middleware:router     /somewhere/Sandbox/nodejs-server/controllers/PetService.js: +0ms
  swagger-tools:middleware:router       PetService_updatePet +0ms
  swagger-tools:middleware:router       PetService_addPet +0ms
  swagger-tools:middleware:router       PetService_findPetsByStatus +0ms
  swagger-tools:middleware:router       PetService_findPetsByTags +0ms
  swagger-tools:middleware:router       PetService_getPetById +0ms
  swagger-tools:middleware:router       PetService_updatePetWithForm +1ms
  swagger-tools:middleware:router       PetService_deletePet +0ms
  swagger-tools:middleware:router     /somewhere/Sandbox/nodejs-server/controllers/Store.js: +1ms
  swagger-tools:middleware:router       Store_placeOrder +0ms
  swagger-tools:middleware:router       Store_getOrderById +0ms
  swagger-tools:middleware:router       Store_deleteOrder +0ms
  swagger-tools:middleware:router     /somewhere/Sandbox/nodejs-server/controllers/StoreService.js: +0ms
  swagger-tools:middleware:router       StoreService_placeOrder +1ms
  swagger-tools:middleware:router       StoreService_getOrderById +0ms
  swagger-tools:middleware:router       StoreService_deleteOrder +0ms
  swagger-tools:middleware:router     /somewhere/Sandbox/nodejs-server/controllers/User.js: +1ms
  swagger-tools:middleware:router       User_createUser +0ms
  swagger-tools:middleware:router       User_createUsersWithArrayInput +0ms
  swagger-tools:middleware:router       User_createUsersWithListInput +0ms
  swagger-tools:middleware:router       User_loginUser +0ms
  swagger-tools:middleware:router       User_logoutUser +0ms
  swagger-tools:middleware:router       User_getUserByName +0ms
  swagger-tools:middleware:router       User_updateUser +0ms
  swagger-tools:middleware:router       User_deleteUser +1ms
  swagger-tools:middleware:router     /somewhere/Sandbox/nodejs-server/controllers/UserService.js: +0ms
  swagger-tools:middleware:router       UserService_createUser +0ms
  swagger-tools:middleware:router       UserService_createUsersWithArrayInput +0ms
  swagger-tools:middleware:router       UserService_createUsersWithListInput +0ms
  swagger-tools:middleware:router       UserService_loginUser +0ms
  swagger-tools:middleware:router       UserService_logoutUser +0ms
  swagger-tools:middleware:router       UserService_getUserByName +0ms
  swagger-tools:middleware:router       UserService_updateUser +0ms
  swagger-tools:middleware:router       UserService_deleteUser +0ms
>>
but when I try DELETE and GET operations on /users/{username}, as it could be seen in UI, only DELETE is available (GET handler is missing)

 <<
  swagger-tools:middleware:metadata DELETE /v2/users/truc +4ms
  swagger-tools:middleware:metadata   Is a Swagger path: true +0ms
  swagger-tools:middleware:metadata   Is a Swagger operation: true +1ms
  swagger-tools:middleware:metadata   Processing Parameters +0ms
  swagger-tools:middleware:metadata     username +1ms
  swagger-tools:middleware:metadata       Type: string +0ms
  swagger-tools:middleware:metadata       Value provided: true +0ms
  swagger-tools:middleware:metadata       Value: truc +1ms
  swagger-tools:middleware:validator DELETE /v2/users/truc +0ms
  swagger-tools:middleware:validator   Will process: yes +0ms
  swagger-tools:middleware:router DELETE /v2/users/truc +2ms
  swagger-tools:middleware:router   Will process: yes +1ms
  swagger-tools:middleware:router   Route handler: User_deleteUser +0ms
  swagger-tools:middleware:router   Mock mode: false +0ms
  swagger-tools:middleware:metadata GET /v2/users/truc +20s
  swagger-tools:middleware:metadata   Is a Swagger path: true +0ms
  swagger-tools:middleware:metadata   Is a Swagger operation: false +17ms
  swagger-tools:middleware:validator GET /v2/users/truc +0ms
  swagger-tools:middleware:validator   Will process: no +0ms
  swagger-tools:middleware:validator   Request validation: succeeded +0ms
  swagger-tools:middleware:router GET /v2/users/truc +0ms
  swagger-tools:middleware:router   Will process: no +1ms
  swagger-tools:middleware:router   No handler for method: GET +0ms
>>

So, yes, the behavior seen in UI have the same origin as the routing problem into the code.
Don't know how I can help more ... maybe going deeper into the code but it will take a while !!!

**Comment by Cooker-Monster** [comment] 2015-05-04 20:12
@webron : I know why !!!
It's because of file generated in /api/swagger.json.
the path is copied for each command rather than have only one path for many commands.
Due to this, some commands are missing by the router.
I guess that this could be easily fixed ...

**Comment by webron** [comment] 2015-05-05 08:20
@Cooker-Monster - can you clarify? Do you see the issue from the code generated by the codegen for nodejs or something else?

**Comment by Cooker-Monster** [comment] 2015-05-05 08:55
@webron: yes, the issue is located in codegen nodejs and to be more precise in NodeJSServerCodegen Java Class which uses swagger.mustache template to create api/swagger.json file.

api/swagge.json is wrong.

This is not an issue in Swagger tools as it was one of hypothesis ...

**Comment by webron** [comment] 2015-05-05 08:55
Got it, thanks.

**Comment by Cooker-Monster** [comment] 2015-05-05 08:57
You're welcome ! I'll dig to create a coffeescript generator for my needs ... wondering if it's valuable ?

**Comment by webron** [comment] 2015-05-05 09:00
Sure, anything could be great.

**Comment by templth** [comment] 2015-07-30 09:18
Hi all,

Hugo (https://github.com/hgwood) and I worked on a fix for this issue. We created a PR for the fix: https://github.com/swagger-api/swagger-codegen/pull/1037.

Feel free to make us your comments!

**Closed** 2015-08-24 07:44 UTC
Labels: Bug, P2, Server: Nodejs
