### ISSUE TITLE
Swagger latest 2.2.0 doesnot generate right nunit test code

### ISSUE THREAD

**Issue by manju1981** [swagger-api/swagger-codegen#3392] opened 2016-07-18 11:25 UTC
##### Description

The nunit test code generated using latest release has below compilation issue

##### Swagger-codegen version
2.2.0

##### Swagger declaration file content or url

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0117	'Assert' does not contain a definition for 'IsInstanceOfType'

**Comment by wing328** [comment] 2016-07-18 14:05
@manju1981 thanks for reporting the issue. As a workaround, please skip the API and model test for the time being by passing the following command line arguments while we're looking into the issue more:
```
-DmodelTests=false,apiTests=false
```

**Comment by wing328** [comment] 2016-07-18 15:34
@manju1981 I couldn't repeat the issue (MacOS, Xamarin). Can you tell us more about your development environment (OS, IDE)? Can you also check which version of nunit you're using?

**Comment by manju1981** [comment] 2016-07-19 11:01
@wing328  I am copying over the command i use to generate .net classes

wget http://repo1.maven.org/maven2/io/swagger/swagger-codegen-cli/2.2.0/swagger-codegen-cli-2.2.0.jar -O client/build_scripts/lib/swagger-codegen-cli.jar

java -jar client/build_scripts/lib/swagger-codegen-cli.jar generate -i src/api/swagger/swagger.yaml -l csharp -o client/generated -c client/config/config.json

Swaager.Yaml


swagger: "2.0"
info:
  version: "0.0.1"
  title: "Retail Control Data Service"
  description: "The Retail Control Service API provides industry-standard for flow, location types."

host: localhost

basePath: /

 schemes:

  - https
 consumes:
   - application/json

 produces:
|   - application/json
 paths:
   /deliveryoptions/smart:
       x-swagger-router-controller: smartdeliveryoptions
       get:
         description: Gets SMART Delivery Options For Fare
         operationId: smartdeliveryoptions
         parameters:
          - name: origin_nlc
            in: query
            description: "NLC code for origin"
            required: true
            type: string
          - name: destination_nlc
            in: query
            description: "NLC code for destination"
            required: true
            type: string
          - name: route_code
            in: query
            description: "Route Code for Fare"
            required: true
            type: string
          - name: ticket_type
            in: query
            description: "3 Char Ticket Type Code"
            required: true
            type: string
        responses:
          "200":
            description: Successful delivery options
            schema:
              $ref: "#/definitions/DeliveryResponse"
          "404":
            description: Delivery Option not available
            schema:
              $ref: "#/definitions/ErrorResponse"
          default:
            description: Error
            schema:
              $ref: "#/definitions/ErrorResponse"
        tags:
          - DeliveryOptions
  /diagnostics/healthcheck:
    x-swagger-router-controller: diagnostics
    get:
      description: "Checks service is running"
      operationId: healthcheck
      responses:
        "200":
          description: "The service is healthy"
          schema:
            $ref: '#/definitions/SuccessResponse'
        default:
          description: "The service reports a problem"
          schema:
            $ref: "#/definitions/ErrorResponse"
      tags:
        - Diagnostics
  /diagnostics/installationcheck:
    x-swagger-router-controller: diagnostics
    get:
      description: "Checks service is running"
      operationId: installationcheck
      responses:
        "200":
          description: "The system is healthy"
          schema:
            $ref: '#/definitions/SuccessResponse'
        default:
          description: "The service reports a problem"
          schema:
            $ref: "#/definitions/ErrorResponse"
      tags:
        - Diagnostics
  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
  SuccessResponse:
    required:
      - message
    properties:
      message:
        type: string
  DeliveryResponse:
      required:
        - fulfilmentdetails
      properties:
        fulfilmentdetails:
          type: array
          items:
            $ref: "#/definitions/DeliveryOption"
  DeliveryOption:
      properties:
        fulfilmentMethod:
          type: string
        ipType:
          type: string
        ipSubType:
          type: string
        operatorId:
          type: string
        issuerId:
          type: string


config.json

  {
  "packageName": "RetailControlServiceData.Client"
}

Nunit version:3.2.1 used

Generated Test classes use depricated nunit assert api.
Note Pipe added at   - application/json is for rendering text cleanly

**Comment by lnunno** [comment] 2016-07-19 19:44
If we are using the maven plugin do you have a good example of passing these commands to skip the generation of the unit tests in the ``pom.xml``?

**Comment by wing328** [comment] 2016-07-20 04:11
@jimschubert when you've time, can you help a test to see if you can repeat the issue?

**Comment by wing328** [comment] 2016-07-20 06:53
Here is a screen cap showing the solution compiles without issue (Mac, Xamarin 5.10.3)

<img width="1038" alt="screen shot 2016-07-20 at 2 51 11 pm" src="https://cloud.githubusercontent.com/assets/934260/16977602/a2bdcbf0-4e89-11e6-938b-4d8b4b977853.png">

**Comment by wing328** [comment] 2016-07-20 07:08
For those who encountered the issue, please provide more information such as OS and IDE.

**Comment by wing328** [comment] 2016-07-20 18:02
Another workaround is to use the `-t` option to provide customized template path and comment out the lines with issue in the mustache template files.

**Comment by jimschubert** [comment] 2016-07-21 02:38
I've can't repro against v2.2.0's petstore.yaml from `modules/swagger-codegen/src/test/resources/2_0/petstore.yaml`).

**Xamarin 6.0.1 (build 9), OS X** 

NUnit tests succeed:

![image](https://cloud.githubusercontent.com/assets/109659/17008981/67ca07bc-4ec4-11e6-823c-22b44e7bb851.png)

After this test, I deleted and regenerated so there's no question of previously built artifacts.

**Visual Studio 2015, Windows 10**

Building on Windows does in fact result in the error:

![image](https://cloud.githubusercontent.com/assets/109659/17009500/4a9ff548-4ec9-11e6-8c3b-5f9f130463cf.png)

From my initial investigation, it looks like a couple of problems. First, the project references for NUnit are missing the target framework. See [TestProject.mustache](https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/csharp/TestProject.mustache#L85) how there's a `{{targetFrameworkNuget}}` after `/lib` on other non-NUnit dependencies. Once the correct lib path is defined, there is an issue with the `IsInstanceOfType` as reported in the issue. It looks to be caused by 6ddf34ce8aa7 when NUnit was updated to 3.2.1.

The reason this doesn't cause problems in Xamarin is because it's bundled with NUnit 2.8.7 (About -> Show Details -> _scroll down_ Show Loaded Assemblies). NUnit 3.x has lots of breaking changes, one of which is finally removing `IsInstanceOfType` which has been deprecated for like 6 years. The fix should be to just change this to `IsInstanceOf`.

I can work on a fix for this, but probably won't be done with it tonight.

**Comment by jimschubert** [comment] 2016-07-21 03:02
Hm... With my changes, I've uncovered that Xamarin can't run tests against NUnit 3.x ([see this post](https://forums.xamarin.com/discussion/55863/upgrading-nunit-to-3-0-0-in-my-project-breaks-the-tests)).

@wing328 I've pushed the fixes I mentioned above to https://github.com/jimschubert/swagger-codegen/tree/cs/nunit-321-fixes. As mentioned in the commit on that branch, the fixes aren't a complete solution. Updating to 3.2.1 means Xamarin won't work. We could look into some hacky version manipulation on the project's imports of NUnit and only include 2.8.7 if we can detect Xamarin. I don't like that approach, though, because it could easily open us to using newer APIs and introducing bugs. I think the best approach would be to roll back to NUnit 2.8.7, but I'm not sure of the reason for upgrading to NUnit 3.2.1.

Oddly, we can't just exclude NUnit from the project file for Xamarin, otherwise the project won't load the references to the bundled NUnit and the test project won't compile. I don't know if it's a bug in Xamarin-- or if it's some weird msbuild project logic that I've never encountered before-- but it only seems to fall back to the bundled NUnit if you have a reference to an invalid NUnit location in the project file. The project _thinks_ it has NUnit referenced, can't find it, so defers to the bundled 2.8.7.

@lunat A quick fix would be to roll back the NUnit dependency via nuget to version 2.8.7. Then your tests should pass until a resolution is committed.

**Comment by wing328** [comment] 2016-07-21 03:52
>  I think the best approach would be to roll back to NUnit 2.8.7, but I'm not sure of the reason for upgrading to NUnit 3.2.1.

Yes, I agree and thanks for performing more tests to pinpoint the issue.

We will only consider upgrading to NUnit 3.x when it's ready for different platform/IDE.

As a follow up item, I'll setup a CI test via Appveyor to ensure the issue can be caught by CI moving forward.

**Comment by wing328** [comment] 2016-07-21 05:31
For the reason upgrading to 3.2.1, we did that as part of the dependency review in preparation for the 2.2.0 release (a while ago) so as to ensure the API clients or server stubs generated by Swagger Codegen are using the latest stable version for all the dependencies.

**Closed** 2016-07-21 10:17 UTC
Labels: Client: C-Sharp, Issue: Platform

**Comment by wing328** [comment] 2016-07-25 14:02
@manju1981 @lnunno the issue has been addressed in the latest master. Please pull the latest to give it a try.
