### ISSUE TITLE
Multiple APIs in spec not recursed

### ISSUE THREAD

**Issue by tibbon** [swagger-api/swagger-codegen#1426] opened 2015-10-22 18:05 UTC
I'm attempting to use the codegen to create a Ruby gem for OpenDining. 

The documentation site is at: http://docs.opendining.net/api/
The file I'm attempting to use for generation is at: http://docs.opendining.net/api/swagger/api.js

I'm running the command `./run-in-docker.sh generate  -i http://docs.opendining.net/api/swagger/api.js  -l ruby   -o samples/client/opendining/ruby ` but it doesn't actually generate any code for the APIs, or recurse into the definitions to get the models either.

**Comment by fehguy** [comment] 2015-10-22 18:12
Hi @tibbon do you work with OpenDining.net?  The issue is that the swagger definition has a few issues with it.

**Comment by tibbon** [comment] 2015-10-22 18:15
I don't, I'm just trying to consume the API in a quick and easy way. 

I'm in touch with them however, and if I can give specific requests to them... they might do it. (Should i have them regen it using Swagger 2.0? etc). What is the main problem that it has, and what likely caused it?

**Comment by fehguy** [comment] 2015-10-26 01:56
Great-- @tibbon to move forward quickly on this, I suggest pulling down the files into a directory and make local changes to the files.  It's pretty fast to do so.

**Comment by wing328** [comment] 2016-01-27 08:46
@tibbon if you need help with this issue, please reply to let us know.

Closing this issue for now.

**Closed by wing328** 2016-01-27 08:46 UTC
