### ISSUE TITLE
"Generate Client" -> "C# .NET 2.0" adds redundant subclass get/set methods from superclass, that hide superclass implementation

### ISSUE THREAD

**Issue by webron** [swagger-api/swagger-codegen#5524] opened 2017-05-01 21:37 UTC
_From @patrickoshaughnessey on May 1, 2017 21:17_

If you create a subclass of an object using the 'allOf' mechanism, then generate the C# 2.0 code, you end up with getters/setters generated in both the superclass and subclass for the superclass's properties. An older version of the editor used to properly generate only the superclass methods.

_Copied from original issue: swagger-api/swagger-editor#1310_

**Comment by jimschubert** [comment] 2017-05-02 01:20
@patrickoshaughnessey How long ago did the editor generate the code as expected? The C# 2.0 client generator has only had [6 or so commits](https://github.com/swagger-api/swagger-codegen/commits/master/modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/CsharpDotNet2ClientCodegen.java) in the past year, so a timeframe may help track down the cause.

**Comment by patrickoshaughnessey** [comment] 2017-05-02 04:12
Honestly, it was probably over 6 months ago.

**Comment by patrickoshaughnessey** [comment] 2017-05-02 04:15
It was at least one version back from whichever version is installed at http://editor2.swagger.io

**Comment by wing328** [comment] 2017-05-03 13:24
@patrickoshaughnessey I believe Swagger Editor (2) is using https://generator.swagger.io (part of Swagger Codegen project) for code generation.

Can you please try the stable release 2.2.2 or 2.2.1 to see which version works for you?

https://github.com/swagger-api/swagger-codegen/releases

Let us know if you need help using the JAR (2.2.2 or 2.2.1) to generate C# (2.0) API client. The project's README is a good starting point.

**Comment by wing328** [comment] 2017-07-24 11:53
Closing this as there's no update further update.

**Closed by wing328** 2017-07-24 11:53 UTC
Labels: Admin: 2.2.3 backlog, Client: C-Sharp, Issue: Bug
